# anemotaxis
# Autogenerated from man page /usr/lib/jvm/default/man/man6/anemotaxis.6.gz
complete -c anemotaxis -o visual -d 'Specify which visual to use'
complete -c anemotaxis -o window -d 'Draw on a newly-created window.   This is the default'
complete -c anemotaxis -o root -d 'Draw on the root window'
complete -c anemotaxis -o delay -d 'Per-frame delay, in microseconds.   Default: 20000 (0. 02 seconds. )'
complete -c anemotaxis -o distance -d 'Max initial distance to the source .   10 - 250.   Default: 40'
complete -c anemotaxis -o sources -d 'Max number of sources.   Default: 25'
complete -c anemotaxis -o searchers -d 'Max number of searchers.  Default: 25'
complete -c anemotaxis -o fps -d 'Display the current frame rate and CPU load'

