# ansible-vault
# Autogenerated from man page /usr/lib/jvm/default/man/man1/ansible-vault.1.gz
complete -c ansible-vault -l version -d 'show program\'s version number, config file location, configured module search…'
complete -c ansible-vault -s h -l help -d 'show this help message and exit'
complete -c ansible-vault -s v -l verbose -d 'verbose mode (-vvv for more, -vvvv to enable connection debugging) ACTIONS cr…'
complete -c ansible-vault -l ask-vault-password -l ask-vault-pass -d 'ask for vault password'
complete -c ansible-vault -l encrypt-vault-id -d 'the vault id used to encrypt (required if more than one vault-id is provided)'
complete -c ansible-vault -l vault-id -d 'the vault identity to use'
complete -c ansible-vault -l vault-password-file -l vault-pass-file -d 'vault password file decrypt decrypt the supplied file using the provided vaul…'
complete -c ansible-vault -l output -d 'output file name for encrypt or decrypt; use - for stdout'
complete -c ansible-vault -l show-input -d 'Do not hide input when prompted for the string to encrypt'
complete -c ansible-vault -l stdin-name -d 'Specify the variable name for stdin'
complete -c ansible-vault -s n -l name -d 'Specify the variable name'
complete -c ansible-vault -s p -l prompt -d 'Prompt for the string to encrypt rekey re-encrypt a vaulted file with a new s…'
complete -c ansible-vault -l new-vault-id -d 'the new vault identity to use for rekey'
complete -c ansible-vault -l new-vault-password-file -d 'new vault password file for rekey'

