# ansible-galaxy
# Autogenerated from man page /usr/lib/jvm/default/man/man1/ansible-galaxy.1.gz
complete -c ansible-galaxy -l version -d 'show program\'s version number, config file location, configured module search…'
complete -c ansible-galaxy -s h -l help -d 'show this help message and exit'
complete -c ansible-galaxy -s v -l verbose -d 'verbose mode (-vvv for more, -vvvv to enable connection debugging) ACTIONS co…'

