# antinspect
# Autogenerated from man page /usr/lib/jvm/default/man/man6/antinspect.6.gz
complete -c antinspect -o window -d 'Draw on a newly-created window.   This is the default'
complete -c antinspect -o root -d 'Draw on the root window'
complete -c antinspect -o install -d 'Install a private colormap for the window'
complete -c antinspect -o shadows -d 'Draw shadows on ground'
complete -c antinspect -o visual -d 'Specify which visual to use'
complete -c antinspect -o fps -d 'Display the current frame rate, CPU load, and polygon count'

