# antmaze
# Autogenerated from man page /usr/lib/jvm/default/man/man6/antmaze.6.gz
complete -c antmaze -o window -d 'Draw on a newly-created window.   This is the default'
complete -c antmaze -o root -d 'Draw on the root window'
complete -c antmaze -o install -d 'Install a private colormap for the window'
complete -c antmaze -o visual -d 'Specify which visual to use'
complete -c antmaze -o fps -d 'Display the current frame rate, CPU load, and polygon count'

