# apollonian
# Autogenerated from man page /usr/lib/jvm/default/man/man6/apollonian.6.gz
complete -c apollonian -o visual -d 'Specify which visual to use'
complete -c apollonian -o window -d 'Draw on a newly-created window.   This is the default'
complete -c apollonian -o root -d 'Draw on the root window'
complete -c apollonian -o label -o no-label -d 'Draw Labels.   Boolean'
complete -c apollonian -o altgeom -o no-altgeom -d 'Include Alternate Geometries.   Boolean'
complete -c apollonian -o cycles -d 'Depth. 	1 - 20.   Default: 20'
complete -c apollonian -o ncolors -d 'Number of Colors.   Default: 64'
complete -c apollonian -o delay -d 'Per-frame delay, in microseconds.   Default: 1000000 (1. 00 seconds. )'
complete -c apollonian -o fps -d 'Display the current frame rate and CPU load'

