# atunnel
# Autogenerated from man page /usr/lib/jvm/default/man/man6/atunnel.6.gz
complete -c atunnel -o window -d 'Draw on a newly-created window.   This is the default'
complete -c atunnel -o root -d 'Draw on the root window'
complete -c atunnel -o install -d 'Install a private colormap for the window'
complete -c atunnel -o visual -d 'Specify which visual to use'
complete -c atunnel -o fps -d 'Display the current frame rate, CPU load, and polygon count'
complete -c atunnel -o texture -d 'Show a textured tunnel.  This is the default'
complete -c atunnel -o no-texture -d 'Disables texturing the animation'
complete -c atunnel -o wire -d 'Draw a wireframe rendition of the tunnel'

