# banner
# Autogenerated from man page /usr/lib/jvm/default/man/man1/banner.1.gz
complete -c banner -s C -l center -d 'Center each line of the message'
complete -c banner -s h -l help -d 'Print a usage message on standard output and exit successfully'
complete -c banner -s l -l use-letters -d 'Use individual characters when drawing the letters, that is: Draw an `a\' usin…'
complete -c banner -s V -l version -d 'Print version information on standard output then exit successfully'
complete -c banner -s c -l use-char -d 'Use the given  character when drawing the letters'
complete -c banner -s f -l font -d 'Select font number  cols for drawing characters'
complete -c banner -s w -l width -d 'Assume the screen is cols columns wide.  The default is 75'

