# beats
# Autogenerated from man page /usr/lib/jvm/default/man/man6/beats.6.gz
complete -c beats -o visual -d 'Specify which visual to use'
complete -c beats -o window -d 'Draw on a newly-created window.   This is the default'
complete -c beats -o root -d 'Draw on the root window'
complete -c beats -o delay -d 'Per-frame delay, in microseconds.   Default: 30000 (0. 03 seconds. )'
complete -c beats -o count -d 'Number of balls.   Default: 30'
complete -c beats -o cycle -d 'Cycle type to use (Default: -1):   -1 - pseudo-random based on current time  …'
complete -c beats -o tick -o no-tick -d 'Add a tick for \'clockwise\' and \'galaxy\' patterns'
complete -c beats -o blur -o no-blur -d 'Add motion blur to the ball movement'
complete -c beats -o wireframe -o no-wireframe -d 'Render in wireframe instead of solid'
complete -c beats -o fps -d 'Display the current frame rate, CPU load, and polygon count'

