# binaryring
# Autogenerated from man page /usr/lib/jvm/default/man/man6/binaryring.6.gz
complete -c binaryring -o fps -d 'Display the current frame rate and CPU load'
complete -c binaryring -o install -d 'Install a private colormap for the window'
complete -c binaryring -o mono -d 'If on a color display, pretend we\'re on a monochrome display'
complete -c binaryring -o noinstall -d 'Don\'t install a private colormap for the window'
complete -c binaryring -o root -d 'Draw on the root window'
complete -c binaryring -o visual -d 'Specify which visual to use'
complete -c binaryring -o window -d 'Draw on a newly-created window.  This is the default'
complete -c binaryring -o window-id -d 'Specify which window id to use'
complete -c binaryring -o color -d 'Particles have random generated colors that gradually change over time'
complete -c binaryring -o no-color -d 'Use the original black and white visualization'
complete -c binaryring -o growth-delay -d 'Delay in ms between growth cycles'
complete -c binaryring -o particles-number -d 'The number of particles in the system'
complete -c binaryring -o ring-radius -d 'The radius of the ring where the particles are born, in pixels'

