# boing
# Autogenerated from man page /usr/lib/jvm/default/man/man6/boing.6.gz
complete -c boing -o window -d 'Draw on a newly-created window.   This is the default'
complete -c boing -o root -d 'Draw on the root window'
complete -c boing -o install -d 'Install a private colormap for the window'
complete -c boing -o visual -d 'Specify which visual to use'
complete -c boing -o delay -d 'The delay between frames of the animation, in microseconds: default 15000'
complete -c boing -o smooth -d 'Draw a smooth sphere instead of a faceted polyhedron'
complete -c boing -o lighting -d 'Do shaded lighting instead of flat colors'
complete -c boing -o scanlines -d 'If the window is large enough, draw horizontal lines to simulate the scanline…'
complete -c boing -o speed -d 'Change the animation speed; 0. 5 to go half as fast, 2. 0 to go twice as fast'
complete -c boing -o no-spin -d 'Don\'t rotate the ball'
complete -c boing -o angle -d 'The jaunty angle at which the ball sits.   Default 15 degrees'
complete -c boing -o size -d 'How big the ball is; default 0. 5 meaning about half the size of the window'
complete -c boing -o parallels -d '-meridians n The pattern of rectangles on the ball.   Default 8x16'
complete -c boing -o wireframe -d 'Look crummy'
complete -c boing -o meridians -d 'The pattern of rectangles on the ball.   Default 8x16'
complete -c boing -o fps -d 'Display the current frame rate, CPU load, and polygon count'

