# boxfit
# Autogenerated from man page /usr/lib/jvm/default/man/man6/boxfit.6.gz
complete -c boxfit -o visual -d 'Specify which visual to use'
complete -c boxfit -o window -d 'Draw on a newly-created window.   This is the default'
complete -c boxfit -o root -d 'Draw on the root window'
complete -c boxfit -o delay -d 'How much of a delay should be introduced between steps of the animation'
complete -c boxfit -o count -d 'How many boxes or circles to animate simultaneously; default 50'
complete -c boxfit -o growby -d 'How many pixels the objects should grow by, each frame.   Default 1'
complete -c boxfit -o spacing -d 'How many pixels of space should be left between the objects.   Default 1'
complete -c boxfit -o border -d 'Thickness of the colored border around each object.   Default 1'
complete -c boxfit -o circles -o squares -o random -d 'Draw circles, squares, or choose randomly (the default)'
complete -c boxfit -o grab -d 'Normally it colors the boxes with a horizontal or vertical gradient'
complete -c boxfit -o peek -d 'This option says to briefly show you the underlying image before beginning'
complete -c boxfit -o fps -d 'Display the current frame rate and CPU load'

