# buildah-containers
# Autogenerated from man page /usr/lib/jvm/default/man/man1/buildah-containers.1.gz
complete -c buildah-containers -l all -s a -d 'List information about all containers, including those which were not created…'
complete -c buildah-containers -l filter -s f -d 'Filter output based on conditions provided.  Valid filters are listed below:'
complete -c buildah-containers -l format -d 'Pretty-print containers using a Go template'
complete -c buildah-containers -l json -d 'Output in JSON format'
complete -c buildah-containers -l noheading -s n -d 'Omit the table headings from the listing of containers'
complete -c buildah-containers -l notruncate -d 'Do not truncate IDs and image names in the output'
complete -c buildah-containers -l quiet -s q -d 'Displays only the container IDs'

