# buildah-images
# Autogenerated from man page /usr/lib/jvm/default/man/man1/buildah-images.1.gz
complete -c buildah-images -l all -s a -d 'Show all images, including intermediate images from a build'
complete -c buildah-images -l digests -d 'Show the image digests'
complete -c buildah-images -l filter -s f -d 'Filter output based on conditions provided (default [])'
complete -c buildah-images -l format -d 'Pretty-print images using a Go template'
complete -c buildah-images -l history -d 'Display the image name history'
complete -c buildah-images -l json -d 'Display the output in JSON format'
complete -c buildah-images -l noheading -s n -d 'Omit the table headings from the listing of images'
complete -c buildah-images -l no-trunc -d 'Do not truncate output'
complete -c buildah-images -l quiet -s q -d 'Displays only the image IDs'

