# buildah-copy
# Autogenerated from man page /usr/lib/jvm/default/man/man1/buildah-copy.1.gz
complete -c buildah-copy -l add-history -d 'Add an entry to the history which will note the digest of the added content'
complete -c buildah-copy -l chmod -d 'Sets the access permissions of the destination content'
complete -c buildah-copy -l chown -d 'Sets the user and group ownership of the destination content'
complete -c buildah-copy -l contextdir -d 'Build context directory'
complete -c buildah-copy -l from -d 'Use the root directory of the specified working container or image as the roo…'
complete -c buildah-copy -l ignorefile -d 'Path to an alternative . containerignore (. dockerignore) file'
complete -c buildah-copy -l quiet -s q -d 'Refrain from printing a digest of the copied content'

