# buildah-pull
# Autogenerated from man page /usr/lib/jvm/default/man/man1/buildah-pull.1.gz
complete -c buildah-pull -l all-tags -s a -d 'All tagged images in the repository will be pulled'
complete -c buildah-pull -l arch -d 'Set the ARCH of the image to be pulled to the provided value instead of using…'
complete -c buildah-pull -l authfile -d 'Path of the authentication file'
complete -c buildah-pull -l cert-dir -d 'Use certificates at path (*. crt, *. cert, *. key) to connect to the registry'
complete -c buildah-pull -l creds -d 'The [username[:password]] to use to authenticate with the registry if required'
complete -c buildah-pull -l decryption-key -d 'The [key[:passphrase]] to be used for decryption of images'
complete -c buildah-pull -l quiet -s q -d 'If an image needs to be pulled from the registry, suppress progress output'
complete -c buildah-pull -l os -d 'Set the OS of the image to be pulled instead of using the current operating s…'
complete -c buildah-pull -l policy -d 'Pull image policy.  The default is missing'
complete -c buildah-pull -l remove-signatures -d 'Don\'t copy signatures when pulling images'
complete -c buildah-pull -l tls-verify -d 'Require HTTPS and verification of certificates when talking to container regi…'
complete -c buildah-pull -l variant -d 'Set the architecture variant of the image to be pulled'

