# buildah-manifest-add
# Autogenerated from man page /usr/lib/jvm/default/man/man1/buildah-manifest-add.1.gz
complete -c buildah-manifest-add -l all -d 'If the image which should be added to the list or index is itself a list or i…'
complete -c buildah-manifest-add -l annotation -d 'Set an annotation on the entry for the newly-added image'
complete -c buildah-manifest-add -l arch -d 'Override the architecture which the list or index records as a requirement fo…'
complete -c buildah-manifest-add -l authfile -d 'Path of the authentication file'
complete -c buildah-manifest-add -l cert-dir -d 'Use certificates at path (*. crt, *. cert, *. key) to connect to the registry'
complete -c buildah-manifest-add -l creds -d 'The [username[:password]] to use to authenticate with the registry if required'
complete -c buildah-manifest-add -l features -d 'Specify the features list which the list or index records as requirements for…'
complete -c buildah-manifest-add -l os -d 'Override the OS which the list or index records as a requirement for the image'
complete -c buildah-manifest-add -l os-features -d 'Specify the OS features list which the list or index records as requirements …'
complete -c buildah-manifest-add -l os-version -d 'Specify the OS version which the list or index records as a requirement for t…'
complete -c buildah-manifest-add -l tls-verify -d 'Require HTTPS and verification of certificates when talking to container regi…'
complete -c buildah-manifest-add -l variant -d 'Specify the variant which the list or index records for the image'

