# buildah-umount
# Autogenerated from man page /usr/lib/jvm/default/man/man1/buildah-umount.1.gz
complete -c buildah-umount -l all -s a -d 'All of the currently mounted containers will be unmounted'

