# buildah-info
# Autogenerated from man page /usr/lib/jvm/default/man/man1/buildah-info.1.gz
complete -c buildah-info -l debug -s D -d 'Show additional information'
complete -c buildah-info -l format -d 'Use template as a Go template when formatting the output'

