# buildah-inspect
# Autogenerated from man page /usr/lib/jvm/default/man/man1/buildah-inspect.1.gz
complete -c buildah-inspect -l format -s f -d 'Use template as a Go template when formatting the output'
complete -c buildah-inspect -l type -s t -d 'Specify whether object is a container, image or a manifest list'

