# ccurve
# Autogenerated from man page /usr/lib/jvm/default/man/man6/ccurve.6.gz
complete -c ccurve -o visual -d 'Specify which visual to use'
complete -c ccurve -o window -d 'Draw on a newly-created window.   This is the default'
complete -c ccurve -o root -d 'Draw on the root window'
complete -c ccurve -o delay -d 'Delay. 	0 - 60.   Default: 1'
complete -c ccurve -o pause -d 'Duration.   1 - 60.   Default: 3'
complete -c ccurve -o limit -d 'Density.   3 - 300000.   Default: 200000'
complete -c ccurve -o fps -d 'Display the current frame rate and CPU load'

