# ciscodump
# Autogenerated from man page /usr/lib/jvm/default/man/man1/ciscodump.1.gz
complete -c ciscodump -l help -d 'PD Print program arguments'
complete -c ciscodump -l version -d 'Print program version'
complete -c ciscodump -l extcap-interfaces -d 'List available interfaces'
complete -c ciscodump -l extcap-interface -d 'Use specified interfaces'
complete -c ciscodump -l extcap-dlts -d 'List DLTs of specified interface'
complete -c ciscodump -l extcap-config -d 'List configuration options of specified interface'
complete -c ciscodump -l capture -d 'Start capturing from specified interface and save it in place specified by --…'
complete -c ciscodump -l fifo -d 'Save captured packet to file or send it through pipe'
complete -c ciscodump -l remote-host -d 'The address of the remote host for capture'
complete -c ciscodump -l remote-port -d 'The \\s-1SSH\\s0 port of the remote host'
complete -c ciscodump -l remote-username -d 'The username for ssh authentication'
complete -c ciscodump -l remote-password -d 'The password to use (if not ssh-agent and pubkey are used)'
complete -c ciscodump -l remote-filter -d 'The remote filter on the router'
complete -c ciscodump -l sshkey -d 'The path to a private key for authentication'
complete -c ciscodump -l remote-interface -d 'The remote network interface to capture from'

