# cmus
# Autogenerated from man page /usr/lib/jvm/default/man/man1/cmus.1.gz
complete -c cmus -l listen
complete -c cmus -l passwd
complete -c cmus -l plugins
complete -c cmus -l show-cursor
complete -c cmus -l help
complete -c cmus -l version
complete -c cmus -o '10%'
complete -c cmus -s l -d 'add to library'
complete -c cmus -s p -d 'add to playlist'
complete -c cmus -s q -d 'add play queue'
complete -c cmus -s Q -d 'prepend to play queue Supported files are based on the loaded input plugins'
complete -c cmus -s f -d 'overwrite existing binding Valid contexts: common (i. e'
complete -c cmus -s i -d 'ask before exiting raise-vte'
complete -c cmus -s L -d 'save filtered library views'
complete -c cmus -s n

