# compass
# Autogenerated from man page /usr/lib/jvm/default/man/man6/compass.6.gz
complete -c compass -o visual -d 'Specify which visual to use'
complete -c compass -o window -d 'Draw on a newly-created window.   This is the default'
complete -c compass -o root -d 'Draw on the root window'
complete -c compass -o delay -d 'Per-frame delay, in microseconds.   Default: 20000 (0. 02 seconds. )'
complete -c compass -o db -o no-db -d 'Double Buffer. 	Boolean'
complete -c compass -o fps -d 'Display the current frame rate and CPU load'

