# containers-storage-add-names
# Autogenerated from man page /usr/lib/jvm/default/man/man1/containers-storage-add-names.1.gz
complete -c containers-storage-add-names -s n -l name -d 'Specifies a name to add to the layer, image, or container'

