# containers-storage-get-container-data
# Autogenerated from man page /usr/lib/jvm/default/man/man1/containers-storage-get-container-data.1.gz
complete -c containers-storage-get-container-data -s f -l file -d 'Write the data to a file instead of stdout'

