# containers-storage-exists
# Autogenerated from man page /usr/lib/jvm/default/man/man1/containers-storage-exists.1.gz
complete -c containers-storage-exists -s c -l container -d 'Only succeed if the names or IDs are that of containers'
complete -c containers-storage-exists -s i -l image -d 'Only succeed if the names or IDs are that of images'
complete -c containers-storage-exists -s l -l layer -d 'Only succeed if the names or IDs are that of layers'
complete -c containers-storage-exists -s q -l quiet -d 'Suppress output'

