# containers-storage-create-image
# Autogenerated from man page /usr/lib/jvm/default/man/man1/containers-storage-create-image.1.gz
complete -c containers-storage-create-image -s n -l name -d 'Sets an optional name for the image'
complete -c containers-storage-create-image -s i -l id -d 'Sets the ID for the image.   If none is specified, one is generated'
complete -c containers-storage-create-image -s m -l metadata -d 'Sets the metadata for the image to the specified value'
complete -c containers-storage-create-image -s f -l metadata-file -d 'Sets the metadata for the image to the contents of the specified file'

