# containers-storage-set-container-data
# Autogenerated from man page /usr/lib/jvm/default/man/man1/containers-storage-set-container-data.1.gz
complete -c containers-storage-set-container-data -s f -l file -d 'Read the data contents from a file instead of stdin'

