# containers-storage-copy
# Autogenerated from man page /usr/lib/jvm/default/man/man1/containers-storage-copy.1.gz
complete -c containers-storage-copy -l chown -d 'Set owners for the new copies to the specified UID/GID pair'

