# containers-storage-mount
# Autogenerated from man page /usr/lib/jvm/default/man/man1/containers-storage-mount.1.gz
complete -c containers-storage-mount -s l -l label -d 'Specify an SELinux context for the mounted layer'

