# crystal
# Autogenerated from man page /usr/lib/jvm/default/man/man6/crystal.6.gz
complete -c crystal -o visual -d 'Specify which visual to use'
complete -c crystal -o window -d 'Draw on a newly-created window.   This is the default'
complete -c crystal -o root -d 'Draw on the root window'
complete -c crystal -o grid -o no-grid -d 'Whether to draw grid'
complete -c crystal -o cell -o no-cell -d 'Whether to draw the cell'
complete -c crystal -o centre -o no-centre -d 'Whether to center on screen'
complete -c crystal -o nx -d 'Horizontal Symmetries. 	-10 - 10.   Default: -3'
complete -c crystal -o ny -d 'Vertical Symmetries.   -10 - 10.   Default: -3'
complete -c crystal -o count -d 'Count. 	-5000 - 5000.   Default: -500'
complete -c crystal -o delay -d 'Per-frame delay, in microseconds.   Default: 60000 (0. 06 seconds. )'
complete -c crystal -o ncolors -d 'Number of Colors.   Default: 100'
complete -c crystal -o fps -d 'Display the current frame rate and CPU load'

