# cubicgrid
# Autogenerated from man page /usr/lib/jvm/default/man/man6/cubicgrid.6.gz
complete -c cubicgrid -o window -d 'Draw on a newly-created window.   This is the default'
complete -c cubicgrid -o root -d 'Draw on the root window'
complete -c cubicgrid -o install -d 'Install a private colormap for the window'
complete -c cubicgrid -o visual -d 'Specify which visual to use'
complete -c cubicgrid -o delay -d 'How long to pause between frames.   Default is 20000, or 0. 02 second'
complete -c cubicgrid -o mono -d 'Draw in black and white.   If not used, a fixed all-color scheme is chosen'
complete -c cubicgrid -o speed -d 'The maximum speed of the rotation'
complete -c cubicgrid -o zoom -d 'Size of the lattice'
complete -c cubicgrid -o ticks -d 'The count of points drawn along every axis.   10 - 100.   The default is 30'
complete -c cubicgrid -o bigdots -d 'Draw the points twice as big'
complete -c cubicgrid -o fps -d 'Display the current frame rate, CPU load, and polygon count'
complete -c cubicgrid -o symmetry -d 'Which crystalographic symmetry system to use'

