# cwaves
# Autogenerated from man page /usr/lib/jvm/default/man/man6/cwaves.6.gz
complete -c cwaves -o window -d 'Draw on a newly-created window.   This is the default'
complete -c cwaves -o root -d 'Draw on the root window'
complete -c cwaves -o mono -d 'If on a color display, pretend we\'re on a monochrome display'
complete -c cwaves -o install -d 'Install a private colormap for the window'
complete -c cwaves -o visual -d 'Specify which visual to use'
complete -c cwaves -o delay -d 'How much of a delay should be introduced between steps of the animation'
complete -c cwaves -o waves -d 'How many cosines to add together'
complete -c cwaves -o colors -d 'How many colors to use.   Default 800'
complete -c cwaves -o fps -d 'Display the current frame rate and CPU load'

