# dangerball
# Autogenerated from man page /usr/lib/jvm/default/man/man6/dangerball.6.gz
complete -c dangerball -o visual -d 'Specify which visual to use'
complete -c dangerball -o window -d 'Draw on a newly-created window.   This is the default'
complete -c dangerball -o root -d 'Draw on the root window'
complete -c dangerball -o delay -d 'Per-frame delay, in microseconds.   Default: 30000 (0. 03 seconds. )'
complete -c dangerball -o speed -d 'Spike growth frequency.   0. 0 - 0. 25.   Default: 0. 05'
complete -c dangerball -o count -d 'Number o spikes.   Default: 30'
complete -c dangerball -o wander -o no-wander -d 'Whether the object should wander around the screen'
complete -c dangerball -o spin -o no-spin -d 'Whether the object should spin'
complete -c dangerball -o wireframe -o no-wireframe -d 'Render in wireframe instead of solid'
complete -c dangerball -o fps -d 'Display the current frame rate, CPU load, and polygon count'

