# deepstars
# Autogenerated from man page /usr/lib/jvm/default/man/man6/deepstars.6.gz
complete -c deepstars -o visual -d 'Specify which visual to use'
complete -c deepstars -o window -d 'Draw on a newly-created window.   This is the default'
complete -c deepstars -o root -d 'Draw on the root window'
complete -c deepstars -o delay -d 'Per-frame delay, in microseconds.   Default: 30000 (0. 03 seconds)'
complete -c deepstars -o speed -d 'Animation speed.   2. 0 means twice as fast, 0. 5 means half as fast'
complete -c deepstars -o smear -d 'How long the vapor trails should be.  2. 0 means twice as long, 0'

