# discoball
# Autogenerated from man page /usr/lib/jvm/default/man/man6/discoball.6.gz
complete -c discoball -o visual -d 'Specify which visual to use'
complete -c discoball -o window -d 'Draw on a newly-created window.   This is the default'
complete -c discoball -o root -d 'Draw on the root window'
complete -c discoball -o delay -d 'Per-frame delay, in microseconds.   Default: 30000 (0. 03 seconds)'
complete -c discoball -o speed -d 'Animation speed.   2. 0 means twice as fast, 0. 5 means half as fast'
complete -c discoball -o count -d 'Number of rows of tiles on the ball.   10 - 100.   Default: 30'
complete -c discoball -o wander -o no-wander -d 'Whether the object should wander around the screen'
complete -c discoball -o spin -o no-spin -d 'Whether the scene should spin'
complete -c discoball -o wireframe -o no-wireframe -d 'Render in wireframe instead of solid'
complete -c discoball -o fps -o no-fps -d 'Whether to show a frames-per-second display at the bottom of the screen'

