# docker-trust-sign
# Autogenerated from man page /usr/lib/jvm/default/man/man1/docker-trust-sign.1.gz
complete -c docker-trust-sign -s h -l help -d '	help for sign'
complete -c docker-trust-sign -l local -d '	Sign a locally tagged image SEE ALSO'

