# docker-save
# Autogenerated from man page /usr/lib/jvm/default/man/man1/docker-save.1.gz
complete -c docker-save -s h -l help -d '	help for save'
complete -c docker-save -s o -l output -d '	Write to a file, instead of STDOUT SEE ALSO'

