# docker-volume-ls
# Autogenerated from man page /usr/lib/jvm/default/man/man1/docker-volume-ls.1.gz
complete -c docker-volume-ls -l filter -d 'more than one filter,  pass multiple flags (for example,'
complete -c docker-volume-ls -s f -d '	Provide filter values (e. g.  \'dangling=true\')'
complete -c docker-volume-ls -l format -d '	Pretty-print volumes using a Go template'
complete -c docker-volume-ls -s h -l help -d '	help for ls'
complete -c docker-volume-ls -s q -l quiet -d '	Only display volume names SEE ALSO'

