# docker-container-stop
# Autogenerated from man page /usr/lib/jvm/default/man/man1/docker-container-stop.1.gz
complete -c docker-container-stop -s h -l help -d '	help for stop'
complete -c docker-container-stop -s t -l time -d '	Seconds to wait for stop before killing it SEE ALSO'

