# endgame
# Autogenerated from man page /usr/lib/jvm/default/man/man6/endgame.6.gz
complete -c endgame -o window -d 'Draw on a newly-created window.   This is the default'
complete -c endgame -o root -d 'Draw on the root window'
complete -c endgame -o install -d 'Install a private colormap for the window'
complete -c endgame -o shadows -d 'Project pieces against the board with dark blend'
complete -c endgame -o reflections -d 'Reflect pieces in light board squares'
complete -c endgame -o classic -d 'Use the original low-polygon piece models'
complete -c endgame -o visual -d 'Specify which visual to use'
complete -c endgame -o wireframe -d 'Render in wireframe instead of solid'
complete -c endgame -o fps -d 'Display the current frame rate, CPU load, and polygon count'

