# fc
# Autogenerated from man page /usr/lib/jvm/default/man/man1/fc.1p.gz
complete -c fc -o eeditor -d 'Use the editor named by R editor to edit the commands'
complete -c fc -s l -d '(The letter ell. ) List the commands rather than invoking an editor on them'
complete -c fc -s n -d 'Suppress command numbers when listing with  -l '
complete -c fc -s r -d 'Reverse the order of the commands listed (with  -l ) or edited (with neither …'
complete -c fc -s e -d 'Use the editor named by editor to edit the commands'
complete -c fc -s s
complete -c fc -o number -d 'A negative decimal number representing the command that was executed number o…'

