# flipscreen3d
# Autogenerated from man page /usr/lib/jvm/default/man/man6/flipscreen3d.6.gz
complete -c flipscreen3d -o visual -d 'Specify which visual to use'
complete -c flipscreen3d -o window -d 'Draw on a newly-created window.   This is the default'
complete -c flipscreen3d -o root -d 'Draw on the root window'
complete -c flipscreen3d -o delay -d 'Per-frame delay, in microseconds.   Default: 20000 (0. 02 seconds. )'
complete -c flipscreen3d -o rotate -o no-rotate -d 'Whether to rotate'
complete -c flipscreen3d -o wireframe -d 'Just render boxes instead of textures (for debugging)'
complete -c flipscreen3d -o fps -d 'Display the current frame rate, CPU load, and polygon count'

