# fluidballs
# Autogenerated from man page /usr/lib/jvm/default/man/man6/fluidballs.6.gz
complete -c fluidballs -o visual -d 'Specify which visual to use'
complete -c fluidballs -o window -d 'Draw on a newly-created window.   This is the default'
complete -c fluidballs -o root -d 'Draw on the root window'
complete -c fluidballs -o count -d 'How many balls to display.   Default: 300'
complete -c fluidballs -o size -d 'Maximum size of each ball.   Default: 25'
complete -c fluidballs -o gravity -d 'Coefficient of gravity.   Useful values are < 0. 1.   Default: 0. 01'
complete -c fluidballs -o wind -d 'Wind.   Useful values are < 0. 1.   Default: 0. 00'
complete -c fluidballs -o elasticity -d 'Coefficient of elasticity.   Useful values are 0. 2 to 1. 0.   Default: 0. 97'
complete -c fluidballs -o delay -d 'Per-frame delay, in microseconds.   Default: 10000 (0. 01 seconds. )'
complete -c fluidballs -o nonrandom -d 'Make all balls be the same size'
complete -c fluidballs -o no-nonrandom -d 'Make the balls be random sizes.   Default'
complete -c fluidballs -o shake -o no-shake -d 'Whether to shake the box if the system seems to have settled down'
complete -c fluidballs -o fps -d 'Display the current frame rate and CPU load'

