# flyingtoasters
# Autogenerated from man page /usr/lib/jvm/default/man/man6/flyingtoasters.6.gz
complete -c flyingtoasters -o visual -d 'Specify which visual to use'
complete -c flyingtoasters -o window -d 'Draw on a newly-created window.   This is the default'
complete -c flyingtoasters -o root -d 'Draw on the root window'
complete -c flyingtoasters -o delay -d 'Per-frame delay, in microseconds.   Default: 30000 (0. 03 seconds. )'
complete -c flyingtoasters -o speed -d 'How fast the toasters fly.   Larger for faster.   Default: 1. 0'
complete -c flyingtoasters -o ntoasters -d 'How many toasters to draw.   Default 20'
complete -c flyingtoasters -o nslices -d 'How many slices of toast to draw.   Default 25'
complete -c flyingtoasters -o no-texture -d 'Turn off texture mapping (for slow machines. )'
complete -c flyingtoasters -o no-fog -d 'Turn off fog (do not fade out distant toasters. )'
complete -c flyingtoasters -o wireframe -d 'Render in wireframe instead of solid'
complete -c flyingtoasters -o fps -d 'Display the current frame rate, CPU load, and polygon count'

