# gcloud_ai-platform_versions_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_ai-platform_versions_create.1.gz
complete -c gcloud_ai-platform_versions_create -l model
complete -c gcloud_ai-platform_versions_create -l accelerator
complete -c gcloud_ai-platform_versions_create -l async
complete -c gcloud_ai-platform_versions_create -l config
complete -c gcloud_ai-platform_versions_create -l description
complete -c gcloud_ai-platform_versions_create -l framework
complete -c gcloud_ai-platform_versions_create -l labels
complete -c gcloud_ai-platform_versions_create -l machine-type
complete -c gcloud_ai-platform_versions_create -l origin
complete -c gcloud_ai-platform_versions_create -l staging-bucket
complete -c gcloud_ai-platform_versions_create -l python-version
complete -c gcloud_ai-platform_versions_create -l region
complete -c gcloud_ai-platform_versions_create -l runtime-version
complete -c gcloud_ai-platform_versions_create -l master-image-uri -d 'along with the list of supported versions: https://cloud. google'
complete -c gcloud_ai-platform_versions_create -l max-nodes
complete -c gcloud_ai-platform_versions_create -l metric-targets
complete -c gcloud_ai-platform_versions_create -l min-nodes
complete -c gcloud_ai-platform_versions_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_ai-platform_versions_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_ai-platform_versions_create -l trace-token -l user-output-enabled -l verbosity

