# gcloud_beta_compute_sole-tenancy_node-groups_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_compute_sole-tenancy_node-groups_update.1.gz
complete -c gcloud_beta_compute_sole-tenancy_node-groups_update -l node-template
complete -c gcloud_beta_compute_sole-tenancy_node-groups_update -l zone
complete -c gcloud_beta_compute_sole-tenancy_node-groups_update -l add-nodes
complete -c gcloud_beta_compute_sole-tenancy_node-groups_update -l delete-nodes
complete -c gcloud_beta_compute_sole-tenancy_node-groups_update -l autoscaler-mode
complete -c gcloud_beta_compute_sole-tenancy_node-groups_update -l max-nodes
complete -c gcloud_beta_compute_sole-tenancy_node-groups_update -l min-nodes
complete -c gcloud_beta_compute_sole-tenancy_node-groups_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_compute_sole-tenancy_node-groups_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_compute_sole-tenancy_node-groups_update -l trace-token -l user-output-enabled -l verbosity

