# gcloud_spanner_databases_restore
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_spanner_databases_restore.1.gz
complete -c gcloud_spanner_databases_restore -l destination-database
complete -c gcloud_spanner_databases_restore -l destination-instance
complete -c gcloud_spanner_databases_restore -l source-backup
complete -c gcloud_spanner_databases_restore -l source-instance
complete -c gcloud_spanner_databases_restore -l async
complete -c gcloud_spanner_databases_restore -l encryption-type
complete -c gcloud_spanner_databases_restore -l kms-key
complete -c gcloud_spanner_databases_restore -l kms-keyring
complete -c gcloud_spanner_databases_restore -l kms-location
complete -c gcloud_spanner_databases_restore -l kms-project
complete -c gcloud_spanner_databases_restore -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_spanner_databases_restore -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_spanner_databases_restore -l trace-token -l user-output-enabled -l verbosity

