# gcloud_pubsub_subscriptions_seek
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_pubsub_subscriptions_seek.1.gz
complete -c gcloud_pubsub_subscriptions_seek -l snapshot
complete -c gcloud_pubsub_subscriptions_seek -l time
complete -c gcloud_pubsub_subscriptions_seek -l snapshot-project
complete -c gcloud_pubsub_subscriptions_seek -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_pubsub_subscriptions_seek -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_pubsub_subscriptions_seek -l trace-token -l user-output-enabled -l verbosity

