# gcloud_beta_builds_triggers_import
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_builds_triggers_import.1.gz
complete -c gcloud_beta_builds_triggers_import -l source
complete -c gcloud_beta_builds_triggers_import -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_builds_triggers_import -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_builds_triggers_import -l trace-token -l user-output-enabled -l verbosity

