# gcloud_iap_web_set-iam-policy
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_iap_web_set-iam-policy.1.gz
complete -c gcloud_iap_web_set-iam-policy -l resource-type
complete -c gcloud_iap_web_set-iam-policy -l service
complete -c gcloud_iap_web_set-iam-policy -l version
complete -c gcloud_iap_web_set-iam-policy -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_iap_web_set-iam-policy -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_iap_web_set-iam-policy -l trace-token -l user-output-enabled -l verbosity

