# gcloud_alpha_sql_export_bak
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_sql_export_bak.1.gz
complete -c gcloud_alpha_sql_export_bak -l database -s d
complete -c gcloud_alpha_sql_export_bak -l async
complete -c gcloud_alpha_sql_export_bak -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_sql_export_bak -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_sql_export_bak -l trace-token -l user-output-enabled -l verbosity

