# gcloud_beta_data-fusion_instances_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_data-fusion_instances_update.1.gz
complete -c gcloud_beta_data-fusion_instances_update -l location
complete -c gcloud_beta_data-fusion_instances_update -l async
complete -c gcloud_beta_data-fusion_instances_update -l enable_stackdriver_logging
complete -c gcloud_beta_data-fusion_instances_update -l enable_stackdriver_monitoring
complete -c gcloud_beta_data-fusion_instances_update -l labels
complete -c gcloud_beta_data-fusion_instances_update -l version
complete -c gcloud_beta_data-fusion_instances_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_data-fusion_instances_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_data-fusion_instances_update -l trace-token -l user-output-enabled -l verbosity

