# gcloud_beta_data-fusion_instances_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_data-fusion_instances_create.1.gz
complete -c gcloud_beta_data-fusion_instances_create -l location
complete -c gcloud_beta_data-fusion_instances_create -l async
complete -c gcloud_beta_data-fusion_instances_create -l edition
complete -c gcloud_beta_data-fusion_instances_create -l enable_stackdriver_logging
complete -c gcloud_beta_data-fusion_instances_create -l enable_stackdriver_monitoring
complete -c gcloud_beta_data-fusion_instances_create -l labels
complete -c gcloud_beta_data-fusion_instances_create -l options
complete -c gcloud_beta_data-fusion_instances_create -l version
complete -c gcloud_beta_data-fusion_instances_create -l zone
complete -c gcloud_beta_data-fusion_instances_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_data-fusion_instances_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_data-fusion_instances_create -l trace-token -l user-output-enabled -l verbosity

