# gcloud_alpha_logging_sinks_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_logging_sinks_create.1.gz
complete -c gcloud_alpha_logging_sinks_create -l description
complete -c gcloud_alpha_logging_sinks_create -l disabled
complete -c gcloud_alpha_logging_sinks_create -l exclusion
complete -c gcloud_alpha_logging_sinks_create -l include-children
complete -c gcloud_alpha_logging_sinks_create -l log-filter
complete -c gcloud_alpha_logging_sinks_create -l use-partitioned-tables
complete -c gcloud_alpha_logging_sinks_create -l billing-account
complete -c gcloud_alpha_logging_sinks_create -l folder
complete -c gcloud_alpha_logging_sinks_create -l organization
complete -c gcloud_alpha_logging_sinks_create -l project
complete -c gcloud_alpha_logging_sinks_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_logging_sinks_create -l impersonate-service-account -l log-http -l quiet
complete -c gcloud_alpha_logging_sinks_create -l trace-token -l user-output-enabled -l verbosity

