# gcloud_identity_groups_memberships_add
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_identity_groups_memberships_add.1.gz
complete -c gcloud_identity_groups_memberships_add -l group-email
complete -c gcloud_identity_groups_memberships_add -l member-email
complete -c gcloud_identity_groups_memberships_add -l expiration
complete -c gcloud_identity_groups_memberships_add -l roles
complete -c gcloud_identity_groups_memberships_add -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_identity_groups_memberships_add -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_identity_groups_memberships_add -l trace-token -l user-output-enabled -l verbosity

