# gcloud_beta_compute_packet-mirrorings_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_compute_packet-mirrorings_update.1.gz
complete -c gcloud_beta_compute_packet-mirrorings_update -l async
complete -c gcloud_beta_compute_packet-mirrorings_update -l collector-ilb
complete -c gcloud_beta_compute_packet-mirrorings_update -l description
complete -c gcloud_beta_compute_packet-mirrorings_update -l enable
complete -c gcloud_beta_compute_packet-mirrorings_update -l filter-direction
complete -c gcloud_beta_compute_packet-mirrorings_update -l region
complete -c gcloud_beta_compute_packet-mirrorings_update -l add-filter-cidr-ranges
complete -c gcloud_beta_compute_packet-mirrorings_update -l clear-filter-cidr-ranges
complete -c gcloud_beta_compute_packet-mirrorings_update -l remove-filter-cidr-ranges
complete -c gcloud_beta_compute_packet-mirrorings_update -l set-filter-cidr-ranges
complete -c gcloud_beta_compute_packet-mirrorings_update -l add-filter-protocols
complete -c gcloud_beta_compute_packet-mirrorings_update -l clear-filter-protocols
complete -c gcloud_beta_compute_packet-mirrorings_update -l remove-filter-protocols
complete -c gcloud_beta_compute_packet-mirrorings_update -l set-filter-protocols
complete -c gcloud_beta_compute_packet-mirrorings_update -l add-mirrored-instances
complete -c gcloud_beta_compute_packet-mirrorings_update -l clear-mirrored-instances
complete -c gcloud_beta_compute_packet-mirrorings_update -l remove-mirrored-instances
complete -c gcloud_beta_compute_packet-mirrorings_update -l set-mirrored-instances
complete -c gcloud_beta_compute_packet-mirrorings_update -l add-mirrored-subnets
complete -c gcloud_beta_compute_packet-mirrorings_update -l clear-mirrored-subnets
complete -c gcloud_beta_compute_packet-mirrorings_update -l remove-mirrored-subnets
complete -c gcloud_beta_compute_packet-mirrorings_update -l set-mirrored-subnets
complete -c gcloud_beta_compute_packet-mirrorings_update -l add-mirrored-tags
complete -c gcloud_beta_compute_packet-mirrorings_update -l clear-mirrored-tags
complete -c gcloud_beta_compute_packet-mirrorings_update -l remove-mirrored-tags
complete -c gcloud_beta_compute_packet-mirrorings_update -l set-mirrored-tags
complete -c gcloud_beta_compute_packet-mirrorings_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_compute_packet-mirrorings_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_compute_packet-mirrorings_update -l trace-token -l user-output-enabled -l verbosity

