# gcloud_beta_compute_url-maps_validate
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_compute_url-maps_validate.1.gz
complete -c gcloud_beta_compute_url-maps_validate -l source
complete -c gcloud_beta_compute_url-maps_validate -l global
complete -c gcloud_beta_compute_url-maps_validate -l region
complete -c gcloud_beta_compute_url-maps_validate -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_compute_url-maps_validate -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_compute_url-maps_validate -l trace-token -l user-output-enabled -l verbosity

