# gcloud_alpha_iam_workload-identity-pools_providers_create-oidc
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_iam_workload-identity-pools_providers_create-oidc.1.gz
complete -c gcloud_alpha_iam_workload-identity-pools_providers_create-oidc -l location
complete -c gcloud_alpha_iam_workload-identity-pools_providers_create-oidc -l workload-identity-pool
complete -c gcloud_alpha_iam_workload-identity-pools_providers_create-oidc -l attribute-mapping
complete -c gcloud_alpha_iam_workload-identity-pools_providers_create-oidc -l issuer-uri
complete -c gcloud_alpha_iam_workload-identity-pools_providers_create-oidc -l allowed-audiences
complete -c gcloud_alpha_iam_workload-identity-pools_providers_create-oidc -l attribute-condition
complete -c gcloud_alpha_iam_workload-identity-pools_providers_create-oidc -l description
complete -c gcloud_alpha_iam_workload-identity-pools_providers_create-oidc -l disabled
complete -c gcloud_alpha_iam_workload-identity-pools_providers_create-oidc -l display-name
complete -c gcloud_alpha_iam_workload-identity-pools_providers_create-oidc -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_iam_workload-identity-pools_providers_create-oidc -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_iam_workload-identity-pools_providers_create-oidc -l trace-token -l user-output-enabled -l verbosity

