# gcloud_beta_compute_target-ssl-proxies_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_compute_target-ssl-proxies_create.1.gz
complete -c gcloud_beta_compute_target-ssl-proxies_create -l backend-service
complete -c gcloud_beta_compute_target-ssl-proxies_create -l ssl-certificates
complete -c gcloud_beta_compute_target-ssl-proxies_create -l description
complete -c gcloud_beta_compute_target-ssl-proxies_create -l proxy-header
complete -c gcloud_beta_compute_target-ssl-proxies_create -l ssl-policy
complete -c gcloud_beta_compute_target-ssl-proxies_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_compute_target-ssl-proxies_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_compute_target-ssl-proxies_create -l trace-token -l user-output-enabled -l verbosity

