# gcloud_alpha_compute_instances_add-access-config
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_compute_instances_add-access-config.1.gz
complete -c gcloud_alpha_compute_instances_add-access-config -l access-config-name
complete -c gcloud_alpha_compute_instances_add-access-config -l address
complete -c gcloud_alpha_compute_instances_add-access-config -l network-interface
complete -c gcloud_alpha_compute_instances_add-access-config -l network-tier
complete -c gcloud_alpha_compute_instances_add-access-config -l zone
complete -c gcloud_alpha_compute_instances_add-access-config -l public-dns
complete -c gcloud_alpha_compute_instances_add-access-config -l no-public-dns
complete -c gcloud_alpha_compute_instances_add-access-config -l public-ptr
complete -c gcloud_alpha_compute_instances_add-access-config -l no-public-ptr
complete -c gcloud_alpha_compute_instances_add-access-config -l public-ptr-domain
complete -c gcloud_alpha_compute_instances_add-access-config -l no-public-ptr-domain
complete -c gcloud_alpha_compute_instances_add-access-config -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_compute_instances_add-access-config -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_compute_instances_add-access-config -l trace-token -l user-output-enabled -l verbosity

