# gcloud_alpha_services_api-keys_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_services_api-keys_update.1.gz
complete -c gcloud_alpha_services_api-keys_update -l async
complete -c gcloud_alpha_services_api-keys_update -l display-name
complete -c gcloud_alpha_services_api-keys_update -l clear-restrictions
complete -c gcloud_alpha_services_api-keys_update -l api-target
complete -c gcloud_alpha_services_api-keys_update -l flags-file -d 'examples section for how to use --api-target in --flags-file'
complete -c gcloud_alpha_services_api-keys_update -l allowed-application
complete -c gcloud_alpha_services_api-keys_update -l allowed-bundle-ids
complete -c gcloud_alpha_services_api-keys_update -l allowed-ips
complete -c gcloud_alpha_services_api-keys_update -l allowed-referrers
complete -c gcloud_alpha_services_api-keys_update -l configuration -l flatten -l format -l help
complete -c gcloud_alpha_services_api-keys_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_services_api-keys_update -l trace-token -l user-output-enabled -l verbosity

