# gcloud_beta_ml_vision_product-search_products_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_ml_vision_product-search_products_update.1.gz
complete -c gcloud_beta_ml_vision_product-search_products_update -l location
complete -c gcloud_beta_ml_vision_product-search_products_update -l add-product-labels
complete -c gcloud_beta_ml_vision_product-search_products_update -l description
complete -c gcloud_beta_ml_vision_product-search_products_update -l display-name
complete -c gcloud_beta_ml_vision_product-search_products_update -l clear-product-labels
complete -c gcloud_beta_ml_vision_product-search_products_update -l remove-product-labels
complete -c gcloud_beta_ml_vision_product-search_products_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_ml_vision_product-search_products_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_ml_vision_product-search_products_update -l trace-token -l user-output-enabled -l verbosity

