# gcloud_beta_run_services_remove-iam-policy-binding
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_run_services_remove-iam-policy-binding.1.gz
complete -c gcloud_beta_run_services_remove-iam-policy-binding -l member
complete -c gcloud_beta_run_services_remove-iam-policy-binding -l role
complete -c gcloud_beta_run_services_remove-iam-policy-binding -l platform
complete -c gcloud_beta_run_services_remove-iam-policy-binding -l cluster-location -d '[run/cluster_location] properties to specify a cluster in a given zone'
complete -c gcloud_beta_run_services_remove-iam-policy-binding -l all
complete -c gcloud_beta_run_services_remove-iam-policy-binding -l condition
complete -c gcloud_beta_run_services_remove-iam-policy-binding -l condition-from-file
complete -c gcloud_beta_run_services_remove-iam-policy-binding -l region
complete -c gcloud_beta_run_services_remove-iam-policy-binding -l cluster
complete -c gcloud_beta_run_services_remove-iam-policy-binding -l context
complete -c gcloud_beta_run_services_remove-iam-policy-binding -l kubeconfig
complete -c gcloud_beta_run_services_remove-iam-policy-binding -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_run_services_remove-iam-policy-binding -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_run_services_remove-iam-policy-binding -l trace-token -l user-output-enabled -l verbosity

