# gcloud_alpha_container_hub_config-management_version
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_container_hub_config-management_version.1.gz
complete -c gcloud_alpha_container_hub_config-management_version -l filter
complete -c gcloud_alpha_container_hub_config-management_version -l sort-by -l limit
complete -c gcloud_alpha_container_hub_config-management_version -l page-size
complete -c gcloud_alpha_container_hub_config-management_version -l flatten
complete -c gcloud_alpha_container_hub_config-management_version -l uri
complete -c gcloud_alpha_container_hub_config-management_version -l configuration -l flags-file -l format -l help
complete -c gcloud_alpha_container_hub_config-management_version -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_container_hub_config-management_version -l trace-token -l user-output-enabled -l verbosity

