# gcloud_beta_events_triggers_list
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_events_triggers_list.1.gz
complete -c gcloud_beta_events_triggers_list -l platform -d 'Namespace resource - Namespace to list triggers in'
complete -c gcloud_beta_events_triggers_list -l namespace
complete -c gcloud_beta_events_triggers_list -l cluster-location -d '[run/cluster_location] properties to specify a cluster in a given zone'
complete -c gcloud_beta_events_triggers_list -l target-service
complete -c gcloud_beta_events_triggers_list -l cluster
complete -c gcloud_beta_events_triggers_list -l context
complete -c gcloud_beta_events_triggers_list -l kubeconfig
complete -c gcloud_beta_events_triggers_list -l filter
complete -c gcloud_beta_events_triggers_list -l sort-by -l limit
complete -c gcloud_beta_events_triggers_list -l page-size
complete -c gcloud_beta_events_triggers_list -l flatten
complete -c gcloud_beta_events_triggers_list -l uri
complete -c gcloud_beta_events_triggers_list -l configuration -l flags-file -l format -l help
complete -c gcloud_beta_events_triggers_list -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_events_triggers_list -l trace-token -l user-output-enabled -l verbosity

