# gcloud_compute_reservations_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_compute_reservations_update.1.gz
complete -c gcloud_compute_reservations_update -l zone
complete -c gcloud_compute_reservations_update -l vm-count
complete -c gcloud_compute_reservations_update -l async
complete -c gcloud_compute_reservations_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_compute_reservations_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_compute_reservations_update -l trace-token -l user-output-enabled -l verbosity

