# gcloud_beta_dataflow_jobs_export-steps
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_dataflow_jobs_export-steps.1.gz
complete -c gcloud_beta_dataflow_jobs_export-steps -l region
complete -c gcloud_beta_dataflow_jobs_export-steps -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_dataflow_jobs_export-steps -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_dataflow_jobs_export-steps -l trace-token -l user-output-enabled -l verbosity

