# gcloud_beta_asset_search-all-resources
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_asset_search-all-resources.1.gz
complete -c gcloud_beta_asset_search-all-resources -l asset-types
complete -c gcloud_beta_asset_search-all-resources -l order-by
complete -c gcloud_beta_asset_search-all-resources -l query
complete -c gcloud_beta_asset_search-all-resources -l scope
complete -c gcloud_beta_asset_search-all-resources -l filter
complete -c gcloud_beta_asset_search-all-resources -l sort-by -l limit
complete -c gcloud_beta_asset_search-all-resources -l page-size
complete -c gcloud_beta_asset_search-all-resources -l flatten -d 'GCLOUD WIDE FLAGS'
complete -c gcloud_beta_asset_search-all-resources -l configuration -l flags-file -l format -l help
complete -c gcloud_beta_asset_search-all-resources -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_asset_search-all-resources -l trace-token -l user-output-enabled -l verbosity

