# gcloud_beta_ml_vision_product-search_products_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_ml_vision_product-search_products_create.1.gz
complete -c gcloud_beta_ml_vision_product-search_products_create -l location
complete -c gcloud_beta_ml_vision_product-search_products_create -l category
complete -c gcloud_beta_ml_vision_product-search_products_create -l display-name
complete -c gcloud_beta_ml_vision_product-search_products_create -l description
complete -c gcloud_beta_ml_vision_product-search_products_create -l product-labels
complete -c gcloud_beta_ml_vision_product-search_products_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_ml_vision_product-search_products_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_ml_vision_product-search_products_create -l trace-token -l user-output-enabled -l verbosity

