# gcloud_tasks_queues_resume
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_tasks_queues_resume.1.gz
complete -c gcloud_tasks_queues_resume -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_tasks_queues_resume -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_tasks_queues_resume -l trace-token -l user-output-enabled -l verbosity

