# gcloud_workspace-add-ons_deployments_replace
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_workspace-add-ons_deployments_replace.1.gz
complete -c gcloud_workspace-add-ons_deployments_replace -l deployment-file
complete -c gcloud_workspace-add-ons_deployments_replace -l deployment-object
complete -c gcloud_workspace-add-ons_deployments_replace -l etag
complete -c gcloud_workspace-add-ons_deployments_replace -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_workspace-add-ons_deployments_replace -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_workspace-add-ons_deployments_replace -l trace-token -l user-output-enabled -l verbosity

