# gcloud_beta_spanner_instances_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_spanner_instances_create.1.gz
complete -c gcloud_beta_spanner_instances_create -l config
complete -c gcloud_beta_spanner_instances_create -l description
complete -c gcloud_beta_spanner_instances_create -l nodes
complete -c gcloud_beta_spanner_instances_create -l async
complete -c gcloud_beta_spanner_instances_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_spanner_instances_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_spanner_instances_create -l trace-token -l user-output-enabled -l verbosity

