# gcloud_app_instances_scp
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_app_instances_scp.1.gz
complete -c gcloud_app_instances_scp -l compress
complete -c gcloud_app_instances_scp -l recurse
complete -c gcloud_app_instances_scp -l service
complete -c gcloud_app_instances_scp -l version
complete -c gcloud_app_instances_scp -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_app_instances_scp -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_app_instances_scp -l trace-token -l user-output-enabled -l verbosity

