# gcloud_alpha_compute_resource-policies_create_vm-maintenance_maintenance-window
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_compute_resource-policies_create_vm-maintenance_maintenance-window.1.gz
complete -c gcloud_alpha_compute_resource-policies_create_vm-maintenance_maintenance-window -l daily-window
complete -c gcloud_alpha_compute_resource-policies_create_vm-maintenance_maintenance-window -l start-time
complete -c gcloud_alpha_compute_resource-policies_create_vm-maintenance_maintenance-window -l description
complete -c gcloud_alpha_compute_resource-policies_create_vm-maintenance_maintenance-window -l region
complete -c gcloud_alpha_compute_resource-policies_create_vm-maintenance_maintenance-window -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_compute_resource-policies_create_vm-maintenance_maintenance-window -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_compute_resource-policies_create_vm-maintenance_maintenance-window -l trace-token -l user-output-enabled -l verbosity

