# gcloud_alpha_compute_security-policies_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_compute_security-policies_update.1.gz
complete -c gcloud_alpha_compute_security-policies_update -l description
complete -c gcloud_alpha_compute_security-policies_update -l enable-layer7-ddos-defense
complete -c gcloud_alpha_compute_security-policies_update -l enable-ml
complete -c gcloud_alpha_compute_security-policies_update -l json-parsing
complete -c gcloud_alpha_compute_security-policies_update -l layer7-ddos-defense-rule-visibility
complete -c gcloud_alpha_compute_security-policies_update -l log-level
complete -c gcloud_alpha_compute_security-policies_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_compute_security-policies_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_compute_security-policies_update -l trace-token -l user-output-enabled -l verbosity

