# gcloud_alpha_app_ssl-certificates_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_app_ssl-certificates_update.1.gz
complete -c gcloud_alpha_app_ssl-certificates_update -l certificate
complete -c gcloud_alpha_app_ssl-certificates_update -l display-name
complete -c gcloud_alpha_app_ssl-certificates_update -l private-key
complete -c gcloud_alpha_app_ssl-certificates_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_app_ssl-certificates_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_app_ssl-certificates_update -l trace-token -l user-output-enabled -l verbosity

