# gcloud_workflows_run
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_workflows_run.1.gz
complete -c gcloud_workflows_run -l location
complete -c gcloud_workflows_run -l data
complete -c gcloud_workflows_run -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_workflows_run -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_workflows_run -l trace-token -l user-output-enabled -l verbosity

