# gcloud_alpha_compute_instance-groups_unmanaged_set-named-ports
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_compute_instance-groups_unmanaged_set-named-ports.1.gz
complete -c gcloud_alpha_compute_instance-groups_unmanaged_set-named-ports -l named-ports
complete -c gcloud_alpha_compute_instance-groups_unmanaged_set-named-ports -l zone
complete -c gcloud_alpha_compute_instance-groups_unmanaged_set-named-ports -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_compute_instance-groups_unmanaged_set-named-ports -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_compute_instance-groups_unmanaged_set-named-ports -l trace-token -l user-output-enabled -l verbosity

