# gcloud_run_domain-mappings_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_run_domain-mappings_create.1.gz
complete -c gcloud_run_domain-mappings_create -l service
complete -c gcloud_run_domain-mappings_create -l domain
complete -c gcloud_run_domain-mappings_create -l namespace
complete -c gcloud_run_domain-mappings_create -l force-override
complete -c gcloud_run_domain-mappings_create -l platform
complete -c gcloud_run_domain-mappings_create -l cluster-location -d '[run/cluster_location] properties to specify a cluster in a given zone'
complete -c gcloud_run_domain-mappings_create -l cluster
complete -c gcloud_run_domain-mappings_create -l context
complete -c gcloud_run_domain-mappings_create -l kubeconfig
complete -c gcloud_run_domain-mappings_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_run_domain-mappings_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_run_domain-mappings_create -l trace-token -l user-output-enabled -l verbosity

