# gcloud_alpha_ai-platform_jobs_stream-logs
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_ai-platform_jobs_stream-logs.1.gz
complete -c gcloud_alpha_ai-platform_jobs_stream-logs -l allow-multiline-logs
complete -c gcloud_alpha_ai-platform_jobs_stream-logs -l polling-interval
complete -c gcloud_alpha_ai-platform_jobs_stream-logs -l task-name
complete -c gcloud_alpha_ai-platform_jobs_stream-logs -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_ai-platform_jobs_stream-logs -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_ai-platform_jobs_stream-logs -l trace-token -l user-output-enabled -l verbosity

