# gcloud_alpha_healthcare_consent-stores_query-accessible-data
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_healthcare_consent-stores_query-accessible-data.1.gz
complete -c gcloud_alpha_healthcare_consent-stores_query-accessible-data -l dataset
complete -c gcloud_alpha_healthcare_consent-stores_query-accessible-data -l location
complete -c gcloud_alpha_healthcare_consent-stores_query-accessible-data -l gcs-uri
complete -c gcloud_alpha_healthcare_consent-stores_query-accessible-data -l async
complete -c gcloud_alpha_healthcare_consent-stores_query-accessible-data -l request-attributes
complete -c gcloud_alpha_healthcare_consent-stores_query-accessible-data -l resource-attributes
complete -c gcloud_alpha_healthcare_consent-stores_query-accessible-data -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_healthcare_consent-stores_query-accessible-data -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_healthcare_consent-stores_query-accessible-data -l trace-token -l user-output-enabled -l verbosity

