# gcloud_alpha_deploy_targets_export
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_deploy_targets_export.1.gz
complete -c gcloud_alpha_deploy_targets_export -l delivery-pipeline
complete -c gcloud_alpha_deploy_targets_export -l region
complete -c gcloud_alpha_deploy_targets_export -l destination
complete -c gcloud_alpha_deploy_targets_export -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_deploy_targets_export -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_deploy_targets_export -l trace-token -l user-output-enabled -l verbosity

