# gcloud_sql_instances_export
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_sql_instances_export.1.gz
complete -c gcloud_sql_instances_export -l async
complete -c gcloud_sql_instances_export -l database -s d
complete -c gcloud_sql_instances_export -l table -s t
complete -c gcloud_sql_instances_export -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_sql_instances_export -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_sql_instances_export -l trace-token -l user-output-enabled -l verbosity

