# gcloud_dataproc_workflow-templates_add-job_pyspark
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_dataproc_workflow-templates_add-job_pyspark.1.gz
complete -c gcloud_dataproc_workflow-templates_add-job_pyspark -l step-id
complete -c gcloud_dataproc_workflow-templates_add-job_pyspark -l workflow-template
complete -c gcloud_dataproc_workflow-templates_add-job_pyspark -l region
complete -c gcloud_dataproc_workflow-templates_add-job_pyspark -l archives
complete -c gcloud_dataproc_workflow-templates_add-job_pyspark -l driver-log-levels
complete -c gcloud_dataproc_workflow-templates_add-job_pyspark -l files
complete -c gcloud_dataproc_workflow-templates_add-job_pyspark -l jars
complete -c gcloud_dataproc_workflow-templates_add-job_pyspark -l labels
complete -c gcloud_dataproc_workflow-templates_add-job_pyspark -l properties
complete -c gcloud_dataproc_workflow-templates_add-job_pyspark -l py-files
complete -c gcloud_dataproc_workflow-templates_add-job_pyspark -l start-after
complete -c gcloud_dataproc_workflow-templates_add-job_pyspark -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_dataproc_workflow-templates_add-job_pyspark -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_dataproc_workflow-templates_add-job_pyspark -l trace-token -l user-output-enabled -l verbosity

