# gcloud_scc_findings_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_scc_findings_update.1.gz
complete -c gcloud_scc_findings_update -l organization
complete -c gcloud_scc_findings_update -l source
complete -c gcloud_scc_findings_update -l event-time
complete -c gcloud_scc_findings_update -l external-uri
complete -c gcloud_scc_findings_update -l source-properties
complete -c gcloud_scc_findings_update -l state
complete -c gcloud_scc_findings_update -l update-mask
complete -c gcloud_scc_findings_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_scc_findings_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_scc_findings_update -l trace-token -l user-output-enabled -l verbosity

