# gcloud_alpha_compute_resource-policies_create-vm-maintenance
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_compute_resource-policies_create-vm-maintenance.1.gz
complete -c gcloud_alpha_compute_resource-policies_create-vm-maintenance -l daily-window
complete -c gcloud_alpha_compute_resource-policies_create-vm-maintenance -l start-time
complete -c gcloud_alpha_compute_resource-policies_create-vm-maintenance -l description
complete -c gcloud_alpha_compute_resource-policies_create-vm-maintenance -l region
complete -c gcloud_alpha_compute_resource-policies_create-vm-maintenance -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_compute_resource-policies_create-vm-maintenance -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_compute_resource-policies_create-vm-maintenance -l trace-token -l user-output-enabled -l verbosity

