# gcloud_bigtable_backups_delete
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_bigtable_backups_delete.1.gz
complete -c gcloud_bigtable_backups_delete -l cluster
complete -c gcloud_bigtable_backups_delete -l instance
complete -c gcloud_bigtable_backups_delete -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_bigtable_backups_delete -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_bigtable_backups_delete -l trace-token -l user-output-enabled -l verbosity

