# gcloud_beta_datastream_connection-profiles_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_datastream_connection-profiles_create.1.gz
complete -c gcloud_beta_datastream_connection-profiles_create -l location
complete -c gcloud_beta_datastream_connection-profiles_create -l display-name
complete -c gcloud_beta_datastream_connection-profiles_create -l type
complete -c gcloud_beta_datastream_connection-profiles_create -l bucket-name
complete -c gcloud_beta_datastream_connection-profiles_create -l root-path
complete -c gcloud_beta_datastream_connection-profiles_create -l database-service
complete -c gcloud_beta_datastream_connection-profiles_create -l oracle-hostname
complete -c gcloud_beta_datastream_connection-profiles_create -l oracle-port
complete -c gcloud_beta_datastream_connection-profiles_create -l oracle-username
complete -c gcloud_beta_datastream_connection-profiles_create -l oracle-password
complete -c gcloud_beta_datastream_connection-profiles_create -l oracle-prompt-for-password
complete -c gcloud_beta_datastream_connection-profiles_create -l mysql-hostname
complete -c gcloud_beta_datastream_connection-profiles_create -l mysql-port
complete -c gcloud_beta_datastream_connection-profiles_create -l mysql-username
complete -c gcloud_beta_datastream_connection-profiles_create -l mysql-password
complete -c gcloud_beta_datastream_connection-profiles_create -l mysql-prompt-for-password
complete -c gcloud_beta_datastream_connection-profiles_create -l ca-certificate
complete -c gcloud_beta_datastream_connection-profiles_create -l client-certificate
complete -c gcloud_beta_datastream_connection-profiles_create -l client-key
complete -c gcloud_beta_datastream_connection-profiles_create -l labels
complete -c gcloud_beta_datastream_connection-profiles_create -l private-connection-name
complete -c gcloud_beta_datastream_connection-profiles_create -l no-connectivity
complete -c gcloud_beta_datastream_connection-profiles_create -l static-ip-connectivity
complete -c gcloud_beta_datastream_connection-profiles_create -l forward-ssh-hostname
complete -c gcloud_beta_datastream_connection-profiles_create -l forward-ssh-username
complete -c gcloud_beta_datastream_connection-profiles_create -l forward-ssh-port
complete -c gcloud_beta_datastream_connection-profiles_create -l forward-ssh-password
complete -c gcloud_beta_datastream_connection-profiles_create -l forward-ssh-private-key
complete -c gcloud_beta_datastream_connection-profiles_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_datastream_connection-profiles_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_datastream_connection-profiles_create -l trace-token -l user-output-enabled -l verbosity

