# gcloud_recommender_recommendations_mark-succeeded
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_recommender_recommendations_mark-succeeded.1.gz
complete -c gcloud_recommender_recommendations_mark-succeeded -l etag
complete -c gcloud_recommender_recommendations_mark-succeeded -l location
complete -c gcloud_recommender_recommendations_mark-succeeded -l recommender
complete -c gcloud_recommender_recommendations_mark-succeeded -l organization
complete -c gcloud_recommender_recommendations_mark-succeeded -l billing-account
complete -c gcloud_recommender_recommendations_mark-succeeded -l folder
complete -c gcloud_recommender_recommendations_mark-succeeded -l project
complete -c gcloud_recommender_recommendations_mark-succeeded -l state-metadata
complete -c gcloud_recommender_recommendations_mark-succeeded -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_recommender_recommendations_mark-succeeded -l impersonate-service-account -l log-http -l quiet
complete -c gcloud_recommender_recommendations_mark-succeeded -l trace-token -l user-output-enabled -l verbosity

