# gcloud_alpha_compute_interconnects_attachments_dedicated_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_compute_interconnects_attachments_dedicated_update.1.gz
complete -c gcloud_alpha_compute_interconnects_attachments_dedicated_update -l bandwidth
complete -c gcloud_alpha_compute_interconnects_attachments_dedicated_update -l candidate-ipv6-subnets
complete -c gcloud_alpha_compute_interconnects_attachments_dedicated_update -l cloud-router-ipv6-interface-id
complete -c gcloud_alpha_compute_interconnects_attachments_dedicated_update -l customer-router-ipv6-interface-id
complete -c gcloud_alpha_compute_interconnects_attachments_dedicated_update -l description
complete -c gcloud_alpha_compute_interconnects_attachments_dedicated_update -l enable-admin
complete -c gcloud_alpha_compute_interconnects_attachments_dedicated_update -l mtu
complete -c gcloud_alpha_compute_interconnects_attachments_dedicated_update -l region
complete -c gcloud_alpha_compute_interconnects_attachments_dedicated_update -l stack-type
complete -c gcloud_alpha_compute_interconnects_attachments_dedicated_update -l update-labels
complete -c gcloud_alpha_compute_interconnects_attachments_dedicated_update -l clear-labels
complete -c gcloud_alpha_compute_interconnects_attachments_dedicated_update -l remove-labels
complete -c gcloud_alpha_compute_interconnects_attachments_dedicated_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_compute_interconnects_attachments_dedicated_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_compute_interconnects_attachments_dedicated_update -l trace-token -l user-output-enabled -l verbosity

