# gcloud_alpha_network-services_routers_import
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_network-services_routers_import.1.gz
complete -c gcloud_alpha_network-services_routers_import -l location
complete -c gcloud_alpha_network-services_routers_import -l async
complete -c gcloud_alpha_network-services_routers_import -l source
complete -c gcloud_alpha_network-services_routers_import -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_network-services_routers_import -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_network-services_routers_import -l trace-token -l user-output-enabled -l verbosity

