# gcloud_alpha_compute_images_packages_diff
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_compute_images_packages_diff.1.gz
complete -c gcloud_alpha_compute_images_packages_diff -l base-image
complete -c gcloud_alpha_compute_images_packages_diff -l base-project
complete -c gcloud_alpha_compute_images_packages_diff -l diff-image
complete -c gcloud_alpha_compute_images_packages_diff -l diff-project
complete -c gcloud_alpha_compute_images_packages_diff -l show-added-packages
complete -c gcloud_alpha_compute_images_packages_diff -l show-removed-packages
complete -c gcloud_alpha_compute_images_packages_diff -l show-updated-packages
complete -c gcloud_alpha_compute_images_packages_diff -l filter
complete -c gcloud_alpha_compute_images_packages_diff -l sort-by -l limit
complete -c gcloud_alpha_compute_images_packages_diff -l page-size
complete -c gcloud_alpha_compute_images_packages_diff -l flatten
complete -c gcloud_alpha_compute_images_packages_diff -l uri
complete -c gcloud_alpha_compute_images_packages_diff -l configuration -l flags-file -l format -l help
complete -c gcloud_alpha_compute_images_packages_diff -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_compute_images_packages_diff -l trace-token -l user-output-enabled -l verbosity

