# gcloud_beta_assured_workloads_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_assured_workloads_create.1.gz
complete -c gcloud_beta_assured_workloads_create -l billing-account
complete -c gcloud_beta_assured_workloads_create -l compliance-regime
complete -c gcloud_beta_assured_workloads_create -l display-name
complete -c gcloud_beta_assured_workloads_create -l location
complete -c gcloud_beta_assured_workloads_create -l organization
complete -c gcloud_beta_assured_workloads_create -l external-identifier
complete -c gcloud_beta_assured_workloads_create -l labels
complete -c gcloud_beta_assured_workloads_create -l next-rotation-time
complete -c gcloud_beta_assured_workloads_create -l provisioned-resources-parent
complete -c gcloud_beta_assured_workloads_create -l resource-settings
complete -c gcloud_beta_assured_workloads_create -l rotation-period
complete -c gcloud_beta_assured_workloads_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_assured_workloads_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_assured_workloads_create -l trace-token -l user-output-enabled -l verbosity

