# gcloud_alpha_lifesciences_pipelines_run
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_lifesciences_pipelines_run.1.gz
complete -c gcloud_alpha_lifesciences_pipelines_run -l command-line
complete -c gcloud_alpha_lifesciences_pipelines_run -l pipeline-file
complete -c gcloud_alpha_lifesciences_pipelines_run -l disk-size
complete -c gcloud_alpha_lifesciences_pipelines_run -l docker-image
complete -c gcloud_alpha_lifesciences_pipelines_run -l env-vars
complete -c gcloud_alpha_lifesciences_pipelines_run -l inputs
complete -c gcloud_alpha_lifesciences_pipelines_run -l inputs-from-file
complete -c gcloud_alpha_lifesciences_pipelines_run -l logging
complete -c gcloud_alpha_lifesciences_pipelines_run -o 'stdout.log' -o 'stderr.log'
complete -c gcloud_alpha_lifesciences_pipelines_run -l outputs
complete -c gcloud_alpha_lifesciences_pipelines_run -l preemptible
complete -c gcloud_alpha_lifesciences_pipelines_run -l boot-disk-size
complete -c gcloud_alpha_lifesciences_pipelines_run -l labels
complete -c gcloud_alpha_lifesciences_pipelines_run -l location
complete -c gcloud_alpha_lifesciences_pipelines_run -l machine-type
complete -c gcloud_alpha_lifesciences_pipelines_run -l network
complete -c gcloud_alpha_lifesciences_pipelines_run -l regions
complete -c gcloud_alpha_lifesciences_pipelines_run -l service-account-email
complete -c gcloud_alpha_lifesciences_pipelines_run -l service-account-scopes
complete -c gcloud_alpha_lifesciences_pipelines_run -l subnetwork
complete -c gcloud_alpha_lifesciences_pipelines_run -l zones
complete -c gcloud_alpha_lifesciences_pipelines_run -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_lifesciences_pipelines_run -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_lifesciences_pipelines_run -l trace-token -l user-output-enabled -l verbosity

