# gcloud_alpha_dlp_datasources_bigquery_inspect
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_dlp_datasources_bigquery_inspect.1.gz
complete -c gcloud_alpha_dlp_datasources_bigquery_inspect -l exclude-info-types
complete -c gcloud_alpha_dlp_datasources_bigquery_inspect -l identifying-fields
complete -c gcloud_alpha_dlp_datasources_bigquery_inspect -l include-quote
complete -c gcloud_alpha_dlp_datasources_bigquery_inspect -l info-types
complete -c gcloud_alpha_dlp_datasources_bigquery_inspect -l job-id
complete -c gcloud_alpha_dlp_datasources_bigquery_inspect -l max-findings
complete -c gcloud_alpha_dlp_datasources_bigquery_inspect -l max-findings-per-item
complete -c gcloud_alpha_dlp_datasources_bigquery_inspect -l max-time
complete -c gcloud_alpha_dlp_datasources_bigquery_inspect -l min-likelihood
complete -c gcloud_alpha_dlp_datasources_bigquery_inspect -l min-time
complete -c gcloud_alpha_dlp_datasources_bigquery_inspect -l output-table
complete -c gcloud_alpha_dlp_datasources_bigquery_inspect -l output-topics
complete -c gcloud_alpha_dlp_datasources_bigquery_inspect -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_dlp_datasources_bigquery_inspect -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_dlp_datasources_bigquery_inspect -l trace-token -l user-output-enabled -l verbosity

