# gcloud_beta_ml_language_analyze-syntax
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_ml_language_analyze-syntax.1.gz
complete -c gcloud_beta_ml_language_analyze-syntax -l content
complete -c gcloud_beta_ml_language_analyze-syntax -l content-file
complete -c gcloud_beta_ml_language_analyze-syntax -l content-type
complete -c gcloud_beta_ml_language_analyze-syntax -l encoding-type
complete -c gcloud_beta_ml_language_analyze-syntax -l language
complete -c gcloud_beta_ml_language_analyze-syntax -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_ml_language_analyze-syntax -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_ml_language_analyze-syntax -l trace-token -l user-output-enabled -l verbosity

