# gcloud_beta_container_operations_cancel
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_container_operations_cancel.1.gz
complete -c gcloud_beta_container_operations_cancel -l region
complete -c gcloud_beta_container_operations_cancel -l zone -s z
complete -c gcloud_beta_container_operations_cancel -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_container_operations_cancel -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_container_operations_cancel -l trace-token -l user-output-enabled -l verbosity

