# gcloud_beta_events_namespaces_init
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_events_namespaces_init.1.gz
complete -c gcloud_beta_events_namespaces_init -l authentication
complete -c gcloud_beta_events_namespaces_init -l copy-default-secret
complete -c gcloud_beta_events_namespaces_init -l platform
complete -c gcloud_beta_events_namespaces_init -l cluster-location -d '[run/cluster_location] properties to specify a cluster in a given zone'
complete -c gcloud_beta_events_namespaces_init -l cluster
complete -c gcloud_beta_events_namespaces_init -l context
complete -c gcloud_beta_events_namespaces_init -l kubeconfig
complete -c gcloud_beta_events_namespaces_init -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_events_namespaces_init -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_events_namespaces_init -l trace-token -l user-output-enabled -l verbosity

