# gcloud_alpha_compute_target-pools_get-health
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_compute_target-pools_get-health.1.gz
complete -c gcloud_alpha_compute_target-pools_get-health -l region
complete -c gcloud_alpha_compute_target-pools_get-health -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_compute_target-pools_get-health -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_compute_target-pools_get-health -l trace-token -l user-output-enabled -l verbosity

