# gcloud_compute_instances_stop
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_compute_instances_stop.1.gz
complete -c gcloud_compute_instances_stop -l async
complete -c gcloud_compute_instances_stop -l zone
complete -c gcloud_compute_instances_stop -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_compute_instances_stop -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_compute_instances_stop -l trace-token -l user-output-enabled -l verbosity

