# gcloud_alpha_scc_notifications_delete
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_scc_notifications_delete.1.gz
complete -c gcloud_alpha_scc_notifications_delete -l organization
complete -c gcloud_alpha_scc_notifications_delete -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_scc_notifications_delete -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_scc_notifications_delete -l trace-token -l user-output-enabled -l verbosity

