# gcloud_alpha_compute_target-pools_set-backup
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_compute_target-pools_set-backup.1.gz
complete -c gcloud_alpha_compute_target-pools_set-backup -l backup-pool
complete -c gcloud_alpha_compute_target-pools_set-backup -l no-backup-pool
complete -c gcloud_alpha_compute_target-pools_set-backup -l failover-ratio
complete -c gcloud_alpha_compute_target-pools_set-backup -l region
complete -c gcloud_alpha_compute_target-pools_set-backup -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_compute_target-pools_set-backup -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_compute_target-pools_set-backup -l trace-token -l user-output-enabled -l verbosity

