# gcloud_alpha_compute_instances_set-scopes
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_compute_instances_set-scopes.1.gz
complete -c gcloud_alpha_compute_instances_set-scopes -l zone
complete -c gcloud_alpha_compute_instances_set-scopes -l scopes
complete -c gcloud_alpha_compute_instances_set-scopes -l no-scopes
complete -c gcloud_alpha_compute_instances_set-scopes -l service-account
complete -c gcloud_alpha_compute_instances_set-scopes -l no-service-account
complete -c gcloud_alpha_compute_instances_set-scopes -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_compute_instances_set-scopes -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_compute_instances_set-scopes -l trace-token -l user-output-enabled -l verbosity

