# gcloud_alpha_deployment-manager_manifests_list
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_deployment-manager_manifests_list.1.gz
complete -c gcloud_alpha_deployment-manager_manifests_list -l deployment
complete -c gcloud_alpha_deployment-manager_manifests_list -l simple-list
complete -c gcloud_alpha_deployment-manager_manifests_list -l format -d 'LIST COMMAND FLAGS'
complete -c gcloud_alpha_deployment-manager_manifests_list -l filter
complete -c gcloud_alpha_deployment-manager_manifests_list -l sort-by -l limit
complete -c gcloud_alpha_deployment-manager_manifests_list -l page-size
complete -c gcloud_alpha_deployment-manager_manifests_list -l flatten
complete -c gcloud_alpha_deployment-manager_manifests_list -l uri
complete -c gcloud_alpha_deployment-manager_manifests_list -l configuration -l flags-file -l help
complete -c gcloud_alpha_deployment-manager_manifests_list -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_deployment-manager_manifests_list -l trace-token -l user-output-enabled -l verbosity

