# gcloud_alpha_pubsub_schemas_validate-schema
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_pubsub_schemas_validate-schema.1.gz
complete -c gcloud_alpha_pubsub_schemas_validate-schema -l type
complete -c gcloud_alpha_pubsub_schemas_validate-schema -l definition
complete -c gcloud_alpha_pubsub_schemas_validate-schema -l definition-file
complete -c gcloud_alpha_pubsub_schemas_validate-schema -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_pubsub_schemas_validate-schema -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_pubsub_schemas_validate-schema -l trace-token -l user-output-enabled -l verbosity

