# gcloud_compute_images_describe-from-family
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_compute_images_describe-from-family.1.gz
complete -c gcloud_compute_images_describe-from-family -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_compute_images_describe-from-family -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_compute_images_describe-from-family -l trace-token -l user-output-enabled -l verbosity

