# gcloud_alpha_pubsub_subscriptions_modify-ack-deadline
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_pubsub_subscriptions_modify-ack-deadline.1.gz
complete -c gcloud_alpha_pubsub_subscriptions_modify-ack-deadline -l ack-deadline
complete -c gcloud_alpha_pubsub_subscriptions_modify-ack-deadline -l ack-ids
complete -c gcloud_alpha_pubsub_subscriptions_modify-ack-deadline -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_pubsub_subscriptions_modify-ack-deadline -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_pubsub_subscriptions_modify-ack-deadline -l trace-token -l user-output-enabled -l verbosity

