# gcloud_beta_data-catalog_tag-templates_fields_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_data-catalog_tag-templates_fields_create.1.gz
complete -c gcloud_beta_data-catalog_tag-templates_fields_create -l location
complete -c gcloud_beta_data-catalog_tag-templates_fields_create -l tag-template
complete -c gcloud_beta_data-catalog_tag-templates_fields_create -l type
complete -c gcloud_beta_data-catalog_tag-templates_fields_create -l display-name
complete -c gcloud_beta_data-catalog_tag-templates_fields_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_data-catalog_tag-templates_fields_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_data-catalog_tag-templates_fields_create -l trace-token -l user-output-enabled -l verbosity

