# gcloud_kms_import-jobs_describe
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_kms_import-jobs_describe.1.gz
complete -c gcloud_kms_import-jobs_describe -l attestation-file -d '$ gcloud kms import-jobs describe strider --keyring=fellowship \\     --locati…'
complete -c gcloud_kms_import-jobs_describe -l keyring
complete -c gcloud_kms_import-jobs_describe -l location
complete -c gcloud_kms_import-jobs_describe -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_kms_import-jobs_describe -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_kms_import-jobs_describe -l trace-token -l user-output-enabled -l verbosity

