# gcloud_compute_interconnects_attachments_partner_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_compute_interconnects_attachments_partner_update.1.gz
complete -c gcloud_compute_interconnects_attachments_partner_update -l description
complete -c gcloud_compute_interconnects_attachments_partner_update -l enable-admin
complete -c gcloud_compute_interconnects_attachments_partner_update -l mtu
complete -c gcloud_compute_interconnects_attachments_partner_update -l region
complete -c gcloud_compute_interconnects_attachments_partner_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_compute_interconnects_attachments_partner_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_compute_interconnects_attachments_partner_update -l trace-token -l user-output-enabled -l verbosity

