# gcloud_beta_compute_instances_ops-agents_policies_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_compute_instances_ops-agents_policies_update.1.gz
complete -c gcloud_beta_compute_instances_ops-agents_policies_update -l agents
complete -c gcloud_beta_compute_instances_ops-agents_policies_update -l instances -l zones -d 'following flags as documented below: --clear-group-labels,'
complete -c gcloud_beta_compute_instances_ops-agents_policies_update -l clear-instances -l clear-zones -d EXAMPLES
complete -c gcloud_beta_compute_instances_ops-agents_policies_update -l agent-rules
complete -c gcloud_beta_compute_instances_ops-agents_policies_update -l description
complete -c gcloud_beta_compute_instances_ops-agents_policies_update -l etag
complete -c gcloud_beta_compute_instances_ops-agents_policies_update -l os-types
complete -c gcloud_beta_compute_instances_ops-agents_policies_update -l clear-group-labels
complete -c gcloud_beta_compute_instances_ops-agents_policies_update -l group-labels -d to
complete -c gcloud_beta_compute_instances_ops-agents_policies_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_compute_instances_ops-agents_policies_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_compute_instances_ops-agents_policies_update -l trace-token -l user-output-enabled -l verbosity

