# gcloud_anthos_auth_login
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_anthos_auth_login.1.gz
complete -c gcloud_anthos_auth_login -l cluster
complete -c gcloud_anthos_auth_login -l dry-run
complete -c gcloud_anthos_auth_login -l kubeconfig
complete -c gcloud_anthos_auth_login -l login-config
complete -c gcloud_anthos_auth_login -l login-config-cert
complete -c gcloud_anthos_auth_login -l set-preferred-auth
complete -c gcloud_anthos_auth_login -l user
complete -c gcloud_anthos_auth_login -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_anthos_auth_login -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_anthos_auth_login -l trace-token -l user-output-enabled -l verbosity

