# gcloud_monitoring_dashboards_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_monitoring_dashboards_update.1.gz
complete -c gcloud_monitoring_dashboards_update -l config
complete -c gcloud_monitoring_dashboards_update -l config-from-file
complete -c gcloud_monitoring_dashboards_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_monitoring_dashboards_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_monitoring_dashboards_update -l trace-token -l user-output-enabled -l verbosity

