# gcloud_spanner_instance-configs_describe
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_spanner_instance-configs_describe.1.gz
complete -c gcloud_spanner_instance-configs_describe -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_spanner_instance-configs_describe -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_spanner_instance-configs_describe -l trace-token -l user-output-enabled -l verbosity

