# gcloud_alpha_scc_findings_list-marks
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_scc_findings_list-marks.1.gz
complete -c gcloud_alpha_scc_findings_list-marks -l organization
complete -c gcloud_alpha_scc_findings_list-marks -l source
complete -c gcloud_alpha_scc_findings_list-marks -l page-token
complete -c gcloud_alpha_scc_findings_list-marks -l read-time
complete -c gcloud_alpha_scc_findings_list-marks -l filter
complete -c gcloud_alpha_scc_findings_list-marks -l sort-by -l limit
complete -c gcloud_alpha_scc_findings_list-marks -l page-size
complete -c gcloud_alpha_scc_findings_list-marks -l flatten -d 'GCLOUD WIDE FLAGS'
complete -c gcloud_alpha_scc_findings_list-marks -l configuration -l flags-file -l format -l help
complete -c gcloud_alpha_scc_findings_list-marks -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_scc_findings_list-marks -l trace-token -l user-output-enabled -l verbosity

