# gcloud_beta_events_triggers_delete
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_events_triggers_delete.1.gz
complete -c gcloud_beta_events_triggers_delete -l namespace
complete -c gcloud_beta_events_triggers_delete -l platform
complete -c gcloud_beta_events_triggers_delete -l cluster-location -d '[run/cluster_location] properties to specify a cluster in a given zone'
complete -c gcloud_beta_events_triggers_delete -l cluster
complete -c gcloud_beta_events_triggers_delete -l context
complete -c gcloud_beta_events_triggers_delete -l kubeconfig
complete -c gcloud_beta_events_triggers_delete -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_events_triggers_delete -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_events_triggers_delete -l trace-token -l user-output-enabled -l verbosity

