# gcloud_alpha_redis_instances_reschedule-maintenance
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_redis_instances_reschedule-maintenance.1.gz
complete -c gcloud_alpha_redis_instances_reschedule-maintenance -l region
complete -c gcloud_alpha_redis_instances_reschedule-maintenance -l reschedule-type
complete -c gcloud_alpha_redis_instances_reschedule-maintenance -l async
complete -c gcloud_alpha_redis_instances_reschedule-maintenance -l schedule-time
complete -c gcloud_alpha_redis_instances_reschedule-maintenance -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_redis_instances_reschedule-maintenance -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_redis_instances_reschedule-maintenance -l trace-token -l user-output-enabled -l verbosity

