# gcloud_service-directory_services_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_service-directory_services_create.1.gz
complete -c gcloud_service-directory_services_create -l location
complete -c gcloud_service-directory_services_create -l namespace
complete -c gcloud_service-directory_services_create -l annotations
complete -c gcloud_service-directory_services_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_service-directory_services_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_service-directory_services_create -l trace-token -l user-output-enabled -l verbosity

