# gcloud_alpha_scc_settings_describe-explicit
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_scc_settings_describe-explicit.1.gz
complete -c gcloud_alpha_scc_settings_describe-explicit -l organization
complete -c gcloud_alpha_scc_settings_describe-explicit -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_scc_settings_describe-explicit -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_scc_settings_describe-explicit -l trace-token -l user-output-enabled -l verbosity

