# gcloud_alpha_builds_triggers_create_bitbucketserver
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_builds_triggers_create_bitbucketserver.1.gz
complete -c gcloud_alpha_builds_triggers_create_bitbucketserver -l trigger-config
complete -c gcloud_alpha_builds_triggers_create_bitbucketserver -l bitbucket-server-config-resource
complete -c gcloud_alpha_builds_triggers_create_bitbucketserver -l project-key
complete -c gcloud_alpha_builds_triggers_create_bitbucketserver -l repo-slug
complete -c gcloud_alpha_builds_triggers_create_bitbucketserver -l description
complete -c gcloud_alpha_builds_triggers_create_bitbucketserver -l ignored-files
complete -c gcloud_alpha_builds_triggers_create_bitbucketserver -l included-files
complete -c gcloud_alpha_builds_triggers_create_bitbucketserver -l name
complete -c gcloud_alpha_builds_triggers_create_bitbucketserver -l substitutions
complete -c gcloud_alpha_builds_triggers_create_bitbucketserver -l branch-pattern
complete -c gcloud_alpha_builds_triggers_create_bitbucketserver -l tag-pattern
complete -c gcloud_alpha_builds_triggers_create_bitbucketserver -l pull-request-pattern
complete -c gcloud_alpha_builds_triggers_create_bitbucketserver -l comment-control
complete -c gcloud_alpha_builds_triggers_create_bitbucketserver -l build-config
complete -c gcloud_alpha_builds_triggers_create_bitbucketserver -l inline-config
complete -c gcloud_alpha_builds_triggers_create_bitbucketserver -l dockerfile
complete -c gcloud_alpha_builds_triggers_create_bitbucketserver -l dockerfile-dir
complete -c gcloud_alpha_builds_triggers_create_bitbucketserver -l dockerfile-image
complete -c gcloud_alpha_builds_triggers_create_bitbucketserver -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_builds_triggers_create_bitbucketserver -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_builds_triggers_create_bitbucketserver -l trace-token -l user-output-enabled -l verbosity

