# gcloud_beta_artifacts_tags_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_artifacts_tags_create.1.gz
complete -c gcloud_beta_artifacts_tags_create -l location
complete -c gcloud_beta_artifacts_tags_create -l package
complete -c gcloud_beta_artifacts_tags_create -l repository
complete -c gcloud_beta_artifacts_tags_create -l version
complete -c gcloud_beta_artifacts_tags_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_artifacts_tags_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_artifacts_tags_create -l trace-token -l user-output-enabled -l verbosity

