# gcloud_alpha_deploy_rollouts_approve
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_deploy_rollouts_approve.1.gz
complete -c gcloud_alpha_deploy_rollouts_approve -l delivery-pipeline
complete -c gcloud_alpha_deploy_rollouts_approve -l region
complete -c gcloud_alpha_deploy_rollouts_approve -l release
complete -c gcloud_alpha_deploy_rollouts_approve -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_deploy_rollouts_approve -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_deploy_rollouts_approve -l trace-token -l user-output-enabled -l verbosity

