# gcloud_alpha_resource-config_list-resources
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_resource-config_list-resources.1.gz
complete -c gcloud_alpha_resource-config_list-resources -l output-format
complete -c gcloud_alpha_resource-config_list-resources -l folder
complete -c gcloud_alpha_resource-config_list-resources -l organization
complete -c gcloud_alpha_resource-config_list-resources -l project
complete -c gcloud_alpha_resource-config_list-resources -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_resource-config_list-resources -l impersonate-service-account -l log-http -l quiet
complete -c gcloud_alpha_resource-config_list-resources -l trace-token -l user-output-enabled -l verbosity

