# gcloud_beta_app_versions_stop
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_app_versions_stop.1.gz
complete -c gcloud_beta_app_versions_stop -l service -s s
complete -c gcloud_beta_app_versions_stop -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_app_versions_stop -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_app_versions_stop -l trace-token -l user-output-enabled -l verbosity

