# gcloud_dataproc_jobs_kill
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_dataproc_jobs_kill.1.gz
complete -c gcloud_dataproc_jobs_kill -l region
complete -c gcloud_dataproc_jobs_kill -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_dataproc_jobs_kill -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_dataproc_jobs_kill -l trace-token -l user-output-enabled -l verbosity

