# gcloud_app_services_set-traffic
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_app_services_set-traffic.1.gz
complete -c gcloud_app_services_set-traffic -l splits
complete -c gcloud_app_services_set-traffic -l migrate
complete -c gcloud_app_services_set-traffic -l split-by
complete -c gcloud_app_services_set-traffic -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_app_services_set-traffic -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_app_services_set-traffic -l trace-token -l user-output-enabled -l verbosity

