# gcloud_alpha_data-catalog_tag-templates_fields_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_data-catalog_tag-templates_fields_update.1.gz
complete -c gcloud_alpha_data-catalog_tag-templates_fields_update -l location
complete -c gcloud_alpha_data-catalog_tag-templates_fields_update -l tag-template
complete -c gcloud_alpha_data-catalog_tag-templates_fields_update -l display-name
complete -c gcloud_alpha_data-catalog_tag-templates_fields_update -l enum-values
complete -c gcloud_alpha_data-catalog_tag-templates_fields_update -l required
complete -c gcloud_alpha_data-catalog_tag-templates_fields_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_data-catalog_tag-templates_fields_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_data-catalog_tag-templates_fields_update -l trace-token -l user-output-enabled -l verbosity

