# gcloud_beta_resource-manager_org-policies_allow
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_resource-manager_org-policies_allow.1.gz
complete -c gcloud_beta_resource-manager_org-policies_allow -l folder
complete -c gcloud_beta_resource-manager_org-policies_allow -l organization
complete -c gcloud_beta_resource-manager_org-policies_allow -l project
complete -c gcloud_beta_resource-manager_org-policies_allow -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_resource-manager_org-policies_allow -l impersonate-service-account -l log-http -l quiet
complete -c gcloud_beta_resource-manager_org-policies_allow -l trace-token -l user-output-enabled -l verbosity

