# gcloud_alpha_dlp_images_inspect
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_dlp_images_inspect.1.gz
complete -c gcloud_alpha_dlp_images_inspect -l exclude-info-types
complete -c gcloud_alpha_dlp_images_inspect -l include-quote
complete -c gcloud_alpha_dlp_images_inspect -l info-types
complete -c gcloud_alpha_dlp_images_inspect -l max-findings
complete -c gcloud_alpha_dlp_images_inspect -l min-likelihood
complete -c gcloud_alpha_dlp_images_inspect -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_dlp_images_inspect -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_dlp_images_inspect -l trace-token -l user-output-enabled -l verbosity

