# gcloud_beta_metastore_services_imports_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_metastore_services_imports_create.1.gz
complete -c gcloud_beta_metastore_services_imports_create -l location
complete -c gcloud_beta_metastore_services_imports_create -l service
complete -c gcloud_beta_metastore_services_imports_create -l database-dump
complete -c gcloud_beta_metastore_services_imports_create -l async
complete -c gcloud_beta_metastore_services_imports_create -l database-dump-type
complete -c gcloud_beta_metastore_services_imports_create -l database-type
complete -c gcloud_beta_metastore_services_imports_create -l description
complete -c gcloud_beta_metastore_services_imports_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_metastore_services_imports_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_metastore_services_imports_create -l trace-token -l user-output-enabled -l verbosity

