# gcloud_service-directory_locations_list
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_service-directory_locations_list.1.gz
complete -c gcloud_service-directory_locations_list -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_service-directory_locations_list -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_service-directory_locations_list -l trace-token -l user-output-enabled -l verbosity

