# gcloud_alpha_active-directory_domains_describe-ldaps-settings
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_active-directory_domains_describe-ldaps-settings.1.gz
complete -c gcloud_alpha_active-directory_domains_describe-ldaps-settings -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_active-directory_domains_describe-ldaps-settings -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_active-directory_domains_describe-ldaps-settings -l trace-token -l user-output-enabled -l verbosity

