# gcloud_compute_instance-groups_managed_wait-until
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_compute_instance-groups_managed_wait-until.1.gz
complete -c gcloud_compute_instance-groups_managed_wait-until -l stable
complete -c gcloud_compute_instance-groups_managed_wait-until -l version-target-reached
complete -c gcloud_compute_instance-groups_managed_wait-until -l timeout
complete -c gcloud_compute_instance-groups_managed_wait-until -l region
complete -c gcloud_compute_instance-groups_managed_wait-until -l zone
complete -c gcloud_compute_instance-groups_managed_wait-until -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_compute_instance-groups_managed_wait-until -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_compute_instance-groups_managed_wait-until -l trace-token -l user-output-enabled -l verbosity

