# gcloud_alpha_trace_sinks_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_trace_sinks_update.1.gz
complete -c gcloud_alpha_trace_sinks_update -l project
complete -c gcloud_alpha_trace_sinks_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_trace_sinks_update -l impersonate-service-account -l log-http -l quiet
complete -c gcloud_alpha_trace_sinks_update -l trace-token -l user-output-enabled -l verbosity

