# gcloud_beta_ml_translate_get-supported-languages
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_ml_translate_get-supported-languages.1.gz
complete -c gcloud_beta_ml_translate_get-supported-languages -l display-language-code
complete -c gcloud_beta_ml_translate_get-supported-languages -l model
complete -c gcloud_beta_ml_translate_get-supported-languages -l zone
complete -c gcloud_beta_ml_translate_get-supported-languages -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_ml_translate_get-supported-languages -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_ml_translate_get-supported-languages -l trace-token -l user-output-enabled -l verbosity

