# gcloud_beta_compute_instances_add-labels
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_compute_instances_add-labels.1.gz
complete -c gcloud_beta_compute_instances_add-labels -l labels
complete -c gcloud_beta_compute_instances_add-labels -l zone
complete -c gcloud_beta_compute_instances_add-labels -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_compute_instances_add-labels -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_compute_instances_add-labels -l trace-token -l user-output-enabled -l verbosity

