# gcloud_alpha_active-directory_domains_trusts_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_active-directory_domains_trusts_create.1.gz
complete -c gcloud_alpha_active-directory_domains_trusts_create -l target-dns-ip-addresses -l type -l direction
complete -c gcloud_alpha_active-directory_domains_trusts_create -l selective-authentication -l async -d 'POSITIONAL ARGUMENTS Domain resource - Name of the Managed Microsoft AD domai…'
complete -c gcloud_alpha_active-directory_domains_trusts_create -l target-domain-name
complete -c gcloud_alpha_active-directory_domains_trusts_create -l handshake-secret
complete -c gcloud_alpha_active-directory_domains_trusts_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_active-directory_domains_trusts_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_active-directory_domains_trusts_create -l trace-token -l user-output-enabled -l verbosity

