# gcloud_beta_ml_vision_product-search_product-sets_remove-product
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_ml_vision_product-search_product-sets_remove-product.1.gz
complete -c gcloud_beta_ml_vision_product-search_product-sets_remove-product -l location
complete -c gcloud_beta_ml_vision_product-search_product-sets_remove-product -l product
complete -c gcloud_beta_ml_vision_product-search_product-sets_remove-product -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_ml_vision_product-search_product-sets_remove-product -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_ml_vision_product-search_product-sets_remove-product -l trace-token -l user-output-enabled -l verbosity

