# gcloud_beta_pubsub_lite-subscriptions_subscribe
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_pubsub_lite-subscriptions_subscribe.1.gz
complete -c gcloud_beta_pubsub_lite-subscriptions_subscribe -l zone
complete -c gcloud_beta_pubsub_lite-subscriptions_subscribe -l auto-ack
complete -c gcloud_beta_pubsub_lite-subscriptions_subscribe -l num-messages
complete -c gcloud_beta_pubsub_lite-subscriptions_subscribe -l partitions
complete -c gcloud_beta_pubsub_lite-subscriptions_subscribe -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_pubsub_lite-subscriptions_subscribe -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_pubsub_lite-subscriptions_subscribe -l trace-token -l user-output-enabled -l verbosity

