# gcloud_beta_compute_security-policies_rules_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_compute_security-policies_rules_create.1.gz
complete -c gcloud_beta_compute_security-policies_rules_create -l action
complete -c gcloud_beta_compute_security-policies_rules_create -l expression
complete -c gcloud_beta_compute_security-policies_rules_create -l src-ip-ranges
complete -c gcloud_beta_compute_security-policies_rules_create -l description
complete -c gcloud_beta_compute_security-policies_rules_create -l preview
complete -c gcloud_beta_compute_security-policies_rules_create -l security-policy
complete -c gcloud_beta_compute_security-policies_rules_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_compute_security-policies_rules_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_compute_security-policies_rules_create -l trace-token -l user-output-enabled -l verbosity

