# gcloud_compute_firewall-policies_clone-rules
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_compute_firewall-policies_clone-rules.1.gz
complete -c gcloud_compute_firewall-policies_clone-rules -l source-firewall-policy
complete -c gcloud_compute_firewall-policies_clone-rules -l organization
complete -c gcloud_compute_firewall-policies_clone-rules -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_compute_firewall-policies_clone-rules -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_compute_firewall-policies_clone-rules -l trace-token -l user-output-enabled -l verbosity

