# gcloud_database-migration_migration-jobs_restart
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_database-migration_migration-jobs_restart.1.gz
complete -c gcloud_database-migration_migration-jobs_restart -l region
complete -c gcloud_database-migration_migration-jobs_restart -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_database-migration_migration-jobs_restart -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_database-migration_migration-jobs_restart -l trace-token -l user-output-enabled -l verbosity

