# gcloud_beta_pubsub_lite-subscriptions_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_pubsub_lite-subscriptions_create.1.gz
complete -c gcloud_beta_pubsub_lite-subscriptions_create -l topic
complete -c gcloud_beta_pubsub_lite-subscriptions_create -l zone
complete -c gcloud_beta_pubsub_lite-subscriptions_create -l delivery-requirement
complete -c gcloud_beta_pubsub_lite-subscriptions_create -l starting-offset
complete -c gcloud_beta_pubsub_lite-subscriptions_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_pubsub_lite-subscriptions_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_pubsub_lite-subscriptions_create -l trace-token -l user-output-enabled -l verbosity

