# gcloud_beta_app_gen-config
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_app_gen-config.1.gz
complete -c gcloud_beta_app_gen-config -l config
complete -c gcloud_beta_app_gen-config -l custom
complete -c gcloud_beta_app_gen-config -l runtime
complete -c gcloud_beta_app_gen-config -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_app_gen-config -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_app_gen-config -l trace-token -l user-output-enabled -l verbosity

