# gcloud_dns_record-sets_import
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_dns_record-sets_import.1.gz
complete -c gcloud_dns_record-sets_import -l delete-all-existing -d 'all the records-sets currently in the managed-zone.  EXAMPLES'
complete -c gcloud_dns_record-sets_import -l zone -s z
complete -c gcloud_dns_record-sets_import -l replace-origin-ns
complete -c gcloud_dns_record-sets_import -l zone-file-format
complete -c gcloud_dns_record-sets_import -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_dns_record-sets_import -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_dns_record-sets_import -l trace-token -l user-output-enabled -l verbosity

