# gcloud_alpha_emulators_datastore_env-init
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_emulators_datastore_env-init.1.gz
complete -c gcloud_alpha_emulators_datastore_env-init -l data-dir
complete -c gcloud_alpha_emulators_datastore_env-init -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_emulators_datastore_env-init -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_emulators_datastore_env-init -l trace-token -l user-output-enabled -l verbosity

