# gcloud_alpha_services_quota_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_services_quota_create.1.gz
complete -c gcloud_alpha_services_quota_create -l consumer
complete -c gcloud_alpha_services_quota_create -l metric
complete -c gcloud_alpha_services_quota_create -l service
complete -c gcloud_alpha_services_quota_create -l unit
complete -c gcloud_alpha_services_quota_create -l value
complete -c gcloud_alpha_services_quota_create -l dimensions
complete -c gcloud_alpha_services_quota_create -l force
complete -c gcloud_alpha_services_quota_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_services_quota_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_services_quota_create -l trace-token -l user-output-enabled -l verbosity

