# gcloud_beta_builds_worker-pools_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_builds_worker-pools_update.1.gz
complete -c gcloud_beta_builds_worker-pools_update -l region
complete -c gcloud_beta_builds_worker-pools_update -l config-from-file
complete -c gcloud_beta_builds_worker-pools_update -l peered-network
complete -c gcloud_beta_builds_worker-pools_update -l no-external-ip
complete -c gcloud_beta_builds_worker-pools_update -l worker-disk-size
complete -c gcloud_beta_builds_worker-pools_update -l worker-machine-type
complete -c gcloud_beta_builds_worker-pools_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_builds_worker-pools_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_builds_worker-pools_update -l trace-token -l user-output-enabled -l verbosity

