# gcloud_compute_shared-vpc_disable
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_compute_shared-vpc_disable.1.gz
complete -c gcloud_compute_shared-vpc_disable -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_compute_shared-vpc_disable -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_compute_shared-vpc_disable -l trace-token -l user-output-enabled -l verbosity

