# gcloud_alpha_compute_instance-groups_managed_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_compute_instance-groups_managed_update.1.gz
complete -c gcloud_alpha_compute_instance-groups_managed_update -l health-check -d 'your application'
complete -c gcloud_alpha_compute_instance-groups_managed_update -l instance-redistribution-type
complete -c gcloud_alpha_compute_instance-groups_managed_update -l remove-stateful-disks
complete -c gcloud_alpha_compute_instance-groups_managed_update -l stateful-disk
complete -c gcloud_alpha_compute_instance-groups_managed_update -l target-distribution-shape
complete -c gcloud_alpha_compute_instance-groups_managed_update -l clear-autohealing
complete -c gcloud_alpha_compute_instance-groups_managed_update -l initial-delay
complete -c gcloud_alpha_compute_instance-groups_managed_update -l http-health-check
complete -c gcloud_alpha_compute_instance-groups_managed_update -l https-health-check
complete -c gcloud_alpha_compute_instance-groups_managed_update -l region
complete -c gcloud_alpha_compute_instance-groups_managed_update -l zone
complete -c gcloud_alpha_compute_instance-groups_managed_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_compute_instance-groups_managed_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_compute_instance-groups_managed_update -l trace-token -l user-output-enabled -l verbosity

