# gcloud_beta_error-reporting_events_report
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_error-reporting_events_report.1.gz
complete -c gcloud_beta_error-reporting_events_report -l service
complete -c gcloud_beta_error-reporting_events_report -l message
complete -c gcloud_beta_error-reporting_events_report -l message-file
complete -c gcloud_beta_error-reporting_events_report -l service-version
complete -c gcloud_beta_error-reporting_events_report -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_error-reporting_events_report -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_error-reporting_events_report -l trace-token -l user-output-enabled -l verbosity

