# gcloud_iam_workload-identity-pools_create-cred-config
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_iam_workload-identity-pools_create-cred-config.1.gz
complete -c gcloud_iam_workload-identity-pools_create-cred-config -l output-file
complete -c gcloud_iam_workload-identity-pools_create-cred-config -l aws
complete -c gcloud_iam_workload-identity-pools_create-cred-config -l azure
complete -c gcloud_iam_workload-identity-pools_create-cred-config -l credential-source-file
complete -c gcloud_iam_workload-identity-pools_create-cred-config -l credential-source-url
complete -c gcloud_iam_workload-identity-pools_create-cred-config -l app-id-uri
complete -c gcloud_iam_workload-identity-pools_create-cred-config -l credential-source-field-name
complete -c gcloud_iam_workload-identity-pools_create-cred-config -l credential-source-headers
complete -c gcloud_iam_workload-identity-pools_create-cred-config -l credential-source-type
complete -c gcloud_iam_workload-identity-pools_create-cred-config -l service-account
complete -c gcloud_iam_workload-identity-pools_create-cred-config -l subject-token-type
complete -c gcloud_iam_workload-identity-pools_create-cred-config -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_iam_workload-identity-pools_create-cred-config -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_iam_workload-identity-pools_create-cred-config -l trace-token -l user-output-enabled -l verbosity

