# gcloud_alpha_game_servers_deployments_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_game_servers_deployments_update.1.gz
complete -c gcloud_alpha_game_servers_deployments_update -l location
complete -c gcloud_alpha_game_servers_deployments_update -l async
complete -c gcloud_alpha_game_servers_deployments_update -l description
complete -c gcloud_alpha_game_servers_deployments_update -l update-labels
complete -c gcloud_alpha_game_servers_deployments_update -l clear-labels
complete -c gcloud_alpha_game_servers_deployments_update -l remove-labels
complete -c gcloud_alpha_game_servers_deployments_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_game_servers_deployments_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_game_servers_deployments_update -l trace-token -l user-output-enabled -l verbosity

