# gcloud_container_binauthz_policy_import
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_container_binauthz_policy_import.1.gz
complete -c gcloud_container_binauthz_policy_import -l strict-validation
complete -c gcloud_container_binauthz_policy_import -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_container_binauthz_policy_import -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_container_binauthz_policy_import -l trace-token -l user-output-enabled -l verbosity

