# gcloud_alpha_web-security-scanner_scan-runs_list-crawled-urls
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_web-security-scanner_scan-runs_list-crawled-urls.1.gz
complete -c gcloud_alpha_web-security-scanner_scan-runs_list-crawled-urls -l scan-run
complete -c gcloud_alpha_web-security-scanner_scan-runs_list-crawled-urls -l scan-config
complete -c gcloud_alpha_web-security-scanner_scan-runs_list-crawled-urls -l filter
complete -c gcloud_alpha_web-security-scanner_scan-runs_list-crawled-urls -l sort-by -l limit
complete -c gcloud_alpha_web-security-scanner_scan-runs_list-crawled-urls -l page-size
complete -c gcloud_alpha_web-security-scanner_scan-runs_list-crawled-urls -l flatten -d 'GCLOUD WIDE FLAGS'
complete -c gcloud_alpha_web-security-scanner_scan-runs_list-crawled-urls -l configuration -l flags-file -l format -l help
complete -c gcloud_alpha_web-security-scanner_scan-runs_list-crawled-urls -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_web-security-scanner_scan-runs_list-crawled-urls -l trace-token -l user-output-enabled -l verbosity

