# gcloud_beta_compute_routers_update-bgp-peer
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_compute_routers_update-bgp-peer.1.gz
complete -c gcloud_beta_compute_routers_update-bgp-peer -l peer-name
complete -c gcloud_beta_compute_routers_update-bgp-peer -l advertised-route-priority
complete -c gcloud_beta_compute_routers_update-bgp-peer -l advertisement-mode
complete -c gcloud_beta_compute_routers_update-bgp-peer -l async
complete -c gcloud_beta_compute_routers_update-bgp-peer -l enabled
complete -c gcloud_beta_compute_routers_update-bgp-peer -l no-enabled
complete -c gcloud_beta_compute_routers_update-bgp-peer -l interface
complete -c gcloud_beta_compute_routers_update-bgp-peer -l ip-address
complete -c gcloud_beta_compute_routers_update-bgp-peer -l peer-asn
complete -c gcloud_beta_compute_routers_update-bgp-peer -l peer-ip-address
complete -c gcloud_beta_compute_routers_update-bgp-peer -l region
complete -c gcloud_beta_compute_routers_update-bgp-peer -l set-advertisement-groups
complete -c gcloud_beta_compute_routers_update-bgp-peer -l set-advertisement-ranges
complete -c gcloud_beta_compute_routers_update-bgp-peer -l add-advertisement-groups
complete -c gcloud_beta_compute_routers_update-bgp-peer -l add-advertisement-ranges
complete -c gcloud_beta_compute_routers_update-bgp-peer -l advertisement-ranges -d 'be specified in custom advertisement mode'
complete -c gcloud_beta_compute_routers_update-bgp-peer -l remove-advertisement-groups
complete -c gcloud_beta_compute_routers_update-bgp-peer -l remove-advertisement-ranges
complete -c gcloud_beta_compute_routers_update-bgp-peer -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_compute_routers_update-bgp-peer -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_compute_routers_update-bgp-peer -l trace-token -l user-output-enabled -l verbosity

