# gcloud_alpha_logging_buckets_describe
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_logging_buckets_describe.1.gz
complete -c gcloud_alpha_logging_buckets_describe -l location
complete -c gcloud_alpha_logging_buckets_describe -l billing-account
complete -c gcloud_alpha_logging_buckets_describe -l folder
complete -c gcloud_alpha_logging_buckets_describe -l organization
complete -c gcloud_alpha_logging_buckets_describe -l project
complete -c gcloud_alpha_logging_buckets_describe -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_logging_buckets_describe -l impersonate-service-account -l log-http -l quiet
complete -c gcloud_alpha_logging_buckets_describe -l trace-token -l user-output-enabled -l verbosity

