# gcloud_alpha_container_hub_ingress_enable
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_container_hub_ingress_enable.1.gz
complete -c gcloud_alpha_container_hub_ingress_enable -l billing
complete -c gcloud_alpha_container_hub_ingress_enable -l config-membership
complete -c gcloud_alpha_container_hub_ingress_enable -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_container_hub_ingress_enable -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_container_hub_ingress_enable -l trace-token -l user-output-enabled -l verbosity

