# gcloud_dns_policies_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_dns_policies_update.1.gz
complete -c gcloud_dns_policies_update -l alternative-name-servers
complete -c gcloud_dns_policies_update -l description
complete -c gcloud_dns_policies_update -l enable-inbound-forwarding
complete -c gcloud_dns_policies_update -l enable-logging
complete -c gcloud_dns_policies_update -l networks
complete -c gcloud_dns_policies_update -l private-alternative-name-servers
complete -c gcloud_dns_policies_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_dns_policies_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_dns_policies_update -l trace-token -l user-output-enabled -l verbosity

