# gcloud_compute_diagnose_routes
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_compute_diagnose_routes.1.gz
complete -c gcloud_compute_diagnose_routes -l container
complete -c gcloud_compute_diagnose_routes -l dry-run
complete -c gcloud_compute_diagnose_routes -l external-route-ip
complete -c gcloud_compute_diagnose_routes -l force-key-file-overwrite
complete -c gcloud_compute_diagnose_routes -l plain
complete -c gcloud_compute_diagnose_routes -l regexp -s r
complete -c gcloud_compute_diagnose_routes -l reverse-traceroute
complete -c gcloud_compute_diagnose_routes -l ssh-flag
complete -c gcloud_compute_diagnose_routes -l ssh-key-file
complete -c gcloud_compute_diagnose_routes -l strict-host-key-checking
complete -c gcloud_compute_diagnose_routes -l user
complete -c gcloud_compute_diagnose_routes -l zones
complete -c gcloud_compute_diagnose_routes -l ssh-key-expiration
complete -c gcloud_compute_diagnose_routes -l ssh-key-expire-after
complete -c gcloud_compute_diagnose_routes -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_compute_diagnose_routes -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_compute_diagnose_routes -l trace-token -l user-output-enabled -l verbosity

