# gcloud_beta_compute_backend-buckets_delete-signed-url-key
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_compute_backend-buckets_delete-signed-url-key.1.gz
complete -c gcloud_beta_compute_backend-buckets_delete-signed-url-key -l key-name
complete -c gcloud_beta_compute_backend-buckets_delete-signed-url-key -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_compute_backend-buckets_delete-signed-url-key -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_compute_backend-buckets_delete-signed-url-key -l trace-token -l user-output-enabled -l verbosity

