# gcloud_beta_tasks_queues_create-pull-queue
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_tasks_queues_create-pull-queue.1.gz
complete -c gcloud_beta_tasks_queues_create-pull-queue -l max-attempts -l max-retry-duration -d 'POSITIONAL ARGUMENTS QUEUE'
complete -c gcloud_beta_tasks_queues_create-pull-queue -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_tasks_queues_create-pull-queue -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_tasks_queues_create-pull-queue -l trace-token -l user-output-enabled -l verbosity

