# gcloud_alpha_spanner_operations_cancel
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_spanner_operations_cancel.1.gz
complete -c gcloud_alpha_spanner_operations_cancel -l instance
complete -c gcloud_alpha_spanner_operations_cancel -l backup
complete -c gcloud_alpha_spanner_operations_cancel -l database
complete -c gcloud_alpha_spanner_operations_cancel -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_spanner_operations_cancel -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_spanner_operations_cancel -l trace-token -l user-output-enabled -l verbosity

