# gcloud_alpha_compute_org-security-policies_rules_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_compute_org-security-policies_rules_update.1.gz
complete -c gcloud_alpha_compute_org-security-policies_rules_update -l description -d 'POSITIONAL ARGUMENTS PRIORITY'
complete -c gcloud_alpha_compute_org-security-policies_rules_update -l security-policy
complete -c gcloud_alpha_compute_org-security-policies_rules_update -l action
complete -c gcloud_alpha_compute_org-security-policies_rules_update -l dest-ip-ranges
complete -c gcloud_alpha_compute_org-security-policies_rules_update -l dest-ports
complete -c gcloud_alpha_compute_org-security-policies_rules_update -l direction
complete -c gcloud_alpha_compute_org-security-policies_rules_update -l enable-logging
complete -c gcloud_alpha_compute_org-security-policies_rules_update -l layer4-configs
complete -c gcloud_alpha_compute_org-security-policies_rules_update -l new-priority
complete -c gcloud_alpha_compute_org-security-policies_rules_update -l organization
complete -c gcloud_alpha_compute_org-security-policies_rules_update -l src-ip-ranges
complete -c gcloud_alpha_compute_org-security-policies_rules_update -l target-resources
complete -c gcloud_alpha_compute_org-security-policies_rules_update -l target-service-accounts
complete -c gcloud_alpha_compute_org-security-policies_rules_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_compute_org-security-policies_rules_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_compute_org-security-policies_rules_update -l trace-token -l user-output-enabled -l verbosity

