# gcloud_beta_emulators_pubsub_start
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_emulators_pubsub_start.1.gz
complete -c gcloud_beta_emulators_pubsub_start -l data-dir
complete -c gcloud_beta_emulators_pubsub_start -l host-port
complete -c gcloud_beta_emulators_pubsub_start -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_emulators_pubsub_start -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_emulators_pubsub_start -l trace-token -l user-output-enabled -l verbosity

