# gcloud_alpha_resource-manager_liens_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_resource-manager_liens_create.1.gz
complete -c gcloud_alpha_resource-manager_liens_create -l reason
complete -c gcloud_alpha_resource-manager_liens_create -l restrictions
complete -c gcloud_alpha_resource-manager_liens_create -l origin
complete -c gcloud_alpha_resource-manager_liens_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_resource-manager_liens_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_resource-manager_liens_create -l trace-token -l user-output-enabled -l verbosity

