# gcloud_alpha_services_vpc-peerings_disable-vpc-service-controls
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_services_vpc-peerings_disable-vpc-service-controls.1.gz
complete -c gcloud_alpha_services_vpc-peerings_disable-vpc-service-controls -l network
complete -c gcloud_alpha_services_vpc-peerings_disable-vpc-service-controls -l async
complete -c gcloud_alpha_services_vpc-peerings_disable-vpc-service-controls -l service
complete -c gcloud_alpha_services_vpc-peerings_disable-vpc-service-controls -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_services_vpc-peerings_disable-vpc-service-controls -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_services_vpc-peerings_disable-vpc-service-controls -l trace-token -l user-output-enabled -l verbosity

