# gcloud_alpha_deployment-manager_types_describe
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_deployment-manager_types_describe.1.gz
complete -c gcloud_alpha_deployment-manager_types_describe -l provider
complete -c gcloud_alpha_deployment-manager_types_describe -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_deployment-manager_types_describe -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_deployment-manager_types_describe -l trace-token -l user-output-enabled -l verbosity

