# gcloud_healthcare_dicom-stores_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_healthcare_dicom-stores_create.1.gz
complete -c gcloud_healthcare_dicom-stores_create -l dataset
complete -c gcloud_healthcare_dicom-stores_create -l location
complete -c gcloud_healthcare_dicom-stores_create -l pubsub-topic
complete -c gcloud_healthcare_dicom-stores_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_healthcare_dicom-stores_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_healthcare_dicom-stores_create -l trace-token -l user-output-enabled -l verbosity

