# gcloud_alpha_container_operations
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_container_operations.1.gz
complete -c gcloud_alpha_container_operations -l region
complete -c gcloud_alpha_container_operations -l zone -s z

