# gcloud_notebooks_instances_rollback
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_notebooks_instances_rollback.1.gz
complete -c gcloud_notebooks_instances_rollback -l location
complete -c gcloud_notebooks_instances_rollback -l target-snapshot
complete -c gcloud_notebooks_instances_rollback -l async
complete -c gcloud_notebooks_instances_rollback -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_notebooks_instances_rollback -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_notebooks_instances_rollback -l trace-token -l user-output-enabled -l verbosity

