# gcloud_beta_projects_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_projects_update.1.gz
complete -c gcloud_beta_projects_update -l name
complete -c gcloud_beta_projects_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_projects_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_projects_update -l trace-token -l user-output-enabled -l verbosity

