# gcloud_beta_kms_keys_versions_describe
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_kms_keys_versions_describe.1.gz
complete -c gcloud_beta_kms_keys_versions_describe -l attestation-file -d '$ gcloud beta kms keys versions describe 2 --key=frodo \\     --keyring=fellow…'
complete -c gcloud_beta_kms_keys_versions_describe -l key
complete -c gcloud_beta_kms_keys_versions_describe -l keyring
complete -c gcloud_beta_kms_keys_versions_describe -l location
complete -c gcloud_beta_kms_keys_versions_describe -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_kms_keys_versions_describe -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_kms_keys_versions_describe -l trace-token -l user-output-enabled -l verbosity

