# gcloud_alpha_compute_addresses_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_compute_addresses_create.1.gz
complete -c gcloud_alpha_compute_addresses_create -l description
complete -c gcloud_alpha_compute_addresses_create -l network
complete -c gcloud_alpha_compute_addresses_create -l network-tier
complete -c gcloud_alpha_compute_addresses_create -l prefix-length
complete -c gcloud_alpha_compute_addresses_create -l purpose
complete -c gcloud_alpha_compute_addresses_create -l subnet
complete -c gcloud_alpha_compute_addresses_create -l address
complete -c gcloud_alpha_compute_addresses_create -l addresses
complete -c gcloud_alpha_compute_addresses_create -l ip-version
complete -c gcloud_alpha_compute_addresses_create -l global
complete -c gcloud_alpha_compute_addresses_create -l region
complete -c gcloud_alpha_compute_addresses_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_compute_addresses_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_compute_addresses_create -l trace-token -l user-output-enabled -l verbosity

