# gcloud_compute_instance-groups_managed_update-instances
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_compute_instance-groups_managed_update-instances.1.gz
complete -c gcloud_compute_instance-groups_managed_update-instances -l instances
complete -c gcloud_compute_instance-groups_managed_update-instances -l minimal-action
complete -c gcloud_compute_instance-groups_managed_update-instances -l most-disruptive-allowed-action
complete -c gcloud_compute_instance-groups_managed_update-instances -l region
complete -c gcloud_compute_instance-groups_managed_update-instances -l zone
complete -c gcloud_compute_instance-groups_managed_update-instances -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_compute_instance-groups_managed_update-instances -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_compute_instance-groups_managed_update-instances -l trace-token -l user-output-enabled -l verbosity

