# gcloud_alpha_auth_login
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_auth_login.1.gz
complete -c gcloud_alpha_auth_login -l activate
complete -c gcloud_alpha_auth_login -l brief
complete -c gcloud_alpha_auth_login -l enable-gdrive-access
complete -c gcloud_alpha_auth_login -l force
complete -c gcloud_alpha_auth_login -l launch-browser
complete -c gcloud_alpha_auth_login -l update-adc
complete -c gcloud_alpha_auth_login -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_auth_login -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_auth_login -l trace-token -l user-output-enabled -l verbosity

