# gcloud_alpha_data-catalog_crawlers_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_data-catalog_crawlers_create.1.gz
complete -c gcloud_alpha_data-catalog_crawlers_create -l crawl-scope
complete -c gcloud_alpha_data-catalog_crawlers_create -l buckets
complete -c gcloud_alpha_data-catalog_crawlers_create -l run-option
complete -c gcloud_alpha_data-catalog_crawlers_create -l run-schedule
complete -c gcloud_alpha_data-catalog_crawlers_create -l bundle-specs
complete -c gcloud_alpha_data-catalog_crawlers_create -l description
complete -c gcloud_alpha_data-catalog_crawlers_create -l display-name
complete -c gcloud_alpha_data-catalog_crawlers_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_data-catalog_crawlers_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_data-catalog_crawlers_create -l trace-token -l user-output-enabled -l verbosity

