# gcloud_compute_url-maps_list-cdn-cache-invalidations
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_compute_url-maps_list-cdn-cache-invalidations.1.gz
complete -c gcloud_compute_url-maps_list-cdn-cache-invalidations -l limit
complete -c gcloud_compute_url-maps_list-cdn-cache-invalidations -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_compute_url-maps_list-cdn-cache-invalidations -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_compute_url-maps_list-cdn-cache-invalidations -l trace-token -l user-output-enabled -l verbosity

