# gcloud_docker
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_docker.1.gz
complete -c gcloud_docker -l authorize-only -s a
complete -c gcloud_docker -l docker-host
complete -c gcloud_docker -l server -s s
complete -c gcloud_docker -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_docker -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_docker -l trace-token -l user-output-enabled -l verbosity

