# gcloud_alpha_recommender_recommendations_mark-dismissed
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_recommender_recommendations_mark-dismissed.1.gz
complete -c gcloud_alpha_recommender_recommendations_mark-dismissed -l recommender -l etag -d 'POSITIONAL ARGUMENTS RECOMMENDATION'
complete -c gcloud_alpha_recommender_recommendations_mark-dismissed -l location
complete -c gcloud_alpha_recommender_recommendations_mark-dismissed -l organization
complete -c gcloud_alpha_recommender_recommendations_mark-dismissed -l billing-account
complete -c gcloud_alpha_recommender_recommendations_mark-dismissed -l folder
complete -c gcloud_alpha_recommender_recommendations_mark-dismissed -l project
complete -c gcloud_alpha_recommender_recommendations_mark-dismissed -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_recommender_recommendations_mark-dismissed -l impersonate-service-account -l log-http -l quiet
complete -c gcloud_alpha_recommender_recommendations_mark-dismissed -l trace-token -l user-output-enabled -l verbosity

