# gcloud_beta_compute_health-checks_update_ssl
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_compute_health-checks_update_ssl.1.gz
complete -c gcloud_beta_compute_health-checks_update_ssl -l check-interval
complete -c gcloud_beta_compute_health-checks_update_ssl -l description
complete -c gcloud_beta_compute_health-checks_update_ssl -l enable-logging
complete -c gcloud_beta_compute_health-checks_update_ssl -l healthy-threshold
complete -c gcloud_beta_compute_health-checks_update_ssl -l proxy-header
complete -c gcloud_beta_compute_health-checks_update_ssl -l request
complete -c gcloud_beta_compute_health-checks_update_ssl -l response
complete -c gcloud_beta_compute_health-checks_update_ssl -l timeout
complete -c gcloud_beta_compute_health-checks_update_ssl -l unhealthy-threshold
complete -c gcloud_beta_compute_health-checks_update_ssl -l global
complete -c gcloud_beta_compute_health-checks_update_ssl -l region
complete -c gcloud_beta_compute_health-checks_update_ssl -l port -l port-name -l port -d precedence
complete -c gcloud_beta_compute_health-checks_update_ssl -l use-serving-port
complete -c gcloud_beta_compute_health-checks_update_ssl -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_compute_health-checks_update_ssl -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_compute_health-checks_update_ssl -l trace-token -l user-output-enabled -l verbosity

