# gcloud_alpha_logging_copy
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_logging_copy.1.gz
complete -c gcloud_alpha_logging_copy -l location
complete -c gcloud_alpha_logging_copy -l log_filter
complete -c gcloud_alpha_logging_copy -l billing-account
complete -c gcloud_alpha_logging_copy -l folder
complete -c gcloud_alpha_logging_copy -l organization
complete -c gcloud_alpha_logging_copy -l project
complete -c gcloud_alpha_logging_copy -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_logging_copy -l impersonate-service-account -l log-http -l quiet
complete -c gcloud_alpha_logging_copy -l trace-token -l user-output-enabled -l verbosity

