# gcloud_alpha_composer_environments_storage_plugins_list
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_composer_environments_storage_plugins_list.1.gz
complete -c gcloud_alpha_composer_environments_storage_plugins_list -l environment
complete -c gcloud_alpha_composer_environments_storage_plugins_list -l location
complete -c gcloud_alpha_composer_environments_storage_plugins_list -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_composer_environments_storage_plugins_list -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_composer_environments_storage_plugins_list -l trace-token -l user-output-enabled -l verbosity

