# gcloud_dns_record-sets_transaction_abort
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_dns_record-sets_transaction_abort.1.gz
complete -c gcloud_dns_record-sets_transaction_abort -l zone -s z
complete -c gcloud_dns_record-sets_transaction_abort -l transaction-file
complete -c gcloud_dns_record-sets_transaction_abort -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_dns_record-sets_transaction_abort -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_dns_record-sets_transaction_abort -l trace-token -l user-output-enabled -l verbosity

