# gcloud_feedback
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_feedback.1.gz
complete -c gcloud_feedback -l log-file
complete -c gcloud_feedback -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_feedback -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_feedback -l trace-token -l user-output-enabled -l verbosity

