# gcloud_run_services_set-iam-policy
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_run_services_set-iam-policy.1.gz
complete -c gcloud_run_services_set-iam-policy -l platform
complete -c gcloud_run_services_set-iam-policy -l cluster-location -d '[run/cluster_location] properties to specify a cluster in a given zone'
complete -c gcloud_run_services_set-iam-policy -l region
complete -c gcloud_run_services_set-iam-policy -l cluster
complete -c gcloud_run_services_set-iam-policy -l context
complete -c gcloud_run_services_set-iam-policy -l kubeconfig
complete -c gcloud_run_services_set-iam-policy -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_run_services_set-iam-policy -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_run_services_set-iam-policy -l trace-token -l user-output-enabled -l verbosity

