# gcloud_beta_compute_instances_network-interfaces_get-effective-firewalls
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_compute_instances_network-interfaces_get-effective-firewalls.1.gz
complete -c gcloud_beta_compute_instances_network-interfaces_get-effective-firewalls -l format -d 'To see more firewall rule fields in table format, run the following for "exam…'
complete -c gcloud_beta_compute_instances_network-interfaces_get-effective-firewalls -l network-interface
complete -c gcloud_beta_compute_instances_network-interfaces_get-effective-firewalls -l regexp -s r
complete -c gcloud_beta_compute_instances_network-interfaces_get-effective-firewalls -l zone
complete -c gcloud_beta_compute_instances_network-interfaces_get-effective-firewalls -l filter
complete -c gcloud_beta_compute_instances_network-interfaces_get-effective-firewalls -l sort-by -l limit
complete -c gcloud_beta_compute_instances_network-interfaces_get-effective-firewalls -l page-size
complete -c gcloud_beta_compute_instances_network-interfaces_get-effective-firewalls -l flatten
complete -c gcloud_beta_compute_instances_network-interfaces_get-effective-firewalls -l uri
complete -c gcloud_beta_compute_instances_network-interfaces_get-effective-firewalls -l configuration -l flags-file -l help
complete -c gcloud_beta_compute_instances_network-interfaces_get-effective-firewalls -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_compute_instances_network-interfaces_get-effective-firewalls -l trace-token -l user-output-enabled -l verbosity

