# gcloud_beta_eventarc_attributes_service-names_list
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_eventarc_attributes_service-names_list.1.gz
complete -c gcloud_beta_eventarc_attributes_service-names_list -l type
complete -c gcloud_beta_eventarc_attributes_service-names_list -l filter
complete -c gcloud_beta_eventarc_attributes_service-names_list -l sort-by -l limit
complete -c gcloud_beta_eventarc_attributes_service-names_list -l flatten -d 'GCLOUD WIDE FLAGS'
complete -c gcloud_beta_eventarc_attributes_service-names_list -l configuration -l flags-file -l format -l help
complete -c gcloud_beta_eventarc_attributes_service-names_list -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_eventarc_attributes_service-names_list -l trace-token -l user-output-enabled -l verbosity

