# gcloud_alpha_recommender_recommender-configs_describe
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_recommender_recommender-configs_describe.1.gz
complete -c gcloud_alpha_recommender_recommender-configs_describe -l location
complete -c gcloud_alpha_recommender_recommender-configs_describe -l project
complete -c gcloud_alpha_recommender_recommender-configs_describe -l recommender
complete -c gcloud_alpha_recommender_recommender-configs_describe -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_recommender_recommender-configs_describe -l impersonate-service-account -l log-http -l quiet
complete -c gcloud_alpha_recommender_recommender-configs_describe -l trace-token -l user-output-enabled -l verbosity

