# gcloud_beta_projects_move
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_projects_move.1.gz
complete -c gcloud_beta_projects_move -l folder
complete -c gcloud_beta_projects_move -l organization
complete -c gcloud_beta_projects_move -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_projects_move -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_projects_move -l trace-token -l user-output-enabled -l verbosity

