# gcloud_compute_os-login_ssh-keys_add
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_compute_os-login_ssh-keys_add.1.gz
complete -c gcloud_compute_os-login_ssh-keys_add -l key
complete -c gcloud_compute_os-login_ssh-keys_add -l key-file
complete -c gcloud_compute_os-login_ssh-keys_add -l ttl
complete -c gcloud_compute_os-login_ssh-keys_add -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_compute_os-login_ssh-keys_add -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_compute_os-login_ssh-keys_add -l trace-token -l user-output-enabled -l verbosity

