# gcloud_artifacts_docker_images_delete
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_artifacts_docker_images_delete.1.gz
complete -c gcloud_artifacts_docker_images_delete -l delete-tags -d 'o 2m Trying to delete an image by tag when the image has other tags.  Add'
complete -c gcloud_artifacts_docker_images_delete -l async
complete -c gcloud_artifacts_docker_images_delete -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_artifacts_docker_images_delete -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_artifacts_docker_images_delete -l trace-token -l user-output-enabled -l verbosity

