# gcloud_access-context-manager_perimeters_dry-run_enforce-all
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_access-context-manager_perimeters_dry-run_enforce-all.1.gz
complete -c gcloud_access-context-manager_perimeters_dry-run_enforce-all -l etag
complete -c gcloud_access-context-manager_perimeters_dry-run_enforce-all -l policy
complete -c gcloud_access-context-manager_perimeters_dry-run_enforce-all -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_access-context-manager_perimeters_dry-run_enforce-all -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_access-context-manager_perimeters_dry-run_enforce-all -l trace-token -l user-output-enabled -l verbosity

