# gcloud_beta_compute_instances_add-metadata
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_compute_instances_add-metadata.1.gz
complete -c gcloud_beta_compute_instances_add-metadata -l metadata
complete -c gcloud_beta_compute_instances_add-metadata -l metadata-from-file
complete -c gcloud_beta_compute_instances_add-metadata -l zone
complete -c gcloud_beta_compute_instances_add-metadata -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_compute_instances_add-metadata -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_compute_instances_add-metadata -l trace-token -l user-output-enabled -l verbosity

