# gcloud_beta_compute_networks_get-effective-firewalls
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_compute_networks_get-effective-firewalls.1.gz
complete -c gcloud_beta_compute_networks_get-effective-firewalls -l format -d 'To list more the fields of the rules of network example-network in table form…'
complete -c gcloud_beta_compute_networks_get-effective-firewalls -l regexp -s r
complete -c gcloud_beta_compute_networks_get-effective-firewalls -l filter
complete -c gcloud_beta_compute_networks_get-effective-firewalls -l sort-by -l limit
complete -c gcloud_beta_compute_networks_get-effective-firewalls -l page-size
complete -c gcloud_beta_compute_networks_get-effective-firewalls -l flatten
complete -c gcloud_beta_compute_networks_get-effective-firewalls -l uri
complete -c gcloud_beta_compute_networks_get-effective-firewalls -l configuration -l flags-file -l help
complete -c gcloud_beta_compute_networks_get-effective-firewalls -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_compute_networks_get-effective-firewalls -l trace-token -l user-output-enabled -l verbosity

