# gcloud_beta_tasks_list
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_tasks_list.1.gz
complete -c gcloud_beta_tasks_list -l queue
complete -c gcloud_beta_tasks_list -l filter
complete -c gcloud_beta_tasks_list -l sort-by -l limit
complete -c gcloud_beta_tasks_list -l page-size
complete -c gcloud_beta_tasks_list -l flatten
complete -c gcloud_beta_tasks_list -l uri
complete -c gcloud_beta_tasks_list -l configuration -l flags-file -l format -l help
complete -c gcloud_beta_tasks_list -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_tasks_list -l trace-token -l user-output-enabled -l verbosity

