# gcloud_beta_compute_health-checks_create_https
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_compute_health-checks_create_https.1.gz
complete -c gcloud_beta_compute_health-checks_create_https -l check-interval
complete -c gcloud_beta_compute_health-checks_create_https -l description
complete -c gcloud_beta_compute_health-checks_create_https -l enable-logging
complete -c gcloud_beta_compute_health-checks_create_https -l healthy-threshold
complete -c gcloud_beta_compute_health-checks_create_https -l host
complete -c gcloud_beta_compute_health-checks_create_https -l proxy-header
complete -c gcloud_beta_compute_health-checks_create_https -l request-path
complete -c gcloud_beta_compute_health-checks_create_https -l response
complete -c gcloud_beta_compute_health-checks_create_https -l timeout
complete -c gcloud_beta_compute_health-checks_create_https -l unhealthy-threshold
complete -c gcloud_beta_compute_health-checks_create_https -l global
complete -c gcloud_beta_compute_health-checks_create_https -l region
complete -c gcloud_beta_compute_health-checks_create_https -l port-name -l port
complete -c gcloud_beta_compute_health-checks_create_https -l use-serving-port
complete -c gcloud_beta_compute_health-checks_create_https -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_compute_health-checks_create_https -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_compute_health-checks_create_https -l trace-token -l user-output-enabled -l verbosity

