# gcloud_functions_logs_read
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_functions_logs_read.1.gz
complete -c gcloud_functions_logs_read -l end-time
complete -c gcloud_functions_logs_read -l execution-id
complete -c gcloud_functions_logs_read -l limit
complete -c gcloud_functions_logs_read -l min-log-level
complete -c gcloud_functions_logs_read -l region
complete -c gcloud_functions_logs_read -l start-time
complete -c gcloud_functions_logs_read -l filter
complete -c gcloud_functions_logs_read -l sort-by
complete -c gcloud_functions_logs_read -l page-size
complete -c gcloud_functions_logs_read -l flatten
complete -c gcloud_functions_logs_read -l uri
complete -c gcloud_functions_logs_read -l configuration -l flags-file -l format -l help
complete -c gcloud_functions_logs_read -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_functions_logs_read -l trace-token -l user-output-enabled -l verbosity

