# gcloud_beta_dataflow_metrics_list
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_dataflow_metrics_list.1.gz
complete -c gcloud_beta_dataflow_metrics_list -l changed-after
complete -c gcloud_beta_dataflow_metrics_list -l hide-committed
complete -c gcloud_beta_dataflow_metrics_list -l region
complete -c gcloud_beta_dataflow_metrics_list -l source
complete -c gcloud_beta_dataflow_metrics_list -l tentative
complete -c gcloud_beta_dataflow_metrics_list -l transform
complete -c gcloud_beta_dataflow_metrics_list -l filter
complete -c gcloud_beta_dataflow_metrics_list -l sort-by -l limit
complete -c gcloud_beta_dataflow_metrics_list -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_dataflow_metrics_list -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_dataflow_metrics_list -l trace-token -l user-output-enabled -l verbosity

