# gcloud_alpha_compute_routers_nats_rules_list
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_compute_routers_nats_rules_list.1.gz
complete -c gcloud_alpha_compute_routers_nats_rules_list -l nat
complete -c gcloud_alpha_compute_routers_nats_rules_list -l router
complete -c gcloud_alpha_compute_routers_nats_rules_list -l region
complete -c gcloud_alpha_compute_routers_nats_rules_list -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_compute_routers_nats_rules_list -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_compute_routers_nats_rules_list -l trace-token -l user-output-enabled -l verbosity

