# gcloud_alpha_identity_groups_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_identity_groups_update.1.gz
complete -c gcloud_alpha_identity_groups_update -l dynamic-user-query
complete -c gcloud_alpha_identity_groups_update -l add-posix-group
complete -c gcloud_alpha_identity_groups_update -l clear-posix-groups
complete -c gcloud_alpha_identity_groups_update -l remove-posix-groups
complete -c gcloud_alpha_identity_groups_update -l clear-description
complete -c gcloud_alpha_identity_groups_update -l description
complete -c gcloud_alpha_identity_groups_update -l clear-display-name
complete -c gcloud_alpha_identity_groups_update -l display-name
complete -c gcloud_alpha_identity_groups_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_identity_groups_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_identity_groups_update -l trace-token -l user-output-enabled -l verbosity

