# gcloud_beta_composer_environments_storage_plugins_import
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_composer_environments_storage_plugins_import.1.gz
complete -c gcloud_beta_composer_environments_storage_plugins_import -l source
complete -c gcloud_beta_composer_environments_storage_plugins_import -l environment
complete -c gcloud_beta_composer_environments_storage_plugins_import -l location
complete -c gcloud_beta_composer_environments_storage_plugins_import -l destination
complete -c gcloud_beta_composer_environments_storage_plugins_import -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_composer_environments_storage_plugins_import -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_composer_environments_storage_plugins_import -l trace-token -l user-output-enabled -l verbosity

