# gcloud_compute_target-https-proxies_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_compute_target-https-proxies_update.1.gz
complete -c gcloud_compute_target-https-proxies_update -l quic-override
complete -c gcloud_compute_target-https-proxies_update -l ssl-certificates
complete -c gcloud_compute_target-https-proxies_update -l url-map
complete -c gcloud_compute_target-https-proxies_update -l clear-ssl-policy
complete -c gcloud_compute_target-https-proxies_update -l ssl-policy
complete -c gcloud_compute_target-https-proxies_update -l global
complete -c gcloud_compute_target-https-proxies_update -l region
complete -c gcloud_compute_target-https-proxies_update -l global-ssl-certificates
complete -c gcloud_compute_target-https-proxies_update -l ssl-certificates-region
complete -c gcloud_compute_target-https-proxies_update -l global-url-map
complete -c gcloud_compute_target-https-proxies_update -l url-map-region
complete -c gcloud_compute_target-https-proxies_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_compute_target-https-proxies_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_compute_target-https-proxies_update -l trace-token -l user-output-enabled -l verbosity

