# gcloud_alpha_ai-platform_jobs_describe
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_ai-platform_jobs_describe.1.gz
complete -c gcloud_alpha_ai-platform_jobs_describe -l summarize
complete -c gcloud_alpha_ai-platform_jobs_describe -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_ai-platform_jobs_describe -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_ai-platform_jobs_describe -l trace-token -l user-output-enabled -l verbosity

