# gcloud_alpha_container_hub_cloudrun_disable
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_container_hub_cloudrun_disable.1.gz
complete -c gcloud_alpha_container_hub_cloudrun_disable -l force
complete -c gcloud_alpha_container_hub_cloudrun_disable -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_container_hub_cloudrun_disable -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_container_hub_cloudrun_disable -l trace-token -l user-output-enabled -l verbosity

