# gcloud_beta_compute_instances_delete
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_compute_instances_delete.1.gz
complete -c gcloud_beta_compute_instances_delete -l zone
complete -c gcloud_beta_compute_instances_delete -l delete-disks
complete -c gcloud_beta_compute_instances_delete -l keep-disks
complete -c gcloud_beta_compute_instances_delete -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_compute_instances_delete -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_compute_instances_delete -l trace-token -l user-output-enabled -l verbosity

