# gcloud_beta_source_repos_clone
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_source_repos_clone.1.gz
complete -c gcloud_beta_source_repos_clone -l dry-run
complete -c gcloud_beta_source_repos_clone -l use-full-gcloud-path
complete -c gcloud_beta_source_repos_clone -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_source_repos_clone -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_source_repos_clone -l trace-token -l user-output-enabled -l verbosity

