# gcloud_alpha_container_clusters_list
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_container_clusters_list.1.gz
complete -c gcloud_alpha_container_clusters_list -l region
complete -c gcloud_alpha_container_clusters_list -l zone -s z
complete -c gcloud_alpha_container_clusters_list -l filter
complete -c gcloud_alpha_container_clusters_list -l sort-by -l limit
complete -c gcloud_alpha_container_clusters_list -l page-size
complete -c gcloud_alpha_container_clusters_list -l flatten
complete -c gcloud_alpha_container_clusters_list -l uri
complete -c gcloud_alpha_container_clusters_list -l configuration -l flags-file -l format -l help
complete -c gcloud_alpha_container_clusters_list -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_container_clusters_list -l trace-token -l user-output-enabled -l verbosity

