# gcloud_identity_groups_memberships_list
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_identity_groups_memberships_list.1.gz
complete -c gcloud_identity_groups_memberships_list -l group-email
complete -c gcloud_identity_groups_memberships_list -l page-token
complete -c gcloud_identity_groups_memberships_list -l view
complete -c gcloud_identity_groups_memberships_list -l filter
complete -c gcloud_identity_groups_memberships_list -l sort-by -l limit
complete -c gcloud_identity_groups_memberships_list -l page-size
complete -c gcloud_identity_groups_memberships_list -l flatten -d 'GCLOUD WIDE FLAGS'
complete -c gcloud_identity_groups_memberships_list -l configuration -l flags-file -l format -l help
complete -c gcloud_identity_groups_memberships_list -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_identity_groups_memberships_list -l trace-token -l user-output-enabled -l verbosity

