# gcloud_alpha_compute_routers_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_compute_routers_create.1.gz
complete -c gcloud_alpha_compute_routers_create -l network
complete -c gcloud_alpha_compute_routers_create -l advertisement-mode
complete -c gcloud_alpha_compute_routers_create -l asn
complete -c gcloud_alpha_compute_routers_create -l async
complete -c gcloud_alpha_compute_routers_create -l description
complete -c gcloud_alpha_compute_routers_create -l keepalive-interval
complete -c gcloud_alpha_compute_routers_create -l region
complete -c gcloud_alpha_compute_routers_create -l set-advertisement-groups
complete -c gcloud_alpha_compute_routers_create -l set-advertisement-ranges
complete -c gcloud_alpha_compute_routers_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_compute_routers_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_compute_routers_create -l trace-token -l user-output-enabled -l verbosity

