# gcloud_bigtable_clusters_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_bigtable_clusters_create.1.gz
complete -c gcloud_bigtable_clusters_create -l instance
complete -c gcloud_bigtable_clusters_create -l zone
complete -c gcloud_bigtable_clusters_create -l async
complete -c gcloud_bigtable_clusters_create -l num-nodes
complete -c gcloud_bigtable_clusters_create -l kms-key
complete -c gcloud_bigtable_clusters_create -l kms-keyring
complete -c gcloud_bigtable_clusters_create -l kms-location
complete -c gcloud_bigtable_clusters_create -l kms-project
complete -c gcloud_bigtable_clusters_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_bigtable_clusters_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_bigtable_clusters_create -l trace-token -l user-output-enabled -l verbosity

