# gcloud_container_clusters_create-auto
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_container_clusters_create-auto.1.gz
complete -c gcloud_container_clusters_create-auto -l async
complete -c gcloud_container_clusters_create-auto -l cluster-ipv4-cidr
complete -c gcloud_container_clusters_create-auto -l cluster-secondary-range-name
complete -c gcloud_container_clusters_create-auto -l create-subnetwork
complete -c gcloud_container_clusters_create-auto -l cluster-version
complete -c gcloud_container_clusters_create-auto -l network
complete -c gcloud_container_clusters_create-auto -l release-channel
complete -c gcloud_container_clusters_create-auto -l services-ipv4-cidr
complete -c gcloud_container_clusters_create-auto -l services-secondary-range-name
complete -c gcloud_container_clusters_create-auto -l subnetwork
complete -c gcloud_container_clusters_create-auto -l enable-master-authorized-networks
complete -c gcloud_container_clusters_create-auto -l master-authorized-networks -d 'through HTTPS'
complete -c gcloud_container_clusters_create-auto -l enable-private-endpoint
complete -c gcloud_container_clusters_create-auto -l enable-private-nodes
complete -c gcloud_container_clusters_create-auto -l master-ipv4-cidr
complete -c gcloud_container_clusters_create-auto -l region
complete -c gcloud_container_clusters_create-auto -l zone -s z
complete -c gcloud_container_clusters_create-auto -l scopes
complete -c gcloud_container_clusters_create-auto -l enable-cloud-monitoring -d 'the full URI of the scope or an alias'
complete -c gcloud_container_clusters_create-auto -l service-account
complete -c gcloud_container_clusters_create-auto -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_container_clusters_create-auto -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_container_clusters_create-auto -l trace-token -l user-output-enabled -l verbosity

