# gcloud_access-context-manager_perimeters_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_access-context-manager_perimeters_create.1.gz
complete -c gcloud_access-context-manager_perimeters_create -l policy
complete -c gcloud_access-context-manager_perimeters_create -l title
complete -c gcloud_access-context-manager_perimeters_create -l access-levels
complete -c gcloud_access-context-manager_perimeters_create -l async
complete -c gcloud_access-context-manager_perimeters_create -l description
complete -c gcloud_access-context-manager_perimeters_create -l egress-policies
complete -c gcloud_access-context-manager_perimeters_create -l ingress-policies
complete -c gcloud_access-context-manager_perimeters_create -l perimeter-type
complete -c gcloud_access-context-manager_perimeters_create -l resources
complete -c gcloud_access-context-manager_perimeters_create -l restricted-services
complete -c gcloud_access-context-manager_perimeters_create -l enable-vpc-accessible-services
complete -c gcloud_access-context-manager_perimeters_create -l vpc-allowed-services
complete -c gcloud_access-context-manager_perimeters_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_access-context-manager_perimeters_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_access-context-manager_perimeters_create -l trace-token -l user-output-enabled -l verbosity

