# gcloud_beta_debug_logpoints_list
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_debug_logpoints_list.1.gz
complete -c gcloud_beta_debug_logpoints_list -l include-inactive -d EXAMPLES
complete -c gcloud_beta_debug_logpoints_list -l all-users
complete -c gcloud_beta_debug_logpoints_list -l location
complete -c gcloud_beta_debug_logpoints_list -l target
complete -c gcloud_beta_debug_logpoints_list -l filter
complete -c gcloud_beta_debug_logpoints_list -l sort-by -l limit
complete -c gcloud_beta_debug_logpoints_list -l flatten -d 'GCLOUD WIDE FLAGS'
complete -c gcloud_beta_debug_logpoints_list -l configuration -l flags-file -l format -l help
complete -c gcloud_beta_debug_logpoints_list -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_debug_logpoints_list -l trace-token -l user-output-enabled -l verbosity

