# gcloud_alpha_compute_instance-groups_get-named-ports
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_compute_instance-groups_get-named-ports.1.gz
complete -c gcloud_alpha_compute_instance-groups_get-named-ports -l region
complete -c gcloud_alpha_compute_instance-groups_get-named-ports -l zone
complete -c gcloud_alpha_compute_instance-groups_get-named-ports -l filter
complete -c gcloud_alpha_compute_instance-groups_get-named-ports -l sort-by -l limit
complete -c gcloud_alpha_compute_instance-groups_get-named-ports -l page-size
complete -c gcloud_alpha_compute_instance-groups_get-named-ports -l flatten
complete -c gcloud_alpha_compute_instance-groups_get-named-ports -l uri
complete -c gcloud_alpha_compute_instance-groups_get-named-ports -l configuration -l flags-file -l format -l help
complete -c gcloud_alpha_compute_instance-groups_get-named-ports -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_compute_instance-groups_get-named-ports -l trace-token -l user-output-enabled -l verbosity

