# gcloud_alpha_compute_instances_get-shielded-identity
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_compute_instances_get-shielded-identity.1.gz
complete -c gcloud_alpha_compute_instances_get-shielded-identity -l zone
complete -c gcloud_alpha_compute_instances_get-shielded-identity -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_compute_instances_get-shielded-identity -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_compute_instances_get-shielded-identity -l trace-token -l user-output-enabled -l verbosity

