# gcloud_alpha_dns_response-policies_rules_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_dns_response-policies_rules_update.1.gz
complete -c gcloud_alpha_dns_response-policies_rules_update -l response-policy
complete -c gcloud_alpha_dns_response-policies_rules_update -l behavior
complete -c gcloud_alpha_dns_response-policies_rules_update -l dns-name
complete -c gcloud_alpha_dns_response-policies_rules_update -l local-data
complete -c gcloud_alpha_dns_response-policies_rules_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_dns_response-policies_rules_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_dns_response-policies_rules_update -l trace-token -l user-output-enabled -l verbosity

