# gcloud_alpha_recommender_insights_mark-accepted
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_recommender_insights_mark-accepted.1.gz
complete -c gcloud_alpha_recommender_insights_mark-accepted -l etag
complete -c gcloud_alpha_recommender_insights_mark-accepted -l insight-type
complete -c gcloud_alpha_recommender_insights_mark-accepted -l location
complete -c gcloud_alpha_recommender_insights_mark-accepted -l organization
complete -c gcloud_alpha_recommender_insights_mark-accepted -l billing-account
complete -c gcloud_alpha_recommender_insights_mark-accepted -l folder
complete -c gcloud_alpha_recommender_insights_mark-accepted -l project
complete -c gcloud_alpha_recommender_insights_mark-accepted -l state-metadata
complete -c gcloud_alpha_recommender_insights_mark-accepted -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_recommender_insights_mark-accepted -l impersonate-service-account -l log-http -l quiet
complete -c gcloud_alpha_recommender_insights_mark-accepted -l trace-token -l user-output-enabled -l verbosity

