# gcloud_topic_flags-file
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_topic_flags-file.1.gz
complete -c gcloud_topic_flags-file -l flags-file -d 'using any command interpreter'

