# gcloud_alpha_web-security-scanner_scan-configs_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_web-security-scanner_scan-configs_create.1.gz
complete -c gcloud_alpha_web-security-scanner_scan-configs_create -l display-name
complete -c gcloud_alpha_web-security-scanner_scan-configs_create -l starting-urls
complete -c gcloud_alpha_web-security-scanner_scan-configs_create -l blacklist-patterns
complete -c gcloud_alpha_web-security-scanner_scan-configs_create -l export-to-security-center
complete -c gcloud_alpha_web-security-scanner_scan-configs_create -l no-export-to-security-center
complete -c gcloud_alpha_web-security-scanner_scan-configs_create -l max-qps
complete -c gcloud_alpha_web-security-scanner_scan-configs_create -l risk-level
complete -c gcloud_alpha_web-security-scanner_scan-configs_create -l target-platforms
complete -c gcloud_alpha_web-security-scanner_scan-configs_create -l user-agent
complete -c gcloud_alpha_web-security-scanner_scan-configs_create -l auth-password
complete -c gcloud_alpha_web-security-scanner_scan-configs_create -l auth-type
complete -c gcloud_alpha_web-security-scanner_scan-configs_create -l auth-url
complete -c gcloud_alpha_web-security-scanner_scan-configs_create -l auth-user
complete -c gcloud_alpha_web-security-scanner_scan-configs_create -l schedule-interval-days
complete -c gcloud_alpha_web-security-scanner_scan-configs_create -l schedule-next-start
complete -c gcloud_alpha_web-security-scanner_scan-configs_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_web-security-scanner_scan-configs_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_web-security-scanner_scan-configs_create -l trace-token -l user-output-enabled -l verbosity

