# gcloud_alpha_ml_vision_product-search_products_delete-all
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_ml_vision_product-search_products_delete-all.1.gz
complete -c gcloud_alpha_ml_vision_product-search_products_delete-all -l orphan-products
complete -c gcloud_alpha_ml_vision_product-search_products_delete-all -l product-set
complete -c gcloud_alpha_ml_vision_product-search_products_delete-all -l force
complete -c gcloud_alpha_ml_vision_product-search_products_delete-all -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_ml_vision_product-search_products_delete-all -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_ml_vision_product-search_products_delete-all -l trace-token -l user-output-enabled -l verbosity

