# gcloud_beta_dataproc_workflow-templates_add-job_spark-sql
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_dataproc_workflow-templates_add-job_spark-sql.1.gz
complete -c gcloud_beta_dataproc_workflow-templates_add-job_spark-sql -l step-id
complete -c gcloud_beta_dataproc_workflow-templates_add-job_spark-sql -l execute -s e
complete -c gcloud_beta_dataproc_workflow-templates_add-job_spark-sql -l file -s f
complete -c gcloud_beta_dataproc_workflow-templates_add-job_spark-sql -l workflow-template
complete -c gcloud_beta_dataproc_workflow-templates_add-job_spark-sql -l region
complete -c gcloud_beta_dataproc_workflow-templates_add-job_spark-sql -l driver-log-levels
complete -c gcloud_beta_dataproc_workflow-templates_add-job_spark-sql -l jars
complete -c gcloud_beta_dataproc_workflow-templates_add-job_spark-sql -l labels
complete -c gcloud_beta_dataproc_workflow-templates_add-job_spark-sql -l params
complete -c gcloud_beta_dataproc_workflow-templates_add-job_spark-sql -l properties
complete -c gcloud_beta_dataproc_workflow-templates_add-job_spark-sql -l start-after
complete -c gcloud_beta_dataproc_workflow-templates_add-job_spark-sql -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_dataproc_workflow-templates_add-job_spark-sql -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_dataproc_workflow-templates_add-job_spark-sql -l trace-token -l user-output-enabled -l verbosity

