# gcloud_beta_compute_shared-vpc_associated-projects_add
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_compute_shared-vpc_associated-projects_add.1.gz
complete -c gcloud_beta_compute_shared-vpc_associated-projects_add -l host-project
complete -c gcloud_beta_compute_shared-vpc_associated-projects_add -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_compute_shared-vpc_associated-projects_add -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_compute_shared-vpc_associated-projects_add -l trace-token -l user-output-enabled -l verbosity

