# gcloud_alpha_network-connectivity_spokes_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_network-connectivity_spokes_create.1.gz
complete -c gcloud_alpha_network-connectivity_spokes_create -l region
complete -c gcloud_alpha_network-connectivity_spokes_create -l hub
complete -c gcloud_alpha_network-connectivity_spokes_create -l interconnect-attachment
complete -c gcloud_alpha_network-connectivity_spokes_create -l router-appliance
complete -c gcloud_alpha_network-connectivity_spokes_create -l vpn-tunnel
complete -c gcloud_alpha_network-connectivity_spokes_create -l async
complete -c gcloud_alpha_network-connectivity_spokes_create -l description
complete -c gcloud_alpha_network-connectivity_spokes_create -l labels
complete -c gcloud_alpha_network-connectivity_spokes_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_network-connectivity_spokes_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_network-connectivity_spokes_create -l trace-token -l user-output-enabled -l verbosity

