# gcloud_alpha_auth_revoke
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_auth_revoke.1.gz
complete -c gcloud_alpha_auth_revoke -l all
complete -c gcloud_alpha_auth_revoke -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_auth_revoke -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_auth_revoke -l trace-token -l user-output-enabled -l verbosity

