# gcloud_beta_app_migrate-config_dispatch-xml-to-yaml
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_app_migrate-config_dispatch-xml-to-yaml.1.gz
complete -c gcloud_beta_app_migrate-config_dispatch-xml-to-yaml -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_app_migrate-config_dispatch-xml-to-yaml -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_app_migrate-config_dispatch-xml-to-yaml -l trace-token -l user-output-enabled -l verbosity

