# gcloud_beta_metastore_services_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_metastore_services_create.1.gz
complete -c gcloud_beta_metastore_services_create -l location
complete -c gcloud_beta_metastore_services_create -l async
complete -c gcloud_beta_metastore_services_create -l data-catalog-sync
complete -c gcloud_beta_metastore_services_create -l hive-metastore-version
complete -c gcloud_beta_metastore_services_create -l labels
complete -c gcloud_beta_metastore_services_create -l network
complete -c gcloud_beta_metastore_services_create -l port
complete -c gcloud_beta_metastore_services_create -l release-channel
complete -c gcloud_beta_metastore_services_create -l tier
complete -c gcloud_beta_metastore_services_create -l hive-metastore-configs
complete -c gcloud_beta_metastore_services_create -l hive-metastore-configs-from-file
complete -c gcloud_beta_metastore_services_create -l kerberos-principal
complete -c gcloud_beta_metastore_services_create -l keytab
complete -c gcloud_beta_metastore_services_create -l krb5-config
complete -c gcloud_beta_metastore_services_create -l maintenance-window-day
complete -c gcloud_beta_metastore_services_create -l maintenance-window-hour
complete -c gcloud_beta_metastore_services_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_metastore_services_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_metastore_services_create -l trace-token -l user-output-enabled -l verbosity

