# gcloud_beta_asset_feeds_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_asset_feeds_update.1.gz
complete -c gcloud_beta_asset_feeds_update -l add-asset-types -d 'POSITIONAL ARGUMENTS FEED_ID'
complete -c gcloud_beta_asset_feeds_update -l folder
complete -c gcloud_beta_asset_feeds_update -l organization
complete -c gcloud_beta_asset_feeds_update -l project
complete -c gcloud_beta_asset_feeds_update -l pubsub-topic
complete -c gcloud_beta_asset_feeds_update -l add-asset-names
complete -c gcloud_beta_asset_feeds_update -l clear-asset-names
complete -c gcloud_beta_asset_feeds_update -l remove-asset-names
complete -c gcloud_beta_asset_feeds_update -l clear-asset-types
complete -c gcloud_beta_asset_feeds_update -l remove-asset-types
complete -c gcloud_beta_asset_feeds_update -l clear-condition-description
complete -c gcloud_beta_asset_feeds_update -l condition-description
complete -c gcloud_beta_asset_feeds_update -l clear-condition-expression
complete -c gcloud_beta_asset_feeds_update -l condition-expression
complete -c gcloud_beta_asset_feeds_update -l clear-condition-title
complete -c gcloud_beta_asset_feeds_update -l condition-title
complete -c gcloud_beta_asset_feeds_update -l clear-content-type
complete -c gcloud_beta_asset_feeds_update -l content-type
complete -c gcloud_beta_asset_feeds_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_asset_feeds_update -l impersonate-service-account -l log-http -l quiet
complete -c gcloud_beta_asset_feeds_update -l trace-token -l user-output-enabled -l verbosity

