# gcloud_alpha_kms_import-jobs_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_kms_import-jobs_create.1.gz
complete -c gcloud_alpha_kms_import-jobs_create -l import-method
complete -c gcloud_alpha_kms_import-jobs_create -l protection-level
complete -c gcloud_alpha_kms_import-jobs_create -l keyring
complete -c gcloud_alpha_kms_import-jobs_create -l location
complete -c gcloud_alpha_kms_import-jobs_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_kms_import-jobs_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_kms_import-jobs_create -l trace-token -l user-output-enabled -l verbosity

