# gcloud_beta_dataproc_workflow-templates_add-job_hadoop
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_dataproc_workflow-templates_add-job_hadoop.1.gz
complete -c gcloud_beta_dataproc_workflow-templates_add-job_hadoop -l step-id
complete -c gcloud_beta_dataproc_workflow-templates_add-job_hadoop -l class
complete -c gcloud_beta_dataproc_workflow-templates_add-job_hadoop -l jar
complete -c gcloud_beta_dataproc_workflow-templates_add-job_hadoop -l workflow-template
complete -c gcloud_beta_dataproc_workflow-templates_add-job_hadoop -l region
complete -c gcloud_beta_dataproc_workflow-templates_add-job_hadoop -l archives
complete -c gcloud_beta_dataproc_workflow-templates_add-job_hadoop -l driver-log-levels
complete -c gcloud_beta_dataproc_workflow-templates_add-job_hadoop -l files
complete -c gcloud_beta_dataproc_workflow-templates_add-job_hadoop -l jars
complete -c gcloud_beta_dataproc_workflow-templates_add-job_hadoop -l labels
complete -c gcloud_beta_dataproc_workflow-templates_add-job_hadoop -l properties
complete -c gcloud_beta_dataproc_workflow-templates_add-job_hadoop -l start-after
complete -c gcloud_beta_dataproc_workflow-templates_add-job_hadoop -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_dataproc_workflow-templates_add-job_hadoop -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_dataproc_workflow-templates_add-job_hadoop -l trace-token -l user-output-enabled -l verbosity

