# gcloud_beta_service-directory_endpoints_delete
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_service-directory_endpoints_delete.1.gz
complete -c gcloud_beta_service-directory_endpoints_delete -l location
complete -c gcloud_beta_service-directory_endpoints_delete -l namespace
complete -c gcloud_beta_service-directory_endpoints_delete -l service
complete -c gcloud_beta_service-directory_endpoints_delete -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_service-directory_endpoints_delete -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_service-directory_endpoints_delete -l trace-token -l user-output-enabled -l verbosity

