# gcloud_alpha_projects_get-ancestors
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_projects_get-ancestors.1.gz
complete -c gcloud_alpha_projects_get-ancestors -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_projects_get-ancestors -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_projects_get-ancestors -l trace-token -l user-output-enabled -l verbosity

