# gcloud_alpha_network-connectivity_hubs_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_network-connectivity_hubs_update.1.gz
complete -c gcloud_alpha_network-connectivity_hubs_update -l async
complete -c gcloud_alpha_network-connectivity_hubs_update -l description
complete -c gcloud_alpha_network-connectivity_hubs_update -l labels
complete -c gcloud_alpha_network-connectivity_hubs_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_network-connectivity_hubs_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_network-connectivity_hubs_update -l trace-token -l user-output-enabled -l verbosity

