# gcloud_alpha_resource-manager_tags_bindings_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_resource-manager_tags_bindings_create.1.gz
complete -c gcloud_alpha_resource-manager_tags_bindings_create -l parent
complete -c gcloud_alpha_resource-manager_tags_bindings_create -l tag-value
complete -c gcloud_alpha_resource-manager_tags_bindings_create -l async
complete -c gcloud_alpha_resource-manager_tags_bindings_create -l location
complete -c gcloud_alpha_resource-manager_tags_bindings_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_resource-manager_tags_bindings_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_resource-manager_tags_bindings_create -l trace-token -l user-output-enabled -l verbosity

