# gcloud_alpha_ai_index-endpoints_deploy-index
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_ai_index-endpoints_deploy-index.1.gz
complete -c gcloud_alpha_ai_index-endpoints_deploy-index -l region
complete -c gcloud_alpha_ai_index-endpoints_deploy-index -l deployed-index-id
complete -c gcloud_alpha_ai_index-endpoints_deploy-index -l display-name
complete -c gcloud_alpha_ai_index-endpoints_deploy-index -l index
complete -c gcloud_alpha_ai_index-endpoints_deploy-index -l max-replica-count
complete -c gcloud_alpha_ai_index-endpoints_deploy-index -l min-replica-count
complete -c gcloud_alpha_ai_index-endpoints_deploy-index -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_ai_index-endpoints_deploy-index -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_ai_index-endpoints_deploy-index -l trace-token -l user-output-enabled -l verbosity

