# gcloud_alpha_kms_encrypt
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_kms_encrypt.1.gz
complete -c gcloud_alpha_kms_encrypt -l ciphertext-file
complete -c gcloud_alpha_kms_encrypt -l plaintext-file
complete -c gcloud_alpha_kms_encrypt -l additional-authenticated-data-file
complete -c gcloud_alpha_kms_encrypt -l key
complete -c gcloud_alpha_kms_encrypt -l keyring
complete -c gcloud_alpha_kms_encrypt -l location
complete -c gcloud_alpha_kms_encrypt -l skip-integrity-verification
complete -c gcloud_alpha_kms_encrypt -l version
complete -c gcloud_alpha_kms_encrypt -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_kms_encrypt -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_kms_encrypt -l trace-token -l user-output-enabled -l verbosity

