# gcloud_beta_filestore_instances_restore
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_filestore_instances_restore.1.gz
complete -c gcloud_beta_filestore_instances_restore -l zone
complete -c gcloud_beta_filestore_instances_restore -l file-share
complete -c gcloud_beta_filestore_instances_restore -l source-backup
complete -c gcloud_beta_filestore_instances_restore -l source-backup-region
complete -c gcloud_beta_filestore_instances_restore -l async
complete -c gcloud_beta_filestore_instances_restore -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_filestore_instances_restore -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_filestore_instances_restore -l trace-token -l user-output-enabled -l verbosity

