# gcloud_beta_composer_environments_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_composer_environments_update.1.gz
complete -c gcloud_beta_composer_environments_update -l location
complete -c gcloud_beta_composer_environments_update -l cloud-sql-machine-type
complete -c gcloud_beta_composer_environments_update -l node-count
complete -c gcloud_beta_composer_environments_update -l web-server-machine-type
complete -c gcloud_beta_composer_environments_update -l airflow-version
complete -c gcloud_beta_composer_environments_update -l image-version
complete -c gcloud_beta_composer_environments_update -l maintenance-window-end
complete -c gcloud_beta_composer_environments_update -l maintenance-window-recurrence
complete -c gcloud_beta_composer_environments_update -l maintenance-window-start
complete -c gcloud_beta_composer_environments_update -l update-airflow-configs
complete -c gcloud_beta_composer_environments_update -l clear-airflow-configs
complete -c gcloud_beta_composer_environments_update -l remove-airflow-configs
complete -c gcloud_beta_composer_environments_update -l update-env-variables
complete -c gcloud_beta_composer_environments_update -l clear-env-variables
complete -c gcloud_beta_composer_environments_update -l remove-env-variables
complete -c gcloud_beta_composer_environments_update -l update-labels
complete -c gcloud_beta_composer_environments_update -l clear-labels
complete -c gcloud_beta_composer_environments_update -l remove-labels
complete -c gcloud_beta_composer_environments_update -l update-pypi-packages-from-file
complete -c gcloud_beta_composer_environments_update -l update-pypi-package
complete -c gcloud_beta_composer_environments_update -l clear-pypi-packages
complete -c gcloud_beta_composer_environments_update -l remove-pypi-packages
complete -c gcloud_beta_composer_environments_update -l update-web-server-allow-ip
complete -c gcloud_beta_composer_environments_update -l web-server-allow-all
complete -c gcloud_beta_composer_environments_update -l web-server-deny-all
complete -c gcloud_beta_composer_environments_update -l async
complete -c gcloud_beta_composer_environments_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_composer_environments_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_composer_environments_update -l trace-token -l user-output-enabled -l verbosity

