# gcloud_healthcare_dicom-stores_deidentify
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_healthcare_dicom-stores_deidentify.1.gz
complete -c gcloud_healthcare_dicom-stores_deidentify -l dataset
complete -c gcloud_healthcare_dicom-stores_deidentify -l location
complete -c gcloud_healthcare_dicom-stores_deidentify -l destination-store
complete -c gcloud_healthcare_dicom-stores_deidentify -l async
complete -c gcloud_healthcare_dicom-stores_deidentify -l dicom-filter-tags
complete -c gcloud_healthcare_dicom-stores_deidentify -l text-redaction-mode
complete -c gcloud_healthcare_dicom-stores_deidentify -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_healthcare_dicom-stores_deidentify -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_healthcare_dicom-stores_deidentify -l trace-token -l user-output-enabled -l verbosity

