# gcloud_beta_compute_instance-groups_managed_list-instances
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_compute_instance-groups_managed_list-instances.1.gz
complete -c gcloud_beta_compute_instance-groups_managed_list-instances -l region
complete -c gcloud_beta_compute_instance-groups_managed_list-instances -l zone
complete -c gcloud_beta_compute_instance-groups_managed_list-instances -l filter
complete -c gcloud_beta_compute_instance-groups_managed_list-instances -l sort-by -l limit
complete -c gcloud_beta_compute_instance-groups_managed_list-instances -l page-size
complete -c gcloud_beta_compute_instance-groups_managed_list-instances -l flatten
complete -c gcloud_beta_compute_instance-groups_managed_list-instances -l uri
complete -c gcloud_beta_compute_instance-groups_managed_list-instances -l configuration -l flags-file -l format -l help
complete -c gcloud_beta_compute_instance-groups_managed_list-instances -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_compute_instance-groups_managed_list-instances -l trace-token -l user-output-enabled -l verbosity

