# gcloud_alpha_deploy_releases_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_deploy_releases_create.1.gz
complete -c gcloud_alpha_deploy_releases_create -l delivery-pipeline
complete -c gcloud_alpha_deploy_releases_create -l region
complete -c gcloud_alpha_deploy_releases_create -l description
complete -c gcloud_alpha_deploy_releases_create -l gcs-render-dir
complete -c gcloud_alpha_deploy_releases_create -l gcs-source-staging-dir
complete -c gcloud_alpha_deploy_releases_create -l ignore-file
complete -c gcloud_alpha_deploy_releases_create -l source
complete -c gcloud_alpha_deploy_releases_create -l to-target
complete -c gcloud_alpha_deploy_releases_create -l build-artifacts
complete -c gcloud_alpha_deploy_releases_create -l images
complete -c gcloud_alpha_deploy_releases_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_deploy_releases_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_deploy_releases_create -l trace-token -l user-output-enabled -l verbosity

