# gcloud_alpha_compute_shared-vpc_get-host-project
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_compute_shared-vpc_get-host-project.1.gz
complete -c gcloud_alpha_compute_shared-vpc_get-host-project -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_compute_shared-vpc_get-host-project -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_compute_shared-vpc_get-host-project -l trace-token -l user-output-enabled -l verbosity

