# gcloud_alpha_asset_feeds_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_asset_feeds_create.1.gz
complete -c gcloud_alpha_asset_feeds_create -l asset-types
complete -c gcloud_alpha_asset_feeds_create -l content-type -l pubsub-topic -d 'POSITIONAL ARGUMENTS FEED_ID'
complete -c gcloud_alpha_asset_feeds_create -l asset-names
complete -c gcloud_alpha_asset_feeds_create -l folder
complete -c gcloud_alpha_asset_feeds_create -l organization
complete -c gcloud_alpha_asset_feeds_create -l project
complete -c gcloud_alpha_asset_feeds_create -l condition-description
complete -c gcloud_alpha_asset_feeds_create -l condition-expression
complete -c gcloud_alpha_asset_feeds_create -l condition-title
complete -c gcloud_alpha_asset_feeds_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_asset_feeds_create -l impersonate-service-account -l log-http -l quiet
complete -c gcloud_alpha_asset_feeds_create -l trace-token -l user-output-enabled -l verbosity

