# gcloud_deployment-manager_deployments_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_deployment-manager_deployments_create.1.gz
complete -c gcloud_deployment-manager_deployments_create -l composite-type
complete -c gcloud_deployment-manager_deployments_create -l config
complete -c gcloud_deployment-manager_deployments_create -l template
complete -c gcloud_deployment-manager_deployments_create -l description
complete -c gcloud_deployment-manager_deployments_create -l labels
complete -c gcloud_deployment-manager_deployments_create -l preview
complete -c gcloud_deployment-manager_deployments_create -l properties
complete -c gcloud_deployment-manager_deployments_create -l async
complete -c gcloud_deployment-manager_deployments_create -l automatic-rollback-on-error
complete -c gcloud_deployment-manager_deployments_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_deployment-manager_deployments_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_deployment-manager_deployments_create -l trace-token -l user-output-enabled -l verbosity

