# gcloud_alpha_dlp_text_redact
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_dlp_text_redact.1.gz
complete -c gcloud_alpha_dlp_text_redact -l info-types
complete -c gcloud_alpha_dlp_text_redact -l content
complete -c gcloud_alpha_dlp_text_redact -l content-file
complete -c gcloud_alpha_dlp_text_redact -l remove-findings
complete -c gcloud_alpha_dlp_text_redact -l replace-with-info-type
complete -c gcloud_alpha_dlp_text_redact -l replacement-text
complete -c gcloud_alpha_dlp_text_redact -l min-likelihood
complete -c gcloud_alpha_dlp_text_redact -l output-file
complete -c gcloud_alpha_dlp_text_redact -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_dlp_text_redact -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_dlp_text_redact -l trace-token -l user-output-enabled -l verbosity

