# gcloud_dataproc_workflow-templates_set-dag-timeout
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_dataproc_workflow-templates_set-dag-timeout.1.gz
complete -c gcloud_dataproc_workflow-templates_set-dag-timeout -l region
complete -c gcloud_dataproc_workflow-templates_set-dag-timeout -l dag-timeout
complete -c gcloud_dataproc_workflow-templates_set-dag-timeout -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_dataproc_workflow-templates_set-dag-timeout -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_dataproc_workflow-templates_set-dag-timeout -l trace-token -l user-output-enabled -l verbosity

