# gcloud_alpha_data-catalog_entries_lookup
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_data-catalog_entries_lookup.1.gz
complete -c gcloud_alpha_data-catalog_entries_lookup -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_data-catalog_entries_lookup -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_data-catalog_entries_lookup -l trace-token -l user-output-enabled -l verbosity

