# gcloud_dataflow_flex-template_run
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_dataflow_flex-template_run.1.gz
complete -c gcloud_dataflow_flex-template_run -l template-file-gcs-location
complete -c gcloud_dataflow_flex-template_run -l additional-experiments
complete -c gcloud_dataflow_flex-template_run -l additional-user-labels
complete -c gcloud_dataflow_flex-template_run -l dataflow-kms-key
complete -c gcloud_dataflow_flex-template_run -l disable-public-ips
complete -c gcloud_dataflow_flex-template_run -l enable-streaming-engine
complete -c gcloud_dataflow_flex-template_run -l flexrs-goal
complete -c gcloud_dataflow_flex-template_run -l max-workers
complete -c gcloud_dataflow_flex-template_run -l network
complete -c gcloud_dataflow_flex-template_run -l num-workers
complete -c gcloud_dataflow_flex-template_run -l parameters
complete -c gcloud_dataflow_flex-template_run -l region
complete -c gcloud_dataflow_flex-template_run -l service-account-email
complete -c gcloud_dataflow_flex-template_run -l staging-location
complete -c gcloud_dataflow_flex-template_run -l subnetwork
complete -c gcloud_dataflow_flex-template_run -l worker-machine-type
complete -c gcloud_dataflow_flex-template_run -l update
complete -c gcloud_dataflow_flex-template_run -l no-update
complete -c gcloud_dataflow_flex-template_run -l transform-name-mappings
complete -c gcloud_dataflow_flex-template_run -l worker-region
complete -c gcloud_dataflow_flex-template_run -l worker-zone
complete -c gcloud_dataflow_flex-template_run -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_dataflow_flex-template_run -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_dataflow_flex-template_run -l trace-token -l user-output-enabled -l verbosity

