# gcloud_beta_debug_snapshots_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_debug_snapshots_create.1.gz
complete -c gcloud_beta_debug_snapshots_create -l condition
complete -c gcloud_beta_debug_snapshots_create -l expression
complete -c gcloud_beta_debug_snapshots_create -l target
complete -c gcloud_beta_debug_snapshots_create -l wait
complete -c gcloud_beta_debug_snapshots_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_debug_snapshots_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_debug_snapshots_create -l trace-token -l user-output-enabled -l verbosity

