# gcloud_beta_compute_sole-tenancy_node-groups_list-nodes
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_compute_sole-tenancy_node-groups_list-nodes.1.gz
complete -c gcloud_beta_compute_sole-tenancy_node-groups_list-nodes -l zone
complete -c gcloud_beta_compute_sole-tenancy_node-groups_list-nodes -l filter
complete -c gcloud_beta_compute_sole-tenancy_node-groups_list-nodes -l sort-by -l limit
complete -c gcloud_beta_compute_sole-tenancy_node-groups_list-nodes -l page-size
complete -c gcloud_beta_compute_sole-tenancy_node-groups_list-nodes -l flatten -d 'GCLOUD WIDE FLAGS'
complete -c gcloud_beta_compute_sole-tenancy_node-groups_list-nodes -l configuration -l flags-file -l format -l help
complete -c gcloud_beta_compute_sole-tenancy_node-groups_list-nodes -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_compute_sole-tenancy_node-groups_list-nodes -l trace-token -l user-output-enabled -l verbosity

