# gcloud_beta_runtime-config_configs_variables_get-value
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_runtime-config_configs_variables_get-value.1.gz
complete -c gcloud_beta_runtime-config_configs_variables_get-value -l config-name
complete -c gcloud_beta_runtime-config_configs_variables_get-value -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_runtime-config_configs_variables_get-value -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_runtime-config_configs_variables_get-value -l trace-token -l user-output-enabled -l verbosity

