# gcloud_beta_compute_config-ssh
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_compute_config-ssh.1.gz
complete -c gcloud_beta_compute_config-ssh -l dry-run
complete -c gcloud_beta_compute_config-ssh -l force-key-file-overwrite
complete -c gcloud_beta_compute_config-ssh -l remove
complete -c gcloud_beta_compute_config-ssh -l ssh-config-file
complete -c gcloud_beta_compute_config-ssh -l ssh-key-file
complete -c gcloud_beta_compute_config-ssh -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_compute_config-ssh -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_compute_config-ssh -l trace-token -l user-output-enabled -l verbosity

