# gcloud_alpha_compute_url-maps_describe
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_compute_url-maps_describe.1.gz
complete -c gcloud_alpha_compute_url-maps_describe -l global
complete -c gcloud_alpha_compute_url-maps_describe -l region
complete -c gcloud_alpha_compute_url-maps_describe -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_compute_url-maps_describe -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_compute_url-maps_describe -l trace-token -l user-output-enabled -l verbosity

