# gcloud_alpha_iam_roles_list
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_iam_roles_list.1.gz
complete -c gcloud_alpha_iam_roles_list -l show-deleted
complete -c gcloud_alpha_iam_roles_list -l organization
complete -c gcloud_alpha_iam_roles_list -l project
complete -c gcloud_alpha_iam_roles_list -l filter
complete -c gcloud_alpha_iam_roles_list -l sort-by -l limit
complete -c gcloud_alpha_iam_roles_list -l flatten -d 'GCLOUD WIDE FLAGS'
complete -c gcloud_alpha_iam_roles_list -l configuration -l flags-file -l format -l help
complete -c gcloud_alpha_iam_roles_list -l impersonate-service-account -l log-http -l quiet
complete -c gcloud_alpha_iam_roles_list -l trace-token -l user-output-enabled -l verbosity

