# gcloud_beta_iot_registries_credentials_clear
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_iot_registries_credentials_clear.1.gz
complete -c gcloud_beta_iot_registries_credentials_clear -l registry
complete -c gcloud_beta_iot_registries_credentials_clear -l region
complete -c gcloud_beta_iot_registries_credentials_clear -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_iot_registries_credentials_clear -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_iot_registries_credentials_clear -l trace-token -l user-output-enabled -l verbosity

