# gcloud_tasks_queues_purge
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_tasks_queues_purge.1.gz
complete -c gcloud_tasks_queues_purge -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_tasks_queues_purge -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_tasks_queues_purge -l trace-token -l user-output-enabled -l verbosity

