# gcloud_beta_access-context-manager_perimeters_dry-run_list
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_access-context-manager_perimeters_dry-run_list.1.gz
complete -c gcloud_beta_access-context-manager_perimeters_dry-run_list -l - -d 'name: perimeter_2 spec:   resources:   - projects/789   restrictedServices:  …'
complete -c gcloud_beta_access-context-manager_perimeters_dry-run_list -l policy
complete -c gcloud_beta_access-context-manager_perimeters_dry-run_list -l filter
complete -c gcloud_beta_access-context-manager_perimeters_dry-run_list -l sort-by -l limit
complete -c gcloud_beta_access-context-manager_perimeters_dry-run_list -l page-size
complete -c gcloud_beta_access-context-manager_perimeters_dry-run_list -l flatten -d 'GCLOUD WIDE FLAGS'
complete -c gcloud_beta_access-context-manager_perimeters_dry-run_list -l configuration -l flags-file -l format -l help
complete -c gcloud_beta_access-context-manager_perimeters_dry-run_list -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_access-context-manager_perimeters_dry-run_list -l trace-token -l user-output-enabled -l verbosity

