# gcloud_beta_services_peered-dns-domains_list
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_services_peered-dns-domains_list.1.gz
complete -c gcloud_beta_services_peered-dns-domains_list -l network
complete -c gcloud_beta_services_peered-dns-domains_list -l service
complete -c gcloud_beta_services_peered-dns-domains_list -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_services_peered-dns-domains_list -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_services_peered-dns-domains_list -l trace-token -l user-output-enabled -l verbosity

