# gcloud_beta_pubsub_subscriptions_pull
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_pubsub_subscriptions_pull.1.gz
complete -c gcloud_beta_pubsub_subscriptions_pull -l limit
complete -c gcloud_beta_pubsub_subscriptions_pull -l auto-ack
complete -c gcloud_beta_pubsub_subscriptions_pull -l max-messages
complete -c gcloud_beta_pubsub_subscriptions_pull -l wait
complete -c gcloud_beta_pubsub_subscriptions_pull -l filter
complete -c gcloud_beta_pubsub_subscriptions_pull -l sort-by
complete -c gcloud_beta_pubsub_subscriptions_pull -l page-size
complete -c gcloud_beta_pubsub_subscriptions_pull -l flatten
complete -c gcloud_beta_pubsub_subscriptions_pull -l uri
complete -c gcloud_beta_pubsub_subscriptions_pull -l configuration -l flags-file -l format -l help
complete -c gcloud_beta_pubsub_subscriptions_pull -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_pubsub_subscriptions_pull -l trace-token -l user-output-enabled -l verbosity

