# gcloud_beta_kms_keys_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_kms_keys_update.1.gz
complete -c gcloud_beta_kms_keys_update -l keyring
complete -c gcloud_beta_kms_keys_update -l location
complete -c gcloud_beta_kms_keys_update -l default-algorithm
complete -c gcloud_beta_kms_keys_update -l next-rotation-time
complete -c gcloud_beta_kms_keys_update -l primary-version
complete -c gcloud_beta_kms_keys_update -l remove-rotation-schedule
complete -c gcloud_beta_kms_keys_update -l rotation-period
complete -c gcloud_beta_kms_keys_update -l update-labels
complete -c gcloud_beta_kms_keys_update -l clear-labels
complete -c gcloud_beta_kms_keys_update -l remove-labels
complete -c gcloud_beta_kms_keys_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_kms_keys_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_kms_keys_update -l trace-token -l user-output-enabled -l verbosity

