# gcloud_beta_app_logs_read
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_app_logs_read.1.gz
complete -c gcloud_beta_app_logs_read -l level
complete -c gcloud_beta_app_logs_read -l limit
complete -c gcloud_beta_app_logs_read -l logs
complete -c gcloud_beta_app_logs_read -l service -s s
complete -c gcloud_beta_app_logs_read -l version -s v
complete -c gcloud_beta_app_logs_read -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_app_logs_read -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_app_logs_read -l trace-token -l user-output-enabled -l verbosity

