# gcloud_alpha_ml_vision_detect-text-pdf
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_ml_vision_detect-text-pdf.1.gz
complete -c gcloud_alpha_ml_vision_detect-text-pdf -l batch-size
complete -c gcloud_alpha_ml_vision_detect-text-pdf -l model-version
complete -c gcloud_alpha_ml_vision_detect-text-pdf -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_ml_vision_detect-text-pdf -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_ml_vision_detect-text-pdf -l trace-token -l user-output-enabled -l verbosity

