# gcloud_beta_iam_service-accounts_keys_get-public-key
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_iam_service-accounts_keys_get-public-key.1.gz
complete -c gcloud_beta_iam_service-accounts_keys_get-public-key -l iam-account
complete -c gcloud_beta_iam_service-accounts_keys_get-public-key -l output-file
complete -c gcloud_beta_iam_service-accounts_keys_get-public-key -l type
complete -c gcloud_beta_iam_service-accounts_keys_get-public-key -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_iam_service-accounts_keys_get-public-key -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_iam_service-accounts_keys_get-public-key -l trace-token -l user-output-enabled -l verbosity

