# gcloud_alpha_resource-settings_set-value
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_resource-settings_set-value.1.gz
complete -c gcloud_alpha_resource-settings_set-value -l value-file
complete -c gcloud_alpha_resource-settings_set-value -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_resource-settings_set-value -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_resource-settings_set-value -l trace-token -l user-output-enabled -l verbosity

