# gcloud_alpha_compute_instances_attach-disk
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_compute_instances_attach-disk.1.gz
complete -c gcloud_alpha_compute_instances_attach-disk -l disk
complete -c gcloud_alpha_compute_instances_attach-disk -l boot
complete -c gcloud_alpha_compute_instances_attach-disk -l csek-key-file
complete -c gcloud_alpha_compute_instances_attach-disk -l device-name
complete -c gcloud_alpha_compute_instances_attach-disk -l container-mount-disk
complete -c gcloud_alpha_compute_instances_attach-disk -l disk-scope
complete -c gcloud_alpha_compute_instances_attach-disk -l force-attach
complete -c gcloud_alpha_compute_instances_attach-disk -l mode
complete -c gcloud_alpha_compute_instances_attach-disk -l zone
complete -c gcloud_alpha_compute_instances_attach-disk -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_compute_instances_attach-disk -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_compute_instances_attach-disk -l trace-token -l user-output-enabled -l verbosity

