# gcloud_beta_iot_devices_credentials_list
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_iot_devices_credentials_list.1.gz
complete -c gcloud_beta_iot_devices_credentials_list -l device
complete -c gcloud_beta_iot_devices_credentials_list -l region
complete -c gcloud_beta_iot_devices_credentials_list -l registry
complete -c gcloud_beta_iot_devices_credentials_list -l filter
complete -c gcloud_beta_iot_devices_credentials_list -l sort-by -l limit
complete -c gcloud_beta_iot_devices_credentials_list -l flatten -d 'GCLOUD WIDE FLAGS'
complete -c gcloud_beta_iot_devices_credentials_list -l configuration -l flags-file -l format -l help
complete -c gcloud_beta_iot_devices_credentials_list -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_iot_devices_credentials_list -l trace-token -l user-output-enabled -l verbosity

