# gcloud_beta_privateca_certificates_describe
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_privateca_certificates_describe.1.gz
complete -c gcloud_beta_privateca_certificates_describe -l issuer
complete -c gcloud_beta_privateca_certificates_describe -l issuer-location
complete -c gcloud_beta_privateca_certificates_describe -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_privateca_certificates_describe -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_privateca_certificates_describe -l trace-token -l user-output-enabled -l verbosity

