# gcloud_beta_functions_call
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_functions_call.1.gz
complete -c gcloud_beta_functions_call -l data -d '$ gcloud beta functions call helloWorld \\   --data=\'{"message": "Hello World!…'
complete -c gcloud_beta_functions_call -l region
complete -c gcloud_beta_functions_call -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_functions_call -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_functions_call -l trace-token -l user-output-enabled -l verbosity

