# gcloud_alpha_ai-platform_predict
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_ai-platform_predict.1.gz
complete -c gcloud_alpha_ai-platform_predict -l model
complete -c gcloud_alpha_ai-platform_predict -l json-instances
complete -c gcloud_alpha_ai-platform_predict -l json-request
complete -c gcloud_alpha_ai-platform_predict -l text-instances
complete -c gcloud_alpha_ai-platform_predict -l region
complete -c gcloud_alpha_ai-platform_predict -l signature-name
complete -c gcloud_alpha_ai-platform_predict -l version
complete -c gcloud_alpha_ai-platform_predict -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_ai-platform_predict -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_ai-platform_predict -l trace-token -l user-output-enabled -l verbosity

