# gcloud_alpha_scheduler_jobs_create_pubsub
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_scheduler_jobs_create_pubsub.1.gz
complete -c gcloud_alpha_scheduler_jobs_create_pubsub -l schedule
complete -c gcloud_alpha_scheduler_jobs_create_pubsub -l topic
complete -c gcloud_alpha_scheduler_jobs_create_pubsub -l message-body
complete -c gcloud_alpha_scheduler_jobs_create_pubsub -l message-body-from-file
complete -c gcloud_alpha_scheduler_jobs_create_pubsub -l attributes
complete -c gcloud_alpha_scheduler_jobs_create_pubsub -l description
complete -c gcloud_alpha_scheduler_jobs_create_pubsub -l max-backoff
complete -c gcloud_alpha_scheduler_jobs_create_pubsub -l max-doublings
complete -c gcloud_alpha_scheduler_jobs_create_pubsub -l max-retry-attempts
complete -c gcloud_alpha_scheduler_jobs_create_pubsub -l max-retry-duration
complete -c gcloud_alpha_scheduler_jobs_create_pubsub -l min-backoff
complete -c gcloud_alpha_scheduler_jobs_create_pubsub -l time-zone
complete -c gcloud_alpha_scheduler_jobs_create_pubsub -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_scheduler_jobs_create_pubsub -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_scheduler_jobs_create_pubsub -l trace-token -l user-output-enabled -l verbosity

