# gcloud_alpha_iam_service-accounts_sign-blob
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_iam_service-accounts_sign-blob.1.gz
complete -c gcloud_alpha_iam_service-accounts_sign-blob -l iam-account
complete -c gcloud_alpha_iam_service-accounts_sign-blob -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_iam_service-accounts_sign-blob -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_iam_service-accounts_sign-blob -l trace-token -l user-output-enabled -l verbosity

