# gcloud_beta_ai-platform_models_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_ai-platform_models_update.1.gz
complete -c gcloud_beta_ai-platform_models_update -l description
complete -c gcloud_beta_ai-platform_models_update -l region
complete -c gcloud_beta_ai-platform_models_update -l update-labels
complete -c gcloud_beta_ai-platform_models_update -l clear-labels
complete -c gcloud_beta_ai-platform_models_update -l remove-labels
complete -c gcloud_beta_ai-platform_models_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_ai-platform_models_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_ai-platform_models_update -l trace-token -l user-output-enabled -l verbosity

