# gcloud_alpha_notebooks_instances_delete
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_notebooks_instances_delete.1.gz
complete -c gcloud_alpha_notebooks_instances_delete -l location
complete -c gcloud_alpha_notebooks_instances_delete -l async
complete -c gcloud_alpha_notebooks_instances_delete -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_notebooks_instances_delete -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_notebooks_instances_delete -l trace-token -l user-output-enabled -l verbosity

