# gcloud_alpha_recommender_recommendations_mark-claimed
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_recommender_recommendations_mark-claimed.1.gz
complete -c gcloud_alpha_recommender_recommendations_mark-claimed -l recommender -l etag
complete -c gcloud_alpha_recommender_recommendations_mark-claimed -l state-metadata -d 'POSITIONAL ARGUMENTS RECOMMENDATION'
complete -c gcloud_alpha_recommender_recommendations_mark-claimed -l location
complete -c gcloud_alpha_recommender_recommendations_mark-claimed -l organization
complete -c gcloud_alpha_recommender_recommendations_mark-claimed -l billing-account
complete -c gcloud_alpha_recommender_recommendations_mark-claimed -l folder
complete -c gcloud_alpha_recommender_recommendations_mark-claimed -l project
complete -c gcloud_alpha_recommender_recommendations_mark-claimed -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_recommender_recommendations_mark-claimed -l impersonate-service-account -l log-http -l quiet
complete -c gcloud_alpha_recommender_recommendations_mark-claimed -l trace-token -l user-output-enabled -l verbosity

