# gcloud_alpha_sql_ssl_server-ca-certs_rollback
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_sql_ssl_server-ca-certs_rollback.1.gz
complete -c gcloud_alpha_sql_ssl_server-ca-certs_rollback -l instance -s i
complete -c gcloud_alpha_sql_ssl_server-ca-certs_rollback -l async
complete -c gcloud_alpha_sql_ssl_server-ca-certs_rollback -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_sql_ssl_server-ca-certs_rollback -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_sql_ssl_server-ca-certs_rollback -l trace-token -l user-output-enabled -l verbosity

