# gcloud_network-management_connectivity-tests_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_network-management_connectivity-tests_update.1.gz
complete -c gcloud_network-management_connectivity-tests_update -l async
complete -c gcloud_network-management_connectivity-tests_update -l description
complete -c gcloud_network-management_connectivity-tests_update -l destination-network
complete -c gcloud_network-management_connectivity-tests_update -l destination-port
complete -c gcloud_network-management_connectivity-tests_update -l destination-project
complete -c gcloud_network-management_connectivity-tests_update -l labels
complete -c gcloud_network-management_connectivity-tests_update -l other-projects
complete -c gcloud_network-management_connectivity-tests_update -l protocol
complete -c gcloud_network-management_connectivity-tests_update -l source-network
complete -c gcloud_network-management_connectivity-tests_update -l source-network-type
complete -c gcloud_network-management_connectivity-tests_update -l source-project
complete -c gcloud_network-management_connectivity-tests_update -l clear-destination-instance
complete -c gcloud_network-management_connectivity-tests_update -l destination-instance
complete -c gcloud_network-management_connectivity-tests_update -l clear-destination-ip-address
complete -c gcloud_network-management_connectivity-tests_update -l destination-ip-address
complete -c gcloud_network-management_connectivity-tests_update -l clear-source-instance
complete -c gcloud_network-management_connectivity-tests_update -l source-instance
complete -c gcloud_network-management_connectivity-tests_update -l clear-source-ip-address
complete -c gcloud_network-management_connectivity-tests_update -l source-ip-address
complete -c gcloud_network-management_connectivity-tests_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_network-management_connectivity-tests_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_network-management_connectivity-tests_update -l trace-token -l user-output-enabled -l verbosity

