# gcloud_beta_iam_roles_undelete
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_iam_roles_undelete.1.gz
complete -c gcloud_beta_iam_roles_undelete -l organization
complete -c gcloud_beta_iam_roles_undelete -l project
complete -c gcloud_beta_iam_roles_undelete -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_iam_roles_undelete -l impersonate-service-account -l log-http -l quiet
complete -c gcloud_beta_iam_roles_undelete -l trace-token -l user-output-enabled -l verbosity

