# gcloud_beta_compute_firewall-rules_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_compute_firewall-rules_update.1.gz
complete -c gcloud_beta_compute_firewall-rules_update -l allow
complete -c gcloud_beta_compute_firewall-rules_update -l description
complete -c gcloud_beta_compute_firewall-rules_update -l destination-ranges
complete -c gcloud_beta_compute_firewall-rules_update -l disabled
complete -c gcloud_beta_compute_firewall-rules_update -l enable-logging
complete -c gcloud_beta_compute_firewall-rules_update -l logging-metadata
complete -c gcloud_beta_compute_firewall-rules_update -l priority
complete -c gcloud_beta_compute_firewall-rules_update -l rules
complete -c gcloud_beta_compute_firewall-rules_update -l source-ranges
complete -c gcloud_beta_compute_firewall-rules_update -l source-tags -d 'either the range of the source matches --source-ranges or the tag of the sour…'
complete -c gcloud_beta_compute_firewall-rules_update -l source-service-accounts
complete -c gcloud_beta_compute_firewall-rules_update -l target-service-accounts
complete -c gcloud_beta_compute_firewall-rules_update -l target-tags
complete -c gcloud_beta_compute_firewall-rules_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_compute_firewall-rules_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_compute_firewall-rules_update -l trace-token -l user-output-enabled -l verbosity

