# gcloud_alpha_services_api-keys_get-key-string
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_services_api-keys_get-key-string.1.gz
complete -c gcloud_alpha_services_api-keys_get-key-string -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_services_api-keys_get-key-string -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_services_api-keys_get-key-string -l trace-token -l user-output-enabled -l verbosity

