# gcloud_alpha_code_clean-up
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_code_clean-up.1.gz
complete -c gcloud_alpha_code_clean-up -l minikube-profile
complete -c gcloud_alpha_code_clean-up -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_code_clean-up -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_code_clean-up -l trace-token -l user-output-enabled -l verbosity

