# gcloud_alpha_data-catalog_taxonomies_policy-tags_remove-iam-policy-binding
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_data-catalog_taxonomies_policy-tags_remove-iam-policy-binding.1.gz
complete -c gcloud_alpha_data-catalog_taxonomies_policy-tags_remove-iam-policy-binding -l location
complete -c gcloud_alpha_data-catalog_taxonomies_policy-tags_remove-iam-policy-binding -l taxonomy
complete -c gcloud_alpha_data-catalog_taxonomies_policy-tags_remove-iam-policy-binding -l member
complete -c gcloud_alpha_data-catalog_taxonomies_policy-tags_remove-iam-policy-binding -l role
complete -c gcloud_alpha_data-catalog_taxonomies_policy-tags_remove-iam-policy-binding -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_data-catalog_taxonomies_policy-tags_remove-iam-policy-binding -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_data-catalog_taxonomies_policy-tags_remove-iam-policy-binding -l trace-token -l user-output-enabled -l verbosity

