# gcloud_alpha_compute_ssl-policies_list-available-features
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_compute_ssl-policies_list-available-features.1.gz
complete -c gcloud_alpha_compute_ssl-policies_list-available-features -l filter
complete -c gcloud_alpha_compute_ssl-policies_list-available-features -l sort-by -l limit
complete -c gcloud_alpha_compute_ssl-policies_list-available-features -l page-size
complete -c gcloud_alpha_compute_ssl-policies_list-available-features -l flatten
complete -c gcloud_alpha_compute_ssl-policies_list-available-features -l uri
complete -c gcloud_alpha_compute_ssl-policies_list-available-features -l configuration -l flags-file -l format -l help
complete -c gcloud_alpha_compute_ssl-policies_list-available-features -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_compute_ssl-policies_list-available-features -l trace-token -l user-output-enabled -l verbosity

