# gcloud_alpha_compute_images_vulnerabilities_list
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_compute_images_vulnerabilities_list.1.gz
complete -c gcloud_alpha_compute_images_vulnerabilities_list -l filter -d 'occurrences are shown, with any additional provided filters applied'
complete -c gcloud_alpha_compute_images_vulnerabilities_list -l image
complete -c gcloud_alpha_compute_images_vulnerabilities_list -l regexp -s r
complete -c gcloud_alpha_compute_images_vulnerabilities_list -l sort-by -l limit
complete -c gcloud_alpha_compute_images_vulnerabilities_list -l page-size
complete -c gcloud_alpha_compute_images_vulnerabilities_list -l flatten
complete -c gcloud_alpha_compute_images_vulnerabilities_list -l uri
complete -c gcloud_alpha_compute_images_vulnerabilities_list -l configuration -l flags-file -l format -l help
complete -c gcloud_alpha_compute_images_vulnerabilities_list -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_compute_images_vulnerabilities_list -l trace-token -l user-output-enabled -l verbosity

