# gcloud_beta_deployment-manager_types_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_deployment-manager_types_create.1.gz
complete -c gcloud_beta_deployment-manager_types_create -l template
complete -c gcloud_beta_deployment-manager_types_create -l async
complete -c gcloud_beta_deployment-manager_types_create -l description
complete -c gcloud_beta_deployment-manager_types_create -l labels
complete -c gcloud_beta_deployment-manager_types_create -l status
complete -c gcloud_beta_deployment-manager_types_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_deployment-manager_types_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_deployment-manager_types_create -l trace-token -l user-output-enabled -l verbosity

