# gcloud_components_remove
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_components_remove.1.gz
complete -c gcloud_components_remove -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_components_remove -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_components_remove -l trace-token -l user-output-enabled -l verbosity

