# gcloud_alpha_logging_buckets_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_logging_buckets_create.1.gz
complete -c gcloud_alpha_logging_buckets_create -l location
complete -c gcloud_alpha_logging_buckets_create -l description
complete -c gcloud_alpha_logging_buckets_create -l enable-analytics
complete -c gcloud_alpha_logging_buckets_create -l index
complete -c gcloud_alpha_logging_buckets_create -l restricted-fields
complete -c gcloud_alpha_logging_buckets_create -l retention-days
complete -c gcloud_alpha_logging_buckets_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_logging_buckets_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_logging_buckets_create -l trace-token -l user-output-enabled -l verbosity

