# gcloud_alpha_help
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_help.1.gz
complete -c gcloud_alpha_help -l filter
complete -c gcloud_alpha_help -l sort-by -l limit
complete -c gcloud_alpha_help -l page-size
complete -c gcloud_alpha_help -l flatten -d 'default is ~relevance.  GCLOUD WIDE FLAGS'
complete -c gcloud_alpha_help -l configuration -l flags-file -l format -l help
complete -c gcloud_alpha_help -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_help -l trace-token -l user-output-enabled -l verbosity

