# gcloud_alpha_emulators_spanner_start
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_emulators_spanner_start.1.gz
complete -c gcloud_alpha_emulators_spanner_start -l enable-fault-injection
complete -c gcloud_alpha_emulators_spanner_start -l host-port
complete -c gcloud_alpha_emulators_spanner_start -l rest-port
complete -c gcloud_alpha_emulators_spanner_start -l use-docker
complete -c gcloud_alpha_emulators_spanner_start -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_emulators_spanner_start -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_emulators_spanner_start -l trace-token -l user-output-enabled -l verbosity

