# gcloud_beta_services_peered-dns-domains_delete
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_services_peered-dns-domains_delete.1.gz
complete -c gcloud_beta_services_peered-dns-domains_delete -l network
complete -c gcloud_beta_services_peered-dns-domains_delete -l async
complete -c gcloud_beta_services_peered-dns-domains_delete -l service
complete -c gcloud_beta_services_peered-dns-domains_delete -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_services_peered-dns-domains_delete -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_services_peered-dns-domains_delete -l trace-token -l user-output-enabled -l verbosity

