# gcloud_beta_composer_environments_storage_dags_export
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_composer_environments_storage_dags_export.1.gz
complete -c gcloud_beta_composer_environments_storage_dags_export -l destination
complete -c gcloud_beta_composer_environments_storage_dags_export -l environment
complete -c gcloud_beta_composer_environments_storage_dags_export -l location
complete -c gcloud_beta_composer_environments_storage_dags_export -l source
complete -c gcloud_beta_composer_environments_storage_dags_export -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_composer_environments_storage_dags_export -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_composer_environments_storage_dags_export -l trace-token -l user-output-enabled -l verbosity

