# gcloud_alpha_healthcare_fhir-stores_export_bq
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_healthcare_fhir-stores_export_bq.1.gz
complete -c gcloud_alpha_healthcare_fhir-stores_export_bq -l dataset
complete -c gcloud_alpha_healthcare_fhir-stores_export_bq -l location
complete -c gcloud_alpha_healthcare_fhir-stores_export_bq -l bq-dataset
complete -c gcloud_alpha_healthcare_fhir-stores_export_bq -l schema-type
complete -c gcloud_alpha_healthcare_fhir-stores_export_bq -l async
complete -c gcloud_alpha_healthcare_fhir-stores_export_bq -l recursive-depth
complete -c gcloud_alpha_healthcare_fhir-stores_export_bq -l write-disposition
complete -c gcloud_alpha_healthcare_fhir-stores_export_bq -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_healthcare_fhir-stores_export_bq -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_healthcare_fhir-stores_export_bq -l trace-token -l user-output-enabled -l verbosity

