# gcloud_healthcare_hl7v2-stores_get-iam-policy
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_healthcare_hl7v2-stores_get-iam-policy.1.gz
complete -c gcloud_healthcare_hl7v2-stores_get-iam-policy -l dataset
complete -c gcloud_healthcare_hl7v2-stores_get-iam-policy -l location
complete -c gcloud_healthcare_hl7v2-stores_get-iam-policy -l filter
complete -c gcloud_healthcare_hl7v2-stores_get-iam-policy -l sort-by -l limit
complete -c gcloud_healthcare_hl7v2-stores_get-iam-policy -l page-size
complete -c gcloud_healthcare_hl7v2-stores_get-iam-policy -l flatten -d 'GCLOUD WIDE FLAGS'
complete -c gcloud_healthcare_hl7v2-stores_get-iam-policy -l configuration -l flags-file -l format -l help
complete -c gcloud_healthcare_hl7v2-stores_get-iam-policy -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_healthcare_hl7v2-stores_get-iam-policy -l trace-token -l user-output-enabled -l verbosity

