# gcloud_alpha_bq_tables_show-rows
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_bq_tables_show-rows.1.gz
complete -c gcloud_alpha_bq_tables_show-rows -l table
complete -c gcloud_alpha_bq_tables_show-rows -l dataset
complete -c gcloud_alpha_bq_tables_show-rows -l limit
complete -c gcloud_alpha_bq_tables_show-rows -l start
complete -c gcloud_alpha_bq_tables_show-rows -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_bq_tables_show-rows -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_bq_tables_show-rows -l trace-token -l user-output-enabled -l verbosity

