# gcloud_alpha_compute_resource-policies_create_vm-maintenance_concurrency-limit
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_compute_resource-policies_create_vm-maintenance_concurrency-limit.1.gz
complete -c gcloud_alpha_compute_resource-policies_create_vm-maintenance_concurrency-limit -l description
complete -c gcloud_alpha_compute_resource-policies_create_vm-maintenance_concurrency-limit -l max-percent
complete -c gcloud_alpha_compute_resource-policies_create_vm-maintenance_concurrency-limit -l region
complete -c gcloud_alpha_compute_resource-policies_create_vm-maintenance_concurrency-limit -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_compute_resource-policies_create_vm-maintenance_concurrency-limit -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_compute_resource-policies_create_vm-maintenance_concurrency-limit -l trace-token -l user-output-enabled -l verbosity

