# gcloud_beta_tasks_queues_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_tasks_queues_create.1.gz
complete -c gcloud_beta_tasks_queues_create -l log-sampling-ratio
complete -c gcloud_beta_tasks_queues_create -l max-attempts
complete -c gcloud_beta_tasks_queues_create -l max-backoff
complete -c gcloud_beta_tasks_queues_create -l max-concurrent-dispatches
complete -c gcloud_beta_tasks_queues_create -l max-dispatches-per-second
complete -c gcloud_beta_tasks_queues_create -l max-doublings
complete -c gcloud_beta_tasks_queues_create -l max-retry-duration
complete -c gcloud_beta_tasks_queues_create -l min-backoff
complete -c gcloud_beta_tasks_queues_create -l routing-override
complete -c gcloud_beta_tasks_queues_create -l type
complete -c gcloud_beta_tasks_queues_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_tasks_queues_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_tasks_queues_create -l trace-token -l user-output-enabled -l verbosity

