# gcloud_alpha_logging_operations_cancel
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_logging_operations_cancel.1.gz
complete -c gcloud_alpha_logging_operations_cancel -l location
complete -c gcloud_alpha_logging_operations_cancel -l billing-account
complete -c gcloud_alpha_logging_operations_cancel -l folder
complete -c gcloud_alpha_logging_operations_cancel -l organization
complete -c gcloud_alpha_logging_operations_cancel -l project
complete -c gcloud_alpha_logging_operations_cancel -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_logging_operations_cancel -l impersonate-service-account -l log-http -l quiet
complete -c gcloud_alpha_logging_operations_cancel -l trace-token -l user-output-enabled -l verbosity

