# gcloud_compute_shared-vpc_associated-projects_remove
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_compute_shared-vpc_associated-projects_remove.1.gz
complete -c gcloud_compute_shared-vpc_associated-projects_remove -l host-project
complete -c gcloud_compute_shared-vpc_associated-projects_remove -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_compute_shared-vpc_associated-projects_remove -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_compute_shared-vpc_associated-projects_remove -l trace-token -l user-output-enabled -l verbosity

