# gcloud_recommender_recommendations_describe
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_recommender_recommendations_describe.1.gz
complete -c gcloud_recommender_recommendations_describe -l recommender -d 'POSITIONAL ARGUMENTS RECOMMENDATION'
complete -c gcloud_recommender_recommendations_describe -l location
complete -c gcloud_recommender_recommendations_describe -l organization
complete -c gcloud_recommender_recommendations_describe -l billing-account
complete -c gcloud_recommender_recommendations_describe -l folder
complete -c gcloud_recommender_recommendations_describe -l project
complete -c gcloud_recommender_recommendations_describe -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_recommender_recommendations_describe -l impersonate-service-account -l log-http -l quiet
complete -c gcloud_recommender_recommendations_describe -l trace-token -l user-output-enabled -l verbosity

