# gcloud_dataproc_workflow-templates_set-cluster-selector
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_dataproc_workflow-templates_set-cluster-selector.1.gz
complete -c gcloud_dataproc_workflow-templates_set-cluster-selector -l region
complete -c gcloud_dataproc_workflow-templates_set-cluster-selector -l cluster-labels
complete -c gcloud_dataproc_workflow-templates_set-cluster-selector -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_dataproc_workflow-templates_set-cluster-selector -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_dataproc_workflow-templates_set-cluster-selector -l trace-token -l user-output-enabled -l verbosity

