# gcloud_beta_data-catalog_entries_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_data-catalog_entries_update.1.gz
complete -c gcloud_beta_data-catalog_entries_update -l entry-group
complete -c gcloud_beta_data-catalog_entries_update -l location
complete -c gcloud_beta_data-catalog_entries_update -l description
complete -c gcloud_beta_data-catalog_entries_update -l display-name
complete -c gcloud_beta_data-catalog_entries_update -l lookup-entry
complete -c gcloud_beta_data-catalog_entries_update -l add-file-patterns
complete -c gcloud_beta_data-catalog_entries_update -l clear-file-patterns
complete -c gcloud_beta_data-catalog_entries_update -l remove-file-patterns
complete -c gcloud_beta_data-catalog_entries_update -l schema
complete -c gcloud_beta_data-catalog_entries_update -l schema-from-file
complete -c gcloud_beta_data-catalog_entries_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_data-catalog_entries_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_data-catalog_entries_update -l trace-token -l user-output-enabled -l verbosity

