# gcloud_compute_target-pools_remove-instances
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_compute_target-pools_remove-instances.1.gz
complete -c gcloud_compute_target-pools_remove-instances -l instances
complete -c gcloud_compute_target-pools_remove-instances -l instances-zone
complete -c gcloud_compute_target-pools_remove-instances -l region
complete -c gcloud_compute_target-pools_remove-instances -l zone
complete -c gcloud_compute_target-pools_remove-instances -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_compute_target-pools_remove-instances -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_compute_target-pools_remove-instances -l trace-token -l user-output-enabled -l verbosity

