# gcloud_sql_ssl_client-certs_describe
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_sql_ssl_client-certs_describe.1.gz
complete -c gcloud_sql_ssl_client-certs_describe -l instance -s i
complete -c gcloud_sql_ssl_client-certs_describe -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_sql_ssl_client-certs_describe -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_sql_ssl_client-certs_describe -l trace-token -l user-output-enabled -l verbosity

