# gcloud_config_configurations_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_config_configurations_create.1.gz
complete -c gcloud_config_configurations_create -l activate
complete -c gcloud_config_configurations_create -l no-activate -d 'GCLOUD WIDE FLAGS'
complete -c gcloud_config_configurations_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_config_configurations_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_config_configurations_create -l trace-token -l user-output-enabled -l verbosity

