# gcloud_alpha_compute_sign-url
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_compute_sign-url.1.gz
complete -c gcloud_alpha_compute_sign-url -l expires-in
complete -c gcloud_alpha_compute_sign-url -l key-file
complete -c gcloud_alpha_compute_sign-url -l key-name
complete -c gcloud_alpha_compute_sign-url -l validate
complete -c gcloud_alpha_compute_sign-url -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_compute_sign-url -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_compute_sign-url -l trace-token -l user-output-enabled -l verbosity

