# gcloud_alpha_compute_instance-groups_managed_list-errors
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_compute_instance-groups_managed_list-errors.1.gz
complete -c gcloud_alpha_compute_instance-groups_managed_list-errors -l region
complete -c gcloud_alpha_compute_instance-groups_managed_list-errors -l zone
complete -c gcloud_alpha_compute_instance-groups_managed_list-errors -l filter
complete -c gcloud_alpha_compute_instance-groups_managed_list-errors -l sort-by -l limit
complete -c gcloud_alpha_compute_instance-groups_managed_list-errors -l page-size
complete -c gcloud_alpha_compute_instance-groups_managed_list-errors -l flatten
complete -c gcloud_alpha_compute_instance-groups_managed_list-errors -l uri
complete -c gcloud_alpha_compute_instance-groups_managed_list-errors -l configuration -l flags-file -l format -l help
complete -c gcloud_alpha_compute_instance-groups_managed_list-errors -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_compute_instance-groups_managed_list-errors -l trace-token -l user-output-enabled -l verbosity

