# gcloud_beta_dataproc_workflow-templates_remove-job
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_dataproc_workflow-templates_remove-job.1.gz
complete -c gcloud_beta_dataproc_workflow-templates_remove-job -l region
complete -c gcloud_beta_dataproc_workflow-templates_remove-job -l step-id
complete -c gcloud_beta_dataproc_workflow-templates_remove-job -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_dataproc_workflow-templates_remove-job -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_dataproc_workflow-templates_remove-job -l trace-token -l user-output-enabled -l verbosity

