# gcloud_compute_disks_add-iam-policy-binding
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_compute_disks_add-iam-policy-binding.1.gz
complete -c gcloud_compute_disks_add-iam-policy-binding -l zone
complete -c gcloud_compute_disks_add-iam-policy-binding -l member
complete -c gcloud_compute_disks_add-iam-policy-binding -l role
complete -c gcloud_compute_disks_add-iam-policy-binding -l condition
complete -c gcloud_compute_disks_add-iam-policy-binding -l condition-from-file
complete -c gcloud_compute_disks_add-iam-policy-binding -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_compute_disks_add-iam-policy-binding -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_compute_disks_add-iam-policy-binding -l trace-token -l user-output-enabled -l verbosity

