# gcloud_beta_ml_vision_detect-logos
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_ml_vision_detect-logos.1.gz
complete -c gcloud_beta_ml_vision_detect-logos -l max-results
complete -c gcloud_beta_ml_vision_detect-logos -l model-version
complete -c gcloud_beta_ml_vision_detect-logos -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_ml_vision_detect-logos -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_ml_vision_detect-logos -l trace-token -l user-output-enabled -l verbosity

