# gcloud_pubsub_topics_list-subscriptions
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_pubsub_topics_list-subscriptions.1.gz
complete -c gcloud_pubsub_topics_list-subscriptions -l filter
complete -c gcloud_pubsub_topics_list-subscriptions -l sort-by -l limit
complete -c gcloud_pubsub_topics_list-subscriptions -l page-size
complete -c gcloud_pubsub_topics_list-subscriptions -l flatten
complete -c gcloud_pubsub_topics_list-subscriptions -l uri
complete -c gcloud_pubsub_topics_list-subscriptions -l configuration -l flags-file -l format -l help
complete -c gcloud_pubsub_topics_list-subscriptions -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_pubsub_topics_list-subscriptions -l trace-token -l user-output-enabled -l verbosity

