# gcloud_alpha_data-catalog_tag-templates_fields_delete
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_data-catalog_tag-templates_fields_delete.1.gz
complete -c gcloud_alpha_data-catalog_tag-templates_fields_delete -l location
complete -c gcloud_alpha_data-catalog_tag-templates_fields_delete -l tag-template
complete -c gcloud_alpha_data-catalog_tag-templates_fields_delete -l force
complete -c gcloud_alpha_data-catalog_tag-templates_fields_delete -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_data-catalog_tag-templates_fields_delete -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_data-catalog_tag-templates_fields_delete -l trace-token -l user-output-enabled -l verbosity

