# gcloud_beta_compute_instances_start
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_compute_instances_start.1.gz
complete -c gcloud_beta_compute_instances_start -l async
complete -c gcloud_beta_compute_instances_start -l csek-key-file
complete -c gcloud_beta_compute_instances_start -l zone
complete -c gcloud_beta_compute_instances_start -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_compute_instances_start -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_compute_instances_start -l trace-token -l user-output-enabled -l verbosity

