# gcloud_beta_iot_registries_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_iot_registries_update.1.gz
complete -c gcloud_beta_iot_registries_update -l region
complete -c gcloud_beta_iot_registries_update -l enable-http-config
complete -c gcloud_beta_iot_registries_update -l enable-mqtt-config
complete -c gcloud_beta_iot_registries_update -l event-notification-config
complete -c gcloud_beta_iot_registries_update -l log-level
complete -c gcloud_beta_iot_registries_update -l state-pubsub-topic
complete -c gcloud_beta_iot_registries_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_iot_registries_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_iot_registries_update -l trace-token -l user-output-enabled -l verbosity

