# gcloud_alpha_iam_workload-identity-pools_undelete
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_iam_workload-identity-pools_undelete.1.gz
complete -c gcloud_alpha_iam_workload-identity-pools_undelete -l location
complete -c gcloud_alpha_iam_workload-identity-pools_undelete -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_iam_workload-identity-pools_undelete -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_iam_workload-identity-pools_undelete -l trace-token -l user-output-enabled -l verbosity

