# gcloud_compute_packet-mirrorings_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_compute_packet-mirrorings_create.1.gz
complete -c gcloud_compute_packet-mirrorings_create -l collector-ilb
complete -c gcloud_compute_packet-mirrorings_create -l network
complete -c gcloud_compute_packet-mirrorings_create -l async
complete -c gcloud_compute_packet-mirrorings_create -l description
complete -c gcloud_compute_packet-mirrorings_create -l enable
complete -c gcloud_compute_packet-mirrorings_create -l no-enable
complete -c gcloud_compute_packet-mirrorings_create -l filter-cidr-ranges
complete -c gcloud_compute_packet-mirrorings_create -l filter-direction
complete -c gcloud_compute_packet-mirrorings_create -l filter-protocols
complete -c gcloud_compute_packet-mirrorings_create -l mirrored-instances
complete -c gcloud_compute_packet-mirrorings_create -l mirrored-subnets
complete -c gcloud_compute_packet-mirrorings_create -l mirrored-tags
complete -c gcloud_compute_packet-mirrorings_create -l region
complete -c gcloud_compute_packet-mirrorings_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_compute_packet-mirrorings_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_compute_packet-mirrorings_create -l trace-token -l user-output-enabled -l verbosity

