# gcloud_alpha_dialogflow_entity-types_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_dialogflow_entity-types_update.1.gz
complete -c gcloud_alpha_dialogflow_entity-types_update -l auto-expand
complete -c gcloud_alpha_dialogflow_entity-types_update -l display-name
complete -c gcloud_alpha_dialogflow_entity-types_update -l add-entities
complete -c gcloud_alpha_dialogflow_entity-types_update -l entities -d '  red:   - red   - cherry   - rose   blue:   - blue   - azure   - cyan For mo…'
complete -c gcloud_alpha_dialogflow_entity-types_update -l clear-entities
complete -c gcloud_alpha_dialogflow_entity-types_update -l remove-entities
complete -c gcloud_alpha_dialogflow_entity-types_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_dialogflow_entity-types_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_dialogflow_entity-types_update -l trace-token -l user-output-enabled -l verbosity

