# gcloud_alpha_monitoring_policies_conditions_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_monitoring_policies_conditions_update.1.gz
complete -c gcloud_alpha_monitoring_policies_conditions_update -l policy
complete -c gcloud_alpha_monitoring_policies_conditions_update -l display-name
complete -c gcloud_alpha_monitoring_policies_conditions_update -l if
complete -c gcloud_alpha_monitoring_policies_conditions_update -l trigger-count
complete -c gcloud_alpha_monitoring_policies_conditions_update -l trigger-percent
complete -c gcloud_alpha_monitoring_policies_conditions_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_monitoring_policies_conditions_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_monitoring_policies_conditions_update -l trace-token -l user-output-enabled -l verbosity

