# gcloud_beta_compute_target-ssl-proxies_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_compute_target-ssl-proxies_update.1.gz
complete -c gcloud_beta_compute_target-ssl-proxies_update -l backend-service
complete -c gcloud_beta_compute_target-ssl-proxies_update -l proxy-header
complete -c gcloud_beta_compute_target-ssl-proxies_update -l ssl-certificates
complete -c gcloud_beta_compute_target-ssl-proxies_update -l clear-ssl-policy
complete -c gcloud_beta_compute_target-ssl-proxies_update -l ssl-policy
complete -c gcloud_beta_compute_target-ssl-proxies_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_compute_target-ssl-proxies_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_compute_target-ssl-proxies_update -l trace-token -l user-output-enabled -l verbosity

