# gcloud_beta_privateca_certificates_export
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_privateca_certificates_export.1.gz
complete -c gcloud_beta_privateca_certificates_export -l issuer
complete -c gcloud_beta_privateca_certificates_export -l issuer-location
complete -c gcloud_beta_privateca_certificates_export -l output-file
complete -c gcloud_beta_privateca_certificates_export -l include-chain
complete -c gcloud_beta_privateca_certificates_export -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_privateca_certificates_export -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_privateca_certificates_export -l trace-token -l user-output-enabled -l verbosity

