# gcloud_alpha_access-context-manager_cloud-bindings_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_access-context-manager_cloud-bindings_update.1.gz
complete -c gcloud_alpha_access-context-manager_cloud-bindings_update -l binding
complete -c gcloud_alpha_access-context-manager_cloud-bindings_update -l organization
complete -c gcloud_alpha_access-context-manager_cloud-bindings_update -l level
complete -c gcloud_alpha_access-context-manager_cloud-bindings_update -l policy
complete -c gcloud_alpha_access-context-manager_cloud-bindings_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_access-context-manager_cloud-bindings_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_access-context-manager_cloud-bindings_update -l trace-token -l user-output-enabled -l verbosity

