# gcloud_alpha_composer_environments_list-upgrades
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_composer_environments_list-upgrades.1.gz
complete -c gcloud_alpha_composer_environments_list-upgrades -l location
complete -c gcloud_alpha_composer_environments_list-upgrades -l filter
complete -c gcloud_alpha_composer_environments_list-upgrades -l sort-by -l limit
complete -c gcloud_alpha_composer_environments_list-upgrades -l page-size
complete -c gcloud_alpha_composer_environments_list-upgrades -l flatten -d 'GCLOUD WIDE FLAGS'
complete -c gcloud_alpha_composer_environments_list-upgrades -l configuration -l flags-file -l format -l help
complete -c gcloud_alpha_composer_environments_list-upgrades -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_composer_environments_list-upgrades -l trace-token -l user-output-enabled -l verbosity

