# gcloud_alpha_kms_keys_versions_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_kms_keys_versions_update.1.gz
complete -c gcloud_alpha_kms_keys_versions_update -l external-key-uri
complete -c gcloud_alpha_kms_keys_versions_update -l key
complete -c gcloud_alpha_kms_keys_versions_update -l keyring
complete -c gcloud_alpha_kms_keys_versions_update -l location
complete -c gcloud_alpha_kms_keys_versions_update -l state
complete -c gcloud_alpha_kms_keys_versions_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_kms_keys_versions_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_kms_keys_versions_update -l trace-token -l user-output-enabled -l verbosity

