# gcloud_access-context-manager_cloud-bindings_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_access-context-manager_cloud-bindings_create.1.gz
complete -c gcloud_access-context-manager_cloud-bindings_create -l group-key
complete -c gcloud_access-context-manager_cloud-bindings_create -l level
complete -c gcloud_access-context-manager_cloud-bindings_create -l policy
complete -c gcloud_access-context-manager_cloud-bindings_create -l organization
complete -c gcloud_access-context-manager_cloud-bindings_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_access-context-manager_cloud-bindings_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_access-context-manager_cloud-bindings_create -l trace-token -l user-output-enabled -l verbosity

