# gcloud_alpha_dataproc_clusters_create-from-file
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_dataproc_clusters_create-from-file.1.gz
complete -c gcloud_alpha_dataproc_clusters_create-from-file -l file
complete -c gcloud_alpha_dataproc_clusters_create-from-file -l async
complete -c gcloud_alpha_dataproc_clusters_create-from-file -l region
complete -c gcloud_alpha_dataproc_clusters_create-from-file -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_dataproc_clusters_create-from-file -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_dataproc_clusters_create-from-file -l trace-token -l user-output-enabled -l verbosity

