# gcloud_alpha_dns_record-sets_export
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_dns_record-sets_export.1.gz
complete -c gcloud_alpha_dns_record-sets_export -l zone -s z
complete -c gcloud_alpha_dns_record-sets_export -l zone-file-format
complete -c gcloud_alpha_dns_record-sets_export -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_dns_record-sets_export -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_dns_record-sets_export -l trace-token -l user-output-enabled -l verbosity

