# gcloud_beta_bigtable_instances_tables_describe
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_bigtable_instances_tables_describe.1.gz
complete -c gcloud_beta_bigtable_instances_tables_describe -l instance
complete -c gcloud_beta_bigtable_instances_tables_describe -l view
complete -c gcloud_beta_bigtable_instances_tables_describe -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_bigtable_instances_tables_describe -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_bigtable_instances_tables_describe -l trace-token -l user-output-enabled -l verbosity

