# gcloud_beta_asset_export-iam-policy-analysis
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_asset_export-iam-policy-analysis.1.gz
complete -c gcloud_beta_asset_export-iam-policy-analysis -l output-path
complete -c gcloud_beta_asset_export-iam-policy-analysis -l folder
complete -c gcloud_beta_asset_export-iam-policy-analysis -l organization
complete -c gcloud_beta_asset_export-iam-policy-analysis -l project
complete -c gcloud_beta_asset_export-iam-policy-analysis -l full-resource-name
complete -c gcloud_beta_asset_export-iam-policy-analysis -l identity
complete -c gcloud_beta_asset_export-iam-policy-analysis -l analyze-service-account-impersonation
complete -c gcloud_beta_asset_export-iam-policy-analysis -l expand-groups
complete -c gcloud_beta_asset_export-iam-policy-analysis -l expand-resources
complete -c gcloud_beta_asset_export-iam-policy-analysis -l expand-roles
complete -c gcloud_beta_asset_export-iam-policy-analysis -l output-group-edges
complete -c gcloud_beta_asset_export-iam-policy-analysis -l output-resource-edges
complete -c gcloud_beta_asset_export-iam-policy-analysis -l permissions
complete -c gcloud_beta_asset_export-iam-policy-analysis -l roles
complete -c gcloud_beta_asset_export-iam-policy-analysis -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_asset_export-iam-policy-analysis -l impersonate-service-account -l log-http -l quiet
complete -c gcloud_beta_asset_export-iam-policy-analysis -l trace-token -l user-output-enabled -l verbosity

