# gcloud_alpha_artifacts_repositories_list
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_artifacts_repositories_list.1.gz
complete -c gcloud_alpha_artifacts_repositories_list -l location -d 'flag, the default location is used if you set the artifacts/location property'
complete -c gcloud_alpha_artifacts_repositories_list -l filter
complete -c gcloud_alpha_artifacts_repositories_list -l sort-by -l limit
complete -c gcloud_alpha_artifacts_repositories_list -l page-size
complete -c gcloud_alpha_artifacts_repositories_list -l flatten -d 'GCLOUD WIDE FLAGS'
complete -c gcloud_alpha_artifacts_repositories_list -l configuration -l flags-file -l format -l help
complete -c gcloud_alpha_artifacts_repositories_list -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_artifacts_repositories_list -l trace-token -l user-output-enabled -l verbosity

