# gcloud_compute_backend-buckets_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_compute_backend-buckets_update.1.gz
complete -c gcloud_compute_backend-buckets_update -l cache-mode
complete -c gcloud_compute_backend-buckets_update -l description
complete -c gcloud_compute_backend-buckets_update -l enable-cdn
complete -c gcloud_compute_backend-buckets_update -l no-enable-cdn
complete -c gcloud_compute_backend-buckets_update -l gcs-bucket-name
complete -c gcloud_compute_backend-buckets_update -l request-coalescing
complete -c gcloud_compute_backend-buckets_update -l no-request-coalescing
complete -c gcloud_compute_backend-buckets_update -l signed-url-cache-max-age
complete -c gcloud_compute_backend-buckets_update -l bypass-cache-on-request-headers
complete -c gcloud_compute_backend-buckets_update -l no-bypass-cache-on-request-headers
complete -c gcloud_compute_backend-buckets_update -l client-ttl
complete -c gcloud_compute_backend-buckets_update -l no-client-ttl
complete -c gcloud_compute_backend-buckets_update -l custom-response-header
complete -c gcloud_compute_backend-buckets_update -l no-custom-response-headers
complete -c gcloud_compute_backend-buckets_update -l default-ttl
complete -c gcloud_compute_backend-buckets_update -l no-default-ttl
complete -c gcloud_compute_backend-buckets_update -l max-ttl
complete -c gcloud_compute_backend-buckets_update -l no-max-ttl
complete -c gcloud_compute_backend-buckets_update -l negative-caching
complete -c gcloud_compute_backend-buckets_update -l no-negative-caching-policies
complete -c gcloud_compute_backend-buckets_update -l negative-caching-policy
complete -c gcloud_compute_backend-buckets_update -l serve-while-stale
complete -c gcloud_compute_backend-buckets_update -l no-serve-while-stale
complete -c gcloud_compute_backend-buckets_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_compute_backend-buckets_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_compute_backend-buckets_update -l trace-token -l user-output-enabled -l verbosity

