# gcloud_compute_routers_get-status
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_compute_routers_get-status.1.gz
complete -c gcloud_compute_routers_get-status -l region
complete -c gcloud_compute_routers_get-status -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_compute_routers_get-status -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_compute_routers_get-status -l trace-token -l user-output-enabled -l verbosity

