# gcloud_alpha_certificate-manager_maps_entries_update
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_certificate-manager_maps_entries_update.1.gz
complete -c gcloud_alpha_certificate-manager_maps_entries_update -l update-labels -l certificates -d 'POSITIONAL ARGUMENTS Certificate map entry resource - The certificate map ent…'
complete -c gcloud_alpha_certificate-manager_maps_entries_update -l map
complete -c gcloud_alpha_certificate-manager_maps_entries_update -l description
complete -c gcloud_alpha_certificate-manager_maps_entries_update -l clear-certificates
complete -c gcloud_alpha_certificate-manager_maps_entries_update -l async
complete -c gcloud_alpha_certificate-manager_maps_entries_update -l clear-labels
complete -c gcloud_alpha_certificate-manager_maps_entries_update -l remove-labels
complete -c gcloud_alpha_certificate-manager_maps_entries_update -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_certificate-manager_maps_entries_update -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_certificate-manager_maps_entries_update -l trace-token -l user-output-enabled -l verbosity

