# gcloud_alpha_dns_record-sets_transaction_add
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_dns_record-sets_transaction_add.1.gz
complete -c gcloud_alpha_dns_record-sets_transaction_add -l name
complete -c gcloud_alpha_dns_record-sets_transaction_add -l ttl
complete -c gcloud_alpha_dns_record-sets_transaction_add -l type
complete -c gcloud_alpha_dns_record-sets_transaction_add -l zone -s z
complete -c gcloud_alpha_dns_record-sets_transaction_add -l transaction-file
complete -c gcloud_alpha_dns_record-sets_transaction_add -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_dns_record-sets_transaction_add -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_dns_record-sets_transaction_add -l trace-token -l user-output-enabled -l verbosity

