# gcloud_alpha_data-catalog_entries_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_data-catalog_entries_create.1.gz
complete -c gcloud_alpha_data-catalog_entries_create -l entry-group
complete -c gcloud_alpha_data-catalog_entries_create -l location
complete -c gcloud_alpha_data-catalog_entries_create -l gcs-file-patterns
complete -c gcloud_alpha_data-catalog_entries_create -l description
complete -c gcloud_alpha_data-catalog_entries_create -l display-name
complete -c gcloud_alpha_data-catalog_entries_create -l schema
complete -c gcloud_alpha_data-catalog_entries_create -l schema-from-file
complete -c gcloud_alpha_data-catalog_entries_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_data-catalog_entries_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_data-catalog_entries_create -l trace-token -l user-output-enabled -l verbosity

