# gcloud_compute_instance-groups_managed_update-autoscaling
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_compute_instance-groups_managed_update-autoscaling.1.gz
complete -c gcloud_compute_instance-groups_managed_update-autoscaling -l cpu-utilization-predictive-method
complete -c gcloud_compute_instance-groups_managed_update-autoscaling -l max-num-replicas
complete -c gcloud_compute_instance-groups_managed_update-autoscaling -l min-num-replicas
complete -c gcloud_compute_instance-groups_managed_update-autoscaling -l mode
complete -c gcloud_compute_instance-groups_managed_update-autoscaling -l clear-scale-in-control
complete -c gcloud_compute_instance-groups_managed_update-autoscaling -l scale-in-control
complete -c gcloud_compute_instance-groups_managed_update-autoscaling -l disable-schedule
complete -c gcloud_compute_instance-groups_managed_update-autoscaling -l enable-schedule
complete -c gcloud_compute_instance-groups_managed_update-autoscaling -l remove-schedule
complete -c gcloud_compute_instance-groups_managed_update-autoscaling -l set-schedule
complete -c gcloud_compute_instance-groups_managed_update-autoscaling -l update-schedule
complete -c gcloud_compute_instance-groups_managed_update-autoscaling -l region
complete -c gcloud_compute_instance-groups_managed_update-autoscaling -l zone
complete -c gcloud_compute_instance-groups_managed_update-autoscaling -l schedule-cron
complete -c gcloud_compute_instance-groups_managed_update-autoscaling -l schedule-description
complete -c gcloud_compute_instance-groups_managed_update-autoscaling -l schedule-duration-sec
complete -c gcloud_compute_instance-groups_managed_update-autoscaling -l schedule-min-required-replicas
complete -c gcloud_compute_instance-groups_managed_update-autoscaling -l schedule-time-zone
complete -c gcloud_compute_instance-groups_managed_update-autoscaling -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_compute_instance-groups_managed_update-autoscaling -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_compute_instance-groups_managed_update-autoscaling -l trace-token -l user-output-enabled -l verbosity

