# gcloud_beta_compute_reservations_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_compute_reservations_create.1.gz
complete -c gcloud_beta_compute_reservations_create -l machine-type
complete -c gcloud_beta_compute_reservations_create -l vm-count
complete -c gcloud_beta_compute_reservations_create -l accelerator
complete -c gcloud_beta_compute_reservations_create -l local-ssd
complete -c gcloud_beta_compute_reservations_create -l min-cpu-platform
complete -c gcloud_beta_compute_reservations_create -l require-specific-reservation
complete -c gcloud_beta_compute_reservations_create -l reservation-affinity -d 'OPTIONAL FLAGS'
complete -c gcloud_beta_compute_reservations_create -l description
complete -c gcloud_beta_compute_reservations_create -l zone
complete -c gcloud_beta_compute_reservations_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_compute_reservations_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_compute_reservations_create -l trace-token -l user-output-enabled -l verbosity

