# gcloud_alpha_ml_vision_detect-product
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_ml_vision_detect-product.1.gz
complete -c gcloud_alpha_ml_vision_detect-product -l category
complete -c gcloud_alpha_ml_vision_detect-product -l product-set
complete -c gcloud_alpha_ml_vision_detect-product -l product-set-location
complete -c gcloud_alpha_ml_vision_detect-product -l bounding-polygon
complete -c gcloud_alpha_ml_vision_detect-product -l filter
complete -c gcloud_alpha_ml_vision_detect-product -l max-results
complete -c gcloud_alpha_ml_vision_detect-product -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_ml_vision_detect-product -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_ml_vision_detect-product -l trace-token -l user-output-enabled -l verbosity

