# gcloud_components_restore
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_components_restore.1.gz
complete -c gcloud_components_restore -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_components_restore -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_components_restore -l trace-token -l user-output-enabled -l verbosity

