# gcloud_compute_target-pools_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_compute_target-pools_create.1.gz
complete -c gcloud_compute_target-pools_create -l backup-pool
complete -c gcloud_compute_target-pools_create -l failover-ratio -d 'load-balanced IP address will be directed to the backup pool'
complete -c gcloud_compute_target-pools_create -l description
complete -c gcloud_compute_target-pools_create -l health-check
complete -c gcloud_compute_target-pools_create -l http-health-check
complete -c gcloud_compute_target-pools_create -l region
complete -c gcloud_compute_target-pools_create -l session-affinity
complete -c gcloud_compute_target-pools_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_compute_target-pools_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_compute_target-pools_create -l trace-token -l user-output-enabled -l verbosity

