# gcloud_spanner_backups_create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_spanner_backups_create.1.gz
complete -c gcloud_spanner_backups_create -l instance
complete -c gcloud_spanner_backups_create -l database
complete -c gcloud_spanner_backups_create -l expiration-date
complete -c gcloud_spanner_backups_create -l retention-period
complete -c gcloud_spanner_backups_create -l async
complete -c gcloud_spanner_backups_create -l version-time
complete -c gcloud_spanner_backups_create -l encryption-type
complete -c gcloud_spanner_backups_create -l kms-key
complete -c gcloud_spanner_backups_create -l kms-keyring
complete -c gcloud_spanner_backups_create -l kms-location
complete -c gcloud_spanner_backups_create -l kms-project
complete -c gcloud_spanner_backups_create -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_spanner_backups_create -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_spanner_backups_create -l trace-token -l user-output-enabled -l verbosity

