# gcloud_alpha_dataproc_jobs_wait
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_alpha_dataproc_jobs_wait.1.gz
complete -c gcloud_alpha_dataproc_jobs_wait -l region
complete -c gcloud_alpha_dataproc_jobs_wait -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_alpha_dataproc_jobs_wait -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_alpha_dataproc_jobs_wait -l trace-token -l user-output-enabled -l verbosity

