# gcloud_beta_container_binauthz_create-signature-payload
# Autogenerated from man page /usr/lib/jvm/default/man/man1/gcloud_beta_container_binauthz_create-signature-payload.1.gz
complete -c gcloud_beta_container_binauthz_create-signature-payload -l artifact-url
complete -c gcloud_beta_container_binauthz_create-signature-payload -l configuration -l flags-file -l flatten -l format -l help
complete -c gcloud_beta_container_binauthz_create-signature-payload -l impersonate-service-account -l log-http -l project -l quiet
complete -c gcloud_beta_container_binauthz_create-signature-payload -l trace-token -l user-output-enabled -l verbosity

