# gears
# Autogenerated from man page /usr/lib/jvm/default/man/man6/gears.6.gz
complete -c gears -o window -d 'Draw on a newly-created window.   This is the default'
complete -c gears -o root -d 'Draw on the root window'
complete -c gears -o install -d 'Install a private colormap for the window'
complete -c gears -o visual -d 'Specify which visual to use'
complete -c gears -o delay -d 'The delay between frames of the animation, in microseconds'
complete -c gears -o speed -d 'Larger numbers mean run faster.   Default: 1. 0'
complete -c gears -o no-spin -d 'Don\'t rotate the object'
complete -c gears -o no-wander -d 'Don\'t wander the object around the screen'
complete -c gears -o count -d 'How many gears to draw.   Default: 0 for random'
complete -c gears -o wireframe -d 'Render in wireframe instead of solid'
complete -c gears -o fps -d 'Display the current frame rate, CPU load, and polygon count'

