# geodesicgears
# Autogenerated from man page /usr/lib/jvm/default/man/man6/geodesicgears.6.gz
complete -c geodesicgears -o visual -d 'Specify which visual to use'
complete -c geodesicgears -o window -d 'Draw on a newly-created window.   This is the default'
complete -c geodesicgears -o root -d 'Draw on the root window'
complete -c geodesicgears -o delay -d 'Per-frame delay, in microseconds.   Default: 30000 (0. 03 seconds)'
complete -c geodesicgears -o timeout -d 'Duration before switching to a new model.   5 - 120 seconds.   Default: 20'
complete -c geodesicgears -o labels -o no-labels -d 'Whether to show the number of gears and teeth.   Default: no'
complete -c geodesicgears -o numbers -o no-numbers -d 'Whether to label the gears with ID numbers.   Default: no'
complete -c geodesicgears -o wireframe -o no-wireframe -d 'Render in wireframe instead of solid'
complete -c geodesicgears -o wander -o no-wander -d 'Whether the object should wander around the screen'
complete -c geodesicgears -o spin -o no-spin -d 'Whether the object should spin'
complete -c geodesicgears -o fps -o no-fps -d 'Whether to show a frames-per-second display at the bottom of the screen'

