# gibson
# Autogenerated from man page /usr/lib/jvm/default/man/man6/gibson.6.gz
complete -c gibson -o visual -d 'Specify which visual to use'
complete -c gibson -o window -d 'Draw on a newly-created window.   This is the default'
complete -c gibson -o root -d 'Draw on the root window'
complete -c gibson -o delay -d 'Per-frame delay, in microseconds.   Default: 20000 (0. 02 seconds)'
complete -c gibson -o speed -d 'Animation speed.   2. 0 means twice as fast, 0. 5 means half as fast'
complete -c gibson -o grid-width -d 'Number of towers across.   1 - 20.   Default: 10'
complete -c gibson -o grid-depth -d 'Number of towers deep.   1 - 20.   Default: 10'
complete -c gibson -o grid-height -d 'Height of the towers.   1 - 20.   Default: 7'
complete -c gibson -o grid-spacing -d 'Space between towers. 	1 - 5. 	Default: 2. 0'
complete -c gibson -o columns -d 'Columns of text on the towers.   1 - 20. 	Default: 6'
complete -c gibson -o texture -o no-texture -d 'Whether to draw text.   Default true'
complete -c gibson -o wireframe -o no-wireframe -d 'Render in wireframe instead of solid'
complete -c gibson -o fps -o no-fps -d 'Whether to show a frames-per-second display at the bottom of the screen'

