# glhanoi
# Autogenerated from man page /usr/lib/jvm/default/man/man6/glhanoi.6.gz
complete -c glhanoi -o visual -d 'Specify which visual to use'
complete -c glhanoi -o window -d 'Draw on a newly-created window.   This is the default'
complete -c glhanoi -o root -d 'Draw on the root window'
complete -c glhanoi -o delay -d 'Per-frame delay, in microseconds.   Default: 30000 (0. 03 seconds. )'
complete -c glhanoi -o count -d 'Number of disks.   Default: 7'
complete -c glhanoi -o poles -d 'Number of poles.   Default: random from 3 to disks+1'
complete -c glhanoi -o speed -d 'Speed multiplier (for smallest disks).   Default: 1'
complete -c glhanoi -o trails -d 'Length of disk trails, in seconds.   Default: 2'
complete -c glhanoi -o wireframe -o no-wireframe -d 'Render in wireframe instead of solid'
complete -c glhanoi -o fog -o no-fog -d 'Render in fog'
complete -c glhanoi -o fps -d 'Display the current frame rate, CPU load, and polygon count'
complete -c glhanoi -o light -o no-light -d 'Whether the scene is lit'
complete -c glhanoi -o texture -o no-texture -d 'Render with textures instead of solid'

