# glplanet
# Autogenerated from man page /usr/lib/jvm/default/man/man6/glplanet.6.gz
complete -c glplanet -o visual -d 'Specify which visual to use'
complete -c glplanet -o window -d 'Draw on a newly-created window.   This is the default'
complete -c glplanet -o root -d 'Draw on the root window'
complete -c glplanet -o delay -d 'Per-frame delay, in microseconds.   Default: 20000 (0. 02 seconds. )'
complete -c glplanet -o image -d 'The day texture map to wrap around the planet\'s surface'
complete -c glplanet -o image2 -d 'The night texture map to wrap around the planet\'s surface'
complete -c glplanet -o mode -d 'All is right with the world'
complete -c glplanet -o resolution -d 'The resolution of the planetary mesh.  Default: 128'
complete -c glplanet -o wireframe -d 'Render in wireframe instead of solid'
complete -c glplanet -o fps -d 'Display the current frame rate, CPU load, and polygon count'

