# glslideshow
# Autogenerated from man page /usr/lib/jvm/default/man/man6/glslideshow.6.gz
complete -c glslideshow -o visual -d 'Specify which visual to use'
complete -c glslideshow -o window -d 'Draw on a newly-created window.   This is the default'
complete -c glslideshow -o root -d 'Draw on the root window'
complete -c glslideshow -o duration -d 'How long each image will be displayed before loading a new one'
complete -c glslideshow -o pan -d 'How long each pan-and-zoom should last.   Default 6 seconds'
complete -c glslideshow -o fade -d 'How long each cross-fade between images should last.   Default 2 seconds'
complete -c glslideshow -o zoom -d 'Amount to zoom and pan as a percentage'
complete -c glslideshow -o titles -d 'Whether to print the file name of the current image in the upper left corner'
complete -c glslideshow -o letterbox -d 'In "letterbox" mode, when an image is not the same aspect ratio as the screen…'
complete -c glslideshow -o clip -d 'In "clip" mode, when an image is not the same aspect ratio as the screen, we …'
complete -c glslideshow -o delay -d 'Per-frame delay, in microseconds.   Default: 20000 (0. 02 seconds. )'
complete -c glslideshow -o fps -d 'Display the current frame rate, CPU load, and polygon count'
complete -c glslideshow -o cutoff -d 'If the frame rate we are achieving is lower than this, then panning, fading, …'
complete -c glslideshow -o debug -d 'Prints debugging info to stderr'
complete -c glslideshow -o wireframe -d 'Another debug mode'

