# grav
# Autogenerated from man page /usr/lib/jvm/default/man/man6/grav.6.gz
complete -c grav -o window -d 'Draw on a newly-created window.   This is the default'
complete -c grav -o root -d 'Draw on the root window'
complete -c grav -o mono -d 'If on a color display, pretend we\'re on a monochrome display'
complete -c grav -o install -d 'Install a private colormap for the window'
complete -c grav -o visual -d 'Specify which visual to use'
complete -c grav -o ncolors -d 'How many colors should be used (if possible).   Default 64'
complete -c grav -o count -d 'Default 12'
complete -c grav -o no-decay -d 'Whether orbits should decay'
complete -c grav -o no-trail -d 'Whether the objects should leave trails behind them (makes it look vaguely li…'
complete -c grav -o decay
complete -c grav -o trail
complete -c grav -o fps -d 'Display the current frame rate and CPU load'

