# grep
# Autogenerated from man page /usr/lib/jvm/default/man/man1/grep.1p.gz
complete -c grep -o epattern_list -d 'br Specify one or more patterns to be used during the search for input'
complete -c grep -o fpattern_file -d 'br Read one or more patterns from the file named by the pathname R pattern_fi…'

