# halo
# Autogenerated from man page /usr/lib/jvm/default/man/man6/halo.6.gz
complete -c halo -o window -d 'Draw on a newly-created window.   This is the default'
complete -c halo -o root -d 'Draw on the root window'
complete -c halo -o mono -d 'If on a color display, pretend we\'re on a monochrome display'
complete -c halo -o install -d 'Install a private colormap for the window'
complete -c halo -o visual -d 'Specify which visual to use'
complete -c halo -o count -d 'How many circles to draw.   Default 0, meaning random'
complete -c halo -o mode -d 'In seuss mode, alternating striped curves will be drawn'
complete -c halo -o delay -d 'How much of a delay should be introduced between steps of the animation'
complete -c halo -o colors -d 'How many colors to use.   Default 100'
complete -c halo -o animate -d 'If specified, then the centerpoints of the circles will bounce around'
complete -c halo -o fps -d 'Display the current frame rate and CPU load'

