# hexstrut
# Autogenerated from man page /usr/lib/jvm/default/man/man6/hexstrut.6.gz
complete -c hexstrut -o visual -d 'Specify which visual to use'
complete -c hexstrut -o window -d 'Draw on a newly-created window.   This is the default'
complete -c hexstrut -o root -d 'Draw on the root window'
complete -c hexstrut -o delay -d 'Per-frame delay, in microseconds.   Default: 30000 (0. 03 seconds)'
complete -c hexstrut -o speed -d 'Animation speed.   2. 0 means twice as fast, 0. 5 means half as fast'
complete -c hexstrut -o count -d 'Approximate number of hexagons on the screen, horizontally.   Default: 20'
complete -c hexstrut -o thickness -d 'Relative thickness of the struts.   0. 01 - 1. 7.   Default: 0. 2'
complete -c hexstrut -o wander -o no-wander -d 'Whether the grid should wander around the screen'
complete -c hexstrut -o spin -o no-spin -d 'Whether the grid should spin'
complete -c hexstrut -o wireframe -o no-wireframe -d 'Render in wireframe instead of solid'
complete -c hexstrut -o fps -o no-fps -d 'Whether to show a frames-per-second display at the bottom of the screen'

