# iat
# Autogenerated from man page /usr/lib/jvm/default/man/man1/iat.1.gz
complete -c iat -s h -l help -d 'Show this help message'
complete -c iat -s V -l version -d 'Display version information'
complete -c iat -s i -l input -d 'A string option for a filename'
complete -c iat -s o -l output -d 'A string option for a filename'
complete -c iat -l debug -d 'debug image'
complete -c iat -l cue -d 'Creates  cuesheet for the image, compatible with many burn program'
complete -c iat -l toc -d 'Creates TOC for the image, for the perfect copy 1:1 of the original image, bu…'
complete -c iat -l iso -d 'Create ISO9660 image           '

