# imsmap
# Autogenerated from man page /usr/lib/jvm/default/man/man6/imsmap.6.gz
complete -c imsmap -o window -d 'Draw on a newly-created window.   This is the default'
complete -c imsmap -o root -d 'Draw on the root window'
complete -c imsmap -o mono -d 'If on a color display, pretend we\'re on a monochrome display'
complete -c imsmap -o install -d 'Install a private colormap for the window'
complete -c imsmap -o visual -d 'Specify which visual to use'
complete -c imsmap -o ncolors -d 'How many colors to use.   Default 50'
complete -c imsmap -o delay -d 'How long to delay between images.   Default 10 seconds'
complete -c imsmap -o delay2 -d 'How long to delay between bitmaps.   Default 200000 (0. 2 seconds)'
complete -c imsmap -o iterations -d 'A measure of the resolution of the resultant image, from 0 to 7.   Default 7'
complete -c imsmap -o mode -d 'The axis upon which colors should be interpolated between the foreground and …'
complete -c imsmap -o fps -d 'Display the current frame rate and CPU load'

