# jmap-openjdk15
# Autogenerated from man page /usr/lib/jvm/default/man/man1/jmap-openjdk15.1.gz
complete -c jmap-openjdk15 -o clstats -d 'Connects to a running process and prints class loader statistics of Java heap'
complete -c jmap-openjdk15 -o finalizerinfo -d 'Connects to a running process and prints information on objects awaiting fina…'
complete -c jmap-openjdk15 -o histo -d 'Connects to a running process and prints a histogram of the Java object heap'
complete -c jmap-openjdk15 -o dump:dump_options -d 'Connects to a running process and dumps the Java heap'

