# julia
# Autogenerated from man page /usr/lib/jvm/default/man/man6/julia.6.gz
complete -c julia -o window -d 'Draw on a newly-created window.   This is the default'
complete -c julia -o root -d 'Draw on the root window'
complete -c julia -o mono -d 'If on a color display, pretend we\'re on a monochrome display'
complete -c julia -o install -d 'Install a private colormap for the window'
complete -c julia -o visual -d 'Specify which visual to use'
complete -c julia -o ncolors -d 'How many colors should be used (if possible).   Default 200'
complete -c julia -o cycles
complete -c julia -o count
complete -c julia -o fps -d 'Display the current frame rate and CPU load'

