# lament
# Autogenerated from man page /usr/lib/jvm/default/man/man6/lament.6.gz
complete -c lament -o window -d 'Draw on a newly-created window.   This is the default'
complete -c lament -o root -d 'Draw on the root window'
complete -c lament -o install -d 'Install a private colormap for the window'
complete -c lament -o visual -d 'Specify which visual to use'
complete -c lament -o texture -d 'Use texture maps.   This is the default'
complete -c lament -o no-texture -d 'Do not use texture maps.   This is boring and wrong'
complete -c lament -o wireframe -d 'Only draw outlines'
complete -c lament -o delay -d 'How long to pause between frames.   Default is 20000, or 0. 02 second'
complete -c lament -o fps -d 'Display the current frame rate, CPU load, and polygon count'

