# lex
# Autogenerated from man page /usr/lib/jvm/default/man/man1/lex.1p.gz
complete -c lex -s n -d 'Suppress the summary of statistics usually written with the  -v option'
complete -c lex -s t -d 'Write the resulting program to standard output instead of  lex. yy. c '
complete -c lex -s v -d 'option.  If no table sizes are specified in the lex source code and the'
complete -c lex -s l -d 'operand with c99 ), the resulting program shall read character input from the…'
complete -c lex -s c -d 'option and references to the C language are retained in this description, lex…'

