# lockward
# Autogenerated from man page /usr/lib/jvm/default/man/man6/lockward.6.gz
complete -c lockward -o visual -d 'Specify which visual to use'
complete -c lockward -o window -d 'Draw on a newly-created window (default)'
complete -c lockward -o root -d 'Draw on the root window'
complete -c lockward -o delay -d 'Per-frame delay, in microseconds.   Default: 20000 (50 frames/sec)'
complete -c lockward -o blink -o no-blink -d 'Enables/disables the blinking effects.   Default: Enabled'
complete -c lockward -o fps -d 'Display the current frame rate, CPU load, and polygon count'
complete -c lockward -o rotateidle-max -d 'The minimum and maximum time each spinner will sit idle, in milliseconds'
complete -c lockward -o blinkidle-max -d 'The minimum and maximum time between blinking effects, in milliseconds'
complete -c lockward -o rotateidle-min
complete -c lockward -o blinkidle-min
complete -c lockward -o blinkdwell-min
complete -c lockward -o blinkdwell-max -d 'The minimum and maximum dwell time for the blinking effects, in milliseconds'

