# loop
# Autogenerated from man page /usr/lib/jvm/default/man/man6/loop.6.gz
complete -c loop -o visual -d 'Specify which visual to use'
complete -c loop -o window -d 'Draw on a newly-created window.   This is the default'
complete -c loop -o root -d 'Draw on the root window'
complete -c loop -o cycles -d 'Timeout.   0 - 8000.   Default: 1600'
complete -c loop -o delay -d 'Per-frame delay, in microseconds.   Default: 100000 (0. 10 seconds. )'
complete -c loop -o ncolors -d 'Number of Colors.   Default: 15'
complete -c loop -o size -d 'Size.   -50 - 50.   Default: -12'
complete -c loop -o fps -d 'Display the current frame rate and CPU load'

