# lp
# Autogenerated from man page /usr/lib/jvm/default/man/man1/lp.1p.gz
complete -c lp -o ddest -d 'Specify a string that names the destination (\\c R dest )'
complete -c lp -o ncopies -d 'Write R copies number of copies of the files, where R copies is a positive de…'
complete -c lp -o ooption -d 'Specify printer-dependent or class-dependent R option s'
complete -c lp -o ttitle -d 'Write R title on the banner page of the output'
complete -c lp -s w -d 'Write a message on the user\'s terminal after the files have been printed'

