# lttng-gen-tp
# Autogenerated from man page /usr/lib/jvm/default/man/man1/lttng-gen-tp.1.gz
complete -c lttng-gen-tp -s o -l output -d 'Do not generate default files: generate FILE'
complete -c lttng-gen-tp -s v -l verbose -d 'Increase verbosity'
complete -c lttng-gen-tp -s h -l help -d 'Show command help'

