# memscroller
# Autogenerated from man page /usr/lib/jvm/default/man/man6/memscroller.6.gz
complete -c memscroller -o window -d 'Draw on a newly-created window.   This is the default'
complete -c memscroller -o root -d 'Draw on the root window'
complete -c memscroller -o install -d 'Install a private colormap for the window'
complete -c memscroller -o visual -d 'Specify which visual to use'
complete -c memscroller -o color -d 'Render each three bytes of memory as R, G, B.   This is the default'
complete -c memscroller -o mono -d 'Render each byte of memory in shades of green'
complete -c memscroller -o ram -d 'Read from the process\'s address space.   This is the default'
complete -c memscroller -o random -d 'Instead of reading from memory, generate random numbers'
complete -c memscroller -o filename -d 'Instead of reading from memory, read from the given file until EOF, then re-o…'
complete -c memscroller -o delay -d 'How much of a delay should be introduced between steps of the animation'
complete -c memscroller -o fps -d 'Display the current frame rate and CPU load'

