# more
# Autogenerated from man page /usr/lib/jvm/default/man/man1/more.1p.gz
complete -c more -s e -d 'Exit immediately after writing the last line of the last file in the argument…'
complete -c more -s i -d 'Perform pattern matching in searches without regard to case; see the Base Def…'
complete -c more -o nnumber -d 'Specify the number of lines per screenful'
complete -c more -o pcommand -d 'Each time a screen from a new file is displayed or redisplayed (including as …'
complete -c more -o ttagstring -d 'Write the screenful of the file containing the tag named by the R tagstring a…'
complete -c more -s t -d 'Write the screenful of the file containing the tag named by the tagstring arg…'
complete -c more -s v -d 'option of 4 BSD and 4 BSD-derived versions of the cat utility since 1980'

