# munch
# Autogenerated from man page /usr/lib/jvm/default/man/man6/munch.6.gz
complete -c munch -o window -d 'Draw on a newly-created window.   This is the default'
complete -c munch -o root -d 'Draw on the root window'
complete -c munch -o mono -d 'If on a color display, pretend we\'re on a monochrome display'
complete -c munch -o install -d 'Install a private colormap for the window'
complete -c munch -o visual -d 'Specify which visual to use'
complete -c munch -o delay -d 'The delay between steps of the animation, in microseconds.   Default: 2500'
complete -c munch -o xor -d 'Use the XOR drawing function.   This is the default'
complete -c munch -o no-xor -d 'Don\'t use the XOR drawing function'
complete -c munch -o clear -d 'Number of squares to misdraw before clearing the display.   Default: 65'
complete -c munch -o simul -d 'Number of squares to misdraw simultaneously.   Default: 5'
complete -c munch -o classic -d 'Draw classic munching squares only'
complete -c munch -o mismunch -d 'Draw "mismunch" only'
complete -c munch -o random -d 'Do one or the other'
complete -c munch -o fps -d 'Display the current frame rate and CPU load'

