# od
# Autogenerated from man page /usr/lib/jvm/default/man/man1/od.1p.gz
complete -c od -o Aaddress_base -d 'br Specify the input offset base.  See the EXTENDED DESCRIPTION section'
complete -c od -o jskip -d 'Jump over R skip bytes from the beginning of the input'
complete -c od -o Ncount -d 'Format no more than R count bytes of input'
complete -c od -o ttype_string -d 'br Specify one or more output types.  See the EXTENDED DESCRIPTION section'
complete -c od -o bcdosx -d 'options is significant'
complete -c od -o bcdostx -d options
complete -c od -s n -d 'respectively, for the'

