# penetrate
# Autogenerated from man page /usr/lib/jvm/default/man/man6/penetrate.6.gz
complete -c penetrate -o display -d 'Specifies which X display we should use'
complete -c penetrate -o root -d 'Draw on the root window'
complete -c penetrate -o window -d 'Draw on a newly-created window.   This is the default'
complete -c penetrate -o install -d 'Install a private colormap for the window'
complete -c penetrate -o noinstall -d 'Don\'t install a private colormap for the window'
complete -c penetrate -o visual -d 'Specify which visual to use'
complete -c penetrate -o foreground -d 'Specifies the default foreground color'
complete -c penetrate -o background -d 'Specifies the default background color'
complete -c penetrate -o bgrowth -d 'Specifies the growth rate of the bomb explosions'
complete -c penetrate -o lrate -d 'Set the initial rate of laser fire'
complete -c penetrate -o smart -d 'Have the computer player skip the learning process'
complete -c penetrate -o fps -d 'Display the current frame rate and CPU load'

