# phosphor
# Autogenerated from man page /usr/lib/jvm/default/man/man6/phosphor.6.gz
complete -c phosphor -o window -d 'Draw on a newly-created window.   This is the default'
complete -c phosphor -o root -d 'Draw on the root window'
complete -c phosphor -o install -d 'Install a private colormap for the window'
complete -c phosphor -o visual -d 'Specify which visual to use'
complete -c phosphor -o font -d 'The X font to use'
complete -c phosphor -o scale -d 'How much to scale the font up: in other words, the size in real pixels of the…'
complete -c phosphor -o ticks -d 'The number of colors to use when fading to black.   Default 20'
complete -c phosphor -o delay -d 'The speed of the terminal: how long to wait between drawing each character'
complete -c phosphor -o pty -d 'Launch the sub-program under a PTY, so that it can address the screen directly'
complete -c phosphor -o pipe -d 'Launch the sub-program at the end of a pipe: do not let it address the screen…'
complete -c phosphor -o program -d 'The command to run to generate the text to display'
complete -c phosphor -o meta -d 'When Meta or Alt are held down, set the high bit on the character instead'
complete -c phosphor -o del -d 'Swap Backspace and Delete.   This is the default'
complete -c phosphor -o bs -d 'Do not swap Backspace and Delete'
complete -c phosphor -o esc -d 'When the user types a key with the Alt or Meta keys held down, send an ESC ch…'
complete -c phosphor -o fps -d 'Display the current frame rate and CPU load'

