# photopile
# Autogenerated from man page /usr/lib/jvm/default/man/man6/photopile.6.gz
complete -c photopile -o visual -d 'Specify which visual to use'
complete -c photopile -o window -d 'Draw on a newly-created window.   This is the default'
complete -c photopile -o root -d 'Draw on the root window'
complete -c photopile -o count -d 'How many images to display.   Default 7'
complete -c photopile -o scale -d 'Size of images in relation to the size of the window.   Default 0. 4'
complete -c photopile -o maxTilt -d 'Maximum deviation from vertical.   Default 50 degrees'
complete -c photopile -o duration -d 'Every duration seconds, one of the images will be replaced with a new one'
complete -c photopile -o speed -d 'Speed up or slow down the animation.   0'
complete -c photopile -o delay -d 'Per-frame delay, in microseconds.   Default: 10000 (0. 01 seconds. )'
complete -c photopile -o titles -o no-titles -d 'Whether to display the file names of the images beneath them.   Default: yes'
complete -c photopile -o polaroid -o no-polaroid -d 'Whether to simulate images taken by an instant camera.   Default: yes'
complete -c photopile -o shadows -o no-shadows -d 'Whether to draw images with drop shadows.   Default: no'
complete -c photopile -o font -d 'The font to use for the initial loading screen and for image titles'
complete -c photopile -o fps -d 'Display the current frame rate, CPU load, and polygon count'
complete -c photopile -o debug -d 'Prints debugging info to stderr'
complete -c photopile -o wireframe -d 'Another debug mode'

