# pinion
# Autogenerated from man page /usr/lib/jvm/default/man/man6/pinion.6.gz
complete -c pinion -o window -d 'Draw on a newly-created window.   This is the default'
complete -c pinion -o root -d 'Draw on the root window'
complete -c pinion -o install -d 'Install a private colormap for the window'
complete -c pinion -o visual -d 'Specify which visual to use'
complete -c pinion -o delay -d 'The delay between frames of the animation, in microseconds: default 15000'
complete -c pinion -o spin -d 'How fast the gears should spin; default 1. 0.   2. 0 means twice as fast, 0'
complete -c pinion -o scroll -d 'How fast the gears should scroll past the screen; default 1. 0.    2'
complete -c pinion -o size -d 'How big the gears should be, on average; default 1. 0.   2'
complete -c pinion -o max-rpm -d 'If any gear exceeds the maximum RPM, the current gear train is broken there, …'
complete -c pinion -o wireframe -d 'Render in wireframe instead of solid'
complete -c pinion -o fps -d 'Display the current frame rate, CPU load, and polygon count'

