# pipes
# Autogenerated from man page /usr/lib/jvm/default/man/man6/pipes.6.gz
complete -c pipes -o visual -d 'Specify which visual to use'
complete -c pipes -o window -d 'Draw on a newly-created window.   This is the default'
complete -c pipes -o root -d 'Draw on the root window'
complete -c pipes -o count -d 'Curved Pipes'
complete -c pipes -o cycles -d 'Number of pipe systems to draw at once.   Default: 5'
complete -c pipes -o size -d 'Length of each pipe system.   Default: 500'
complete -c pipes -o factory -d 'How much gadgetry to create; Useful range is 0-10.   Default: 2'
complete -c pipes -o delay -d 'How long (in microseconds) to sleep between frames.   Default: 10000'
complete -c pipes -o fisheye -o no-fisheye -d 'Whether to use a fisheye lens'
complete -c pipes -o tightturns -o no-tightturns -d 'Whether to allow tight turns'
complete -c pipes -o db -o no-db -d 'Whether to double-buffer'
complete -c pipes -o fps -d 'Display the current frame rate, CPU load, and polygon count'

