# podman-volume-create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/podman-volume-create.1.gz
complete -c podman-volume-create -l driver
complete -c podman-volume-create -l help
complete -c podman-volume-create -l label -s l
complete -c podman-volume-create -l opt -s o

