# podman-machine-init
# Autogenerated from man page /usr/lib/jvm/default/man/man1/podman-machine-init.1.gz
complete -c podman-machine-init -l cpus
complete -c podman-machine-init -l disk-size
complete -c podman-machine-init -l ignition-path
complete -c podman-machine-init -l image-path
complete -c podman-machine-init -l memory -s m
complete -c podman-machine-init -l help

