# podman-system-prune
# Autogenerated from man page /usr/lib/jvm/default/man/man1/podman-system-prune.1.gz
complete -c podman-system-prune -l all -s a
complete -c podman-system-prune -l filter
complete -c podman-system-prune -l force -s f
complete -c podman-system-prune -l help -s h
complete -c podman-system-prune -l volumes

