# podman-pod-kill
# Autogenerated from man page /usr/lib/jvm/default/man/man1/podman-pod-kill.1.gz
complete -c podman-pod-kill -l all -s a
complete -c podman-pod-kill -l latest -s l
complete -c podman-pod-kill -l signal -s s

