# podman
# Autogenerated from man page /usr/lib/jvm/default/man/man1/podman.1.gz
complete -c podman -l cgroup-manager
complete -c podman -l cni-config-dir
complete -c podman -l connection -s c
complete -c podman -l conmon
complete -c podman -l events-backend
complete -c podman -l help -s h
complete -c podman -l hooks-dir
complete -c podman -l identity
complete -c podman -l log-level
complete -c podman -l namespace
complete -c podman -l network-cmd-path
complete -c podman -l remote -s r
complete -c podman -l url
complete -c podman -l root
complete -c podman -l runroot
complete -c podman -l runtime
complete -c podman -l runtime-flag
complete -c podman -l storage-driver
complete -c podman -l storage-opt
complete -c podman -l syslog
complete -c podman -l tmpdir
complete -c podman -l version -s v

