# podman-commit
# Autogenerated from man page /usr/lib/jvm/default/man/man1/podman-commit.1.gz
complete -c podman-commit -l message -d committed
complete -c podman-commit -l author -s a
complete -c podman-commit -l change -s c
complete -c podman-commit -l format -s f
complete -c podman-commit -l iidfile
complete -c podman-commit -l include-volumes
complete -c podman-commit -s m
complete -c podman-commit -l pause -s p
complete -c podman-commit -l quiet -s q

