# podman-generate-systemd
# Autogenerated from man page /usr/lib/jvm/default/man/man1/podman-generate-systemd.1.gz
complete -c podman-generate-systemd -l files -s f
complete -c podman-generate-systemd -l format
complete -c podman-generate-systemd -l name -s n
complete -c podman-generate-systemd -l new
complete -c podman-generate-systemd -l no-header
complete -c podman-generate-systemd -l time -s t
complete -c podman-generate-systemd -l restart-policy
complete -c podman-generate-systemd -l container-prefix
complete -c podman-generate-systemd -l pod-prefix
complete -c podman-generate-systemd -l separator

