# podman-volume-rm
# Autogenerated from man page /usr/lib/jvm/default/man/man1/podman-volume-rm.1.gz
complete -c podman-volume-rm -l all -s a
complete -c podman-volume-rm -l force -s f
complete -c podman-volume-rm -l help

