# podman-mount
# Autogenerated from man page /usr/lib/jvm/default/man/man1/podman-mount.1.gz
complete -c podman-mount -l all -s a
complete -c podman-mount -l format
complete -c podman-mount -l latest -s l
complete -c podman-mount -l notruncate

