# podman-generate-kube
# Autogenerated from man page /usr/lib/jvm/default/man/man1/podman-generate-kube.1.gz
complete -c podman-generate-kube -l filename -s f
complete -c podman-generate-kube -l service -s s
complete -c podman-generate-kube -l - -d 'apiVersion: v1 kind: Service metadata:   creationTimestamp: 2018-12-18T15:16:…'

