# podman-secret-create
# Autogenerated from man page /usr/lib/jvm/default/man/man1/podman-secret-create.1.gz
complete -c podman-secret-create -l env
complete -c podman-secret-create -l driver
complete -c podman-secret-create -l help

