# podman-network-prune
# Autogenerated from man page /usr/lib/jvm/default/man/man1/podman-network-prune.1.gz
complete -c podman-network-prune -l force -s f
complete -c podman-network-prune -l filter

