# providence
# Autogenerated from man page /usr/lib/jvm/default/man/man6/providence.6.gz
complete -c providence -o window -d 'Draw on a newly-created window.   This is the default'
complete -c providence -o root -d 'Draw on the root window'
complete -c providence -o install -d 'Install a private colormap for the window'
complete -c providence -o eye -d 'Draw an eye/$'
complete -c providence -o visual -d 'Specify which visual to use'
complete -c providence -o wireframe -d 'Render in wireframe (with hidden line removal) instead of as textured solids'
complete -c providence -o fps -d 'Display the current frame rate, CPU load, and polygon count'

