# pulsar
# Autogenerated from man page /usr/lib/jvm/default/man/man6/pulsar.6.gz
complete -c pulsar -o visual -d 'Specify which visual to use'
complete -c pulsar -o window -d 'Draw on a newly-created window.   This is the default'
complete -c pulsar -o root -d 'Draw on the root window'
complete -c pulsar -o light -o no-light -d 'Use Flat Coloring'
complete -c pulsar -o wire -d 'Render in wireframe instead of solid'
complete -c pulsar -o delay -d 'Per-frame delay, in microseconds.   Default: 10000 (0. 01 seconds. )'
complete -c pulsar -o image -d 'The texture map to use'
complete -c pulsar -o quads -d 'Quad Count.   1 - 50.   Default: 5'
complete -c pulsar -o fog -o no-fog -d 'Whether to enable fog'
complete -c pulsar -o texture -o no-texture -d 'Whether to enable texturing'
complete -c pulsar -o mipmap -o no-mipmap -d 'Whether to enable texture mipmaps'
complete -c pulsar -o blend -o no-blend -d 'Whether to enable blending'
complete -c pulsar -o antialias -o no-antialias -d 'Whether to anti-alias lines'
complete -c pulsar -o texture_quality -o no-texture_quality -d 'Whether to enable texture filtering'
complete -c pulsar -o do_depth -o no-do_depth -d 'Whether to enable depth buffer'
complete -c pulsar -o fps -d 'Display the current frame rate, CPU load, and polygon count'

