# pwgen
# Autogenerated from man page /usr/lib/jvm/default/man/man1/pwgen.1.gz
complete -c pwgen -s 0 -l no-numerals -d 'Don\'t include numbers in the generated passwords'
complete -c pwgen -s 1 -d 'Print the generated passwords one per line'
complete -c pwgen -s A -l no-capitalize -d 'Don\'t bother to include any capital letters in the generated passwords'
complete -c pwgen -s a -l alt-phonics -d 'This option doesn\'t do anything special; it is present only for backwards com…'
complete -c pwgen -s B -l ambiguous -d 'Don\'t use characters that could be confused by the user when printed, such as…'
complete -c pwgen -s c -l capitalize -d 'Include at least one capital letter in the password'
complete -c pwgen -s C -d 'Print the generated passwords in columns'
complete -c pwgen -s N -l num-passwords -d 'Generate   num passwords'
complete -c pwgen -s n -l numerals -d 'Include at least one number in the password'
complete -c pwgen -s H -l sha1 -d 'Will use the sha1\'s hash of given file and the optional seed to create   pass…'
complete -c pwgen -s h -l help -d 'Print a help message'
complete -c pwgen -s r -l remove-chars -d 'Don\'t use the specified characters in password'
complete -c pwgen -s s -l secure -d 'Generate completely random, hard-to-memorize passwords'
complete -c pwgen -s v -l no-vowels -d 'Generate random passwords that do not contain vowels or numbers that might be…'
complete -c pwgen -s y -l symbols -d 'Include at least one special character in the password'

