# pyro
# Autogenerated from man page /usr/lib/jvm/default/man/man6/pyro.6.gz
complete -c pyro -o window -d 'Draw on a newly-created window.   This is the default'
complete -c pyro -o root -d 'Draw on the root window'
complete -c pyro -o mono -d 'If on a color display, pretend we\'re on a monochrome display'
complete -c pyro -o install -d 'Install a private colormap for the window'
complete -c pyro -o visual -d 'Specify which visual to use'
complete -c pyro -o count -d 'How many particles should be allowed on the screen at once.   Default 600'
complete -c pyro -o frequency -d 'How often new missiles should launch.   Default 30'
complete -c pyro -o scatter -d 'How many particles should appear when a missile explodes.   Default 100'
complete -c pyro -o fps -d 'Display the current frame rate and CPU load'

