# qalter
# Autogenerated from man page /usr/lib/jvm/default/man/man1/qalter.1p.gz
complete -c qalter -o adate_time -d 'Redefine the time at which the batch job becomes eligible for execution'
complete -c qalter -o Aaccount_string -d 'br Redefine the account to which the resource consumption of the batch job sh…'
complete -c qalter -o cinterval -d 'Redefine whether the batch job should be checkpointed, and if so, how often'
complete -c qalter -o epath_name -d 'br Redefine the path to be used for the standard error stream of the batch job'
complete -c qalter -o hhold_list -d 'Redefine the types of holds, if any, on the batch job'
complete -c qalter -o jjoin_list -d 'Redefine which streams of the batch job are to be merged'
complete -c qalter -o kkeep_list -d 'Redefine which output of the batch job to retain on the execution host'
complete -c qalter -o lresource_list -d 'br Redefine the resources that are allowed or required by the batch job'
complete -c qalter -o mmail_options -d 'br Redefine the points in the execution of the batch job at which the batch s…'
complete -c qalter -o Mmail_list -d 'Redefine the list of users to which the batch server that executes the batch …'
complete -c qalter -o Nname -d 'Redefine the name of the batch job. RS 10  '
complete -c qalter -o opath_name -d 'br Redefine the path for the standard output of the batch job. RS 10  '
complete -c qalter -o ppriority -d 'Redefine the priority of the batch job. RS 10  '
complete -c qalter -o ry -d 'Redefine whether the batch job is rerunnable. RS 10  '
complete -c qalter -o Spath_name_list -d 'br Redefine the shell that interprets the script at the destination system'
complete -c qalter -s a -d 'Redefine the time at which the batch job becomes eligible for execution'
complete -c qalter -s A
complete -c qalter -s c -d 'Redefine whether the batch job should be checkpointed, and if so, how often'
complete -c qalter -s e
complete -c qalter -s h -d 'Redefine the types of holds, if any, on the batch job.  The qalter'
complete -c qalter -s j -d 'Redefine which streams of the batch job are to be merged.  The qalter'
complete -c qalter -s k -d 'Redefine which output of the batch job to retain on the execution host'
complete -c qalter -s l
complete -c qalter -s m
complete -c qalter -s M -d 'Redefine the list of users to which the batch server that executes the batch …'
complete -c qalter -s N -d 'Redefine the name of the batch job.  The qalter'
complete -c qalter -s o
complete -c qalter -s p -d 'Redefine the priority of the batch job'
complete -c qalter -s r -d 'Redefine whether the batch job is rerunnable'
complete -c qalter -s S
complete -c qalter -s u -d 'Redefine the user name under which the batch job is to run at the destination…'
complete -c qalter -s V
complete -c qalter -s v -d and
complete -c qalter -s q -d The
complete -c qalter -s P -d 'option allows users to modify the priority of a batch job'

