# qsub
# Autogenerated from man page /usr/lib/jvm/default/man/man1/qsub.1p.gz
complete -c qsub -o adate_time -d 'Define the time at which a batch job becomes eligible for execution. RS 10  '
complete -c qsub -o Aaccount_string -d 'br Define the account to which the resource consumption of the batch job shou…'
complete -c qsub -o cinterval -d 'Define whether the batch job should be checkpointed, and if so, how often'
complete -c qsub -o Cdirective_prefix -d 'br Define the prefix that declares a directive to the R qsub utility within t…'
complete -c qsub -o epath_name -d 'br Define the path to be used for the standard error stream of the batch job'
complete -c qsub -s h -d 'Specify that a USER hold is applied to the batch job. RS 10  '
complete -c qsub -o jjoin_list -d 'Define which streams of the batch job are to be merged'
complete -c qsub -o kkeep_list -d 'Define which output of the batch job to retain on the execution host. RS 10  '
complete -c qsub -o mmail_options -d 'br Define the points in the execution of the batch job at which the batch ser…'
complete -c qsub -o Mmail_list -d 'Define the list of users to which a batch server that executes the batch job …'
complete -c qsub -o Nname -d 'Define the name of the batch job. RS 10  '
complete -c qsub -o opath_name -d 'br Define the path for the standard output of the batch job. RS 10  '
complete -c qsub -o ppriority -d 'Define the priority the batch job should have relative to other batch jobs ow…'
complete -c qsub -o qdestination -d 'br Define the destination of the batch job. RS 10  '
complete -c qsub -o ry -d 'Define whether the batch job is rerunnable. RS 10  '
complete -c qsub -o Spath_name_list -d 'br Define the pathname to the shell under which the batch job is to execute'
complete -c qsub -o uuser_list -d 'Define the user name under which the batch job is to execute. RS 10  '
complete -c qsub -o vvariable_list -d 'br Add to the list of variables that are exported to the session leader of th…'
complete -c qsub -s V -d 'Specify that all of the environment variables of the process are exported to …'
complete -c qsub -s a -d 'Define the time at which a batch job becomes eligible for execution'
complete -c qsub -s A
complete -c qsub -s c -d 'Define whether the batch job should be checkpointed, and if so, how often'
complete -c qsub -s C
complete -c qsub -s e
complete -c qsub -s j -d 'Define which streams of the batch job are to be merged.  The qsub'
complete -c qsub -s k -d 'Define which output of the batch job to retain on the execution host'
complete -c qsub -s m
complete -c qsub -s M -d 'Define the list of users to which a batch server that executes the batch job …'
complete -c qsub -s N -d 'Define the name of the batch job.  The qsub'
complete -c qsub -s o
complete -c qsub -s p -d 'Define the priority the batch job should have relative to other batch jobs ow…'
complete -c qsub -s q
complete -c qsub -s r -d 'Define whether the batch job is rerunnable'
complete -c qsub -s S
complete -c qsub -s u -d 'Define the user name under which the batch job is to execute'
complete -c qsub -s v
complete -c qsub -s z -d 'Specify that the utility does not write the batch job_identifier of the creat…'
complete -c qsub -s P -d 'option allows users to designate the relative priority of a batch job for sel…'

