# randpkt
# Autogenerated from man page /usr/lib/jvm/default/man/man1/randpkt.1.gz
complete -c randpkt -s b -d 'Default 5000'
complete -c randpkt -s c -d 'Default 1000. Sp Defines the number of packets to generate'

