# renice
# Autogenerated from man page /usr/lib/jvm/default/man/man1/renice.1p.gz
complete -c renice -o nincrement -d 'Specify how the nice value of the specified process or processes is to be adj…'

