# ripples
# Autogenerated from man page /usr/lib/jvm/default/man/man6/ripples.6.gz
complete -c ripples -o visual -d 'Specify which visual to use'
complete -c ripples -o window -d 'Draw on a newly-created window.   This is the default'
complete -c ripples -o root -d 'Draw on the root window'
complete -c ripples -o delay -d 'Per-frame delay, in microseconds.   Default: 50000 (0. 05 seconds. )'
complete -c ripples -o duration -d 'How long to run before loading a new image.   Default 120 seconds'
complete -c ripples -o rate -d 'Drizzle.   1 - 100.   Default: 5'
complete -c ripples -o fluidity -d 'Small Drops.   0 - 16.   Default: 6'
complete -c ripples -o light -d 'Lighting Effect.   0 - 8.   Default: 0'
complete -c ripples -o water -o no-water -d 'Grab Screen Image.   Boolean'
complete -c ripples -o stir -o no-stir -d 'Moving Splashes.   Boolean'
complete -c ripples -o oily -o no-oily -d 'Psychedelic Colors.   Boolean'
complete -c ripples -o grayscale -d 'Convert the screen image to grayscale'
complete -c ripples -o colors -d 'Colors Two.   Default: 200'
complete -c ripples -o shm -o no-shm -d 'Use Shared Memory.   Boolean'
complete -c ripples -o fps -d 'Display the current frame rate and CPU load'

