# rocks
# Autogenerated from man page /usr/lib/jvm/default/man/man6/rocks.6.gz
complete -c rocks -o window -d 'Draw on a newly-created window.   This is the default'
complete -c rocks -o root -d 'Draw on the root window'
complete -c rocks -o mono -d 'Make all the rocks the same color'
complete -c rocks -o ncolors -d 'How many different colors to use.   Default 5.   Colors are chosen randomly'
complete -c rocks -o install -d 'Install a private colormap for the window'
complete -c rocks -o visual -d 'Specify which visual to use'
complete -c rocks -o count -d 'Maximum number of rocks to draw on the screen at once.   Default 100'
complete -c rocks -o speed -d 'A measure of the speed with which the observer and the rocks pass each other,…'
complete -c rocks -o delay -d 'Number of microseconds to delay between each frame'
complete -c rocks -o norotate -d 'Don\'t rotate the observer; just fly through the field on the level'
complete -c rocks -o nomove -d 'Don\'t turn the observer; just fly straight ahead through the field'
complete -c rocks -o 3d -d 'Do red/blue 3d separations: if you look at the screen with 3d glasses, the ro…'
complete -c rocks -o fps -d 'Display the current frame rate and CPU load'

