# rotzoomer
# Autogenerated from man page /usr/lib/jvm/default/man/man6/rotzoomer.6.gz
complete -c rotzoomer -o window -d 'Draw on a newly-created window.   This is the default'
complete -c rotzoomer -o root -d 'Draw on the root window'
complete -c rotzoomer -o install -d 'Install a private colormap for the window'
complete -c rotzoomer -o visual -d 'Specify which visual to use'
complete -c rotzoomer -o delay -d 'How much of a delay should be introduced between steps of the animation'
complete -c rotzoomer -o duration -d 'How long to run before loading a new image.   Default 120 seconds'
complete -c rotzoomer -o move -d 'Make the rectangles should wander around the screen'
complete -c rotzoomer -o no-move -d 'Make the rectangles be stationary.   This is the default'
complete -c rotzoomer -s n -d 'How many rectangles to animate simultaneously.   Default 2'
complete -c rotzoomer -o no-shm -d 'Disable use of the SHM extension, even if it appears to be available'
complete -c rotzoomer -o fps -d 'Display the current frame rate and CPU load'

