# runc-exec
# Autogenerated from man page /usr/lib/jvm/default/man/man8/runc-exec.8.gz
complete -c runc-exec -l console
complete -c runc-exec -l cwd
complete -c runc-exec -l env -s e
complete -c runc-exec -l tty -s t
complete -c runc-exec -l user -s u
complete -c runc-exec -l additional-gids -s g
complete -c runc-exec -l process -s p
complete -c runc-exec -l detach -s d
complete -c runc-exec -l pid-file
complete -c runc-exec -l process-label
complete -c runc-exec -l apparmor
complete -c runc-exec -l no-new-privs
complete -c runc-exec -l cap -s c
complete -c runc-exec -l no-subreaper
complete -c runc-exec -l preserve-fds

