# sccs
# Autogenerated from man page /usr/lib/jvm/default/man/man1/sccs.1p.gz
complete -c sccs -o dpath -d 'A pathname of a directory to be used as a root directory for the SCCS files'
complete -c sccs -o ppath -d 'A pathname of a directory in which the SCCS files are located'
complete -c sccs -s d -d 'A pathname of a directory to be used as a root directory for the SCCS files'
complete -c sccs -s p
complete -c sccs -s r -d 'Invoke command with the real user ID of the process, not any effective user I…'
complete -c sccs -s b -d 'option is given, branches shall be ignored in the determination of whether th…'
complete -c sccs -s m
complete -c sccs -s s -d and
complete -c sccs -s y -d 'options shall be passed to delta , and any'
complete -c sccs -s c
complete -c sccs -s e
complete -c sccs -s i
complete -c sccs -s k
complete -c sccs -s l
complete -c sccs -s x -d 'options shall be passed to get '
complete -c sccs -s t -d 'options shall be passed to get ; any'
complete -c sccs -s f
complete -c sccs -s h -d and
complete -c sccs -s C -d 'option shall be passed to diff as'
complete -c sccs -s u -d 'user option is given, then only files being edited by the named user shall be…'
complete -c sccs -s U -d 'option shall be equivalent to'

