# sed
# Autogenerated from man page /usr/lib/jvm/default/man/man1/sed.1p.gz
complete -c sed -o escript -d 'Add the editing commands specified by the R script option-argument to the end…'
complete -c sed -o fscript_file -d 'Add the editing commands in the file R script_file to the end of the script o…'

