# set
# Autogenerated from man page /usr/lib/jvm/default/man/man1/set.1p.gz
complete -c set -s a -d 'When this option is on, the export attribute shall be set for each variable t…'
complete -c set -s b -d 'This option shall be supported if the implementation supports the User Portab…'
complete -c set -s C -d '(Uppercase C'
complete -c set -s e -d 'When this option is on, when any command fails (for any of the reasons listed…'
complete -c set -s f -d 'The shell shall disable pathname expansion'
complete -c set -s h -d 'Locate and remember utilities invoked by functions as those functions are def…'
complete -c set -s m -d 'This option shall be supported if the implementation supports the User Portab…'
complete -c set -s n -d 'The shell shall read commands but does not execute them; this can be used to …'
complete -c set -s o -d 'Write the current settings of the options to standard output in an unspecifie…'
complete -c set -s u -d 'verbose 10 Equivalent to'
complete -c set -s v -d 'vi 10 Allow shell command line editing using the built-in vi editor'
complete -c set -s x
complete -c set -s k -d The
complete -c set -s t -d The
complete -c set -o able -d 'option syntax'

