# sh
# Autogenerated from man page /usr/lib/jvm/default/man/man1/sh.1p.gz
complete -c sh -s c -d 'Read commands from the R command_string operand'
complete -c sh -s i -d 'Specify that the shell is R interactive ; see below'
complete -c sh -s a
complete -c sh -s b
complete -c sh -s C
complete -c sh -s e
complete -c sh -s f
complete -c sh -s m
complete -c sh -s n
complete -c sh -s o -d 'option ,'
complete -c sh -s u
complete -c sh -s v -d and
complete -c sh -s x -d 'options are described as part of the set utility in Section 2'
complete -c sh -s s -d 'Read commands from the standard input'
complete -c sh -s r -d 'option) were excluded because the standard developers considered that the imp…'

