# sierpinski3d
# Autogenerated from man page /usr/lib/jvm/default/man/man6/sierpinski3d.6.gz
complete -c sierpinski3d -o visual -d 'Specify which visual to use'
complete -c sierpinski3d -o window -d 'Draw on a newly-created window.   This is the default'
complete -c sierpinski3d -o root -d 'Draw on the root window'
complete -c sierpinski3d -o delay -d 'Per-frame delay, in microseconds.   Default: 20000 (0. 02 seconds. )'
complete -c sierpinski3d -o speed -d 'Number of frames before changing shape.   Default: 150'
complete -c sierpinski3d -o depth -d 'Max depth to descend.   Default: 5'
complete -c sierpinski3d -o wireframe -d 'Render in wireframe instead of solid'
complete -c sierpinski3d -o fps -d 'Display the current frame rate, CPU load, and polygon count'

