# skopeo-logout
# Autogenerated from man page /usr/lib/jvm/default/man/man1/skopeo-logout.1.gz
complete -c skopeo-logout -l authfile -d 'Path of the authentication file'
complete -c skopeo-logout -l all -s a -d 'Remove the cached credentials for all registries in the auth file'
complete -c skopeo-logout -l help -s h -d 'Print usage statement'

