# skopeo-inspect
# Autogenerated from man page /usr/lib/jvm/default/man/man1/skopeo-inspect.1.gz
complete -c skopeo-inspect -l authfile -d 'Path of the authentication file'
complete -c skopeo-inspect -l cert-dir -d 'Use certificates at path (*. crt, *. cert, *. key) to connect to the registry'
complete -c skopeo-inspect -l config -d 'Output configuration in OCI format, default is to format in JSON format'
complete -c skopeo-inspect -l creds -d 'Username and password for accessing the registry'
complete -c skopeo-inspect -l format -s f -d 'Format the output using the given Go template'
complete -c skopeo-inspect -l no-creds -d 'Access the registry anonymously'
complete -c skopeo-inspect -l raw -d 'Output raw manifest or config data depending on --config option'
complete -c skopeo-inspect -l registry-token -d 'Registry token for accessing the registry'
complete -c skopeo-inspect -l retry-times -d 'The number of times to retry; retry wait time will be exponentially increased…'
complete -c skopeo-inspect -l tls-verify -d 'Require HTTPS and verify certificates when talking to container registries (d…'

