# skopeo
# Autogenerated from man page /usr/lib/jvm/default/man/man1/skopeo.1.gz
complete -c skopeo -l command-timeout
complete -c skopeo -l debug
complete -c skopeo -l help -s h
complete -c skopeo -l insecure-policy
complete -c skopeo -l override-arch
complete -c skopeo -l override-os
complete -c skopeo -l override-variant
complete -c skopeo -l policy
complete -c skopeo -l 'registries.d'
complete -c skopeo -l tmpdir
complete -c skopeo -l version -s v

