# skytentacles
# Autogenerated from man page /usr/lib/jvm/default/man/man6/skytentacles.6.gz
complete -c skytentacles -o visual -d 'Specify which visual to use'
complete -c skytentacles -o window -d 'Draw on a newly-created window.   This is the default'
complete -c skytentacles -o root -d 'Draw on the root window'
complete -c skytentacles -o delay -d 'Delay between frames, in microseconds.   Default 30000'
complete -c skytentacles -o speed -d 'Less than 1 for slower, greater than 1 for faster.   Default 1'
complete -c skytentacles -o count -d 'How many tentacles.   Default 8'
complete -c skytentacles -o thickness -d 'Less than 1 for thinner tentacles, greater than 1 for thicker.   Default 1'
complete -c skytentacles -o length -d 'Length of the tentacles.   Default 9'
complete -c skytentacles -o wiggliness -d 'A measure of how bendy the tentacles are'
complete -c skytentacles -o flexibility -d 'Another measure of how bendy the tentacles are'
complete -c skytentacles -o sucker-color -d 'The colors of the various parts of the tentacle'
complete -c skytentacles -o segments -d 'Larger numbers increase number of polygons in the object mesh.  Default 32'
complete -c skytentacles -o no-smooth -d 'Make the tentacles appear faceted instead of smooth'
complete -c skytentacles -o color
complete -c skytentacles -o stripe-color
complete -c skytentacles -o slices
complete -c skytentacles -o fps -d 'Display the current frame rate, CPU load, and polygon count'

