# slidescreen
# Autogenerated from man page /usr/lib/jvm/default/man/man6/slidescreen.6.gz
complete -c slidescreen -o window -d 'Draw on a newly-created window.   This is the default'
complete -c slidescreen -o root -d 'Draw on the root window'
complete -c slidescreen -o install -d 'Install a private colormap for the window'
complete -c slidescreen -o visual -d 'Specify which visual to use'
complete -c slidescreen -o grid-size -d 'The size of the grid cells.   Default 70 pixels'
complete -c slidescreen -o ibw -d 'The size of the "gutter" between grid cells.   Default 4 pixel'
complete -c slidescreen -o increment -d 'How many pixels by which a piece should be moved when sliding to a new  locat…'
complete -c slidescreen -o delay -d 'How much of a delay should be introduced between steps of the animation of th…'
complete -c slidescreen -o delay2 -d 'How much of a delay should be introduced between the end of the motion of one…'
complete -c slidescreen -o duration -d 'How long to run before loading a new image.   Default 120 seconds'
complete -c slidescreen -o fps -d 'Display the current frame rate and CPU load'

