# slip
# Autogenerated from man page /usr/lib/jvm/default/man/man6/slip.6.gz
complete -c slip -o window -d 'Draw on a newly-created window.   This is the default'
complete -c slip -o root -d 'Draw on the root window'
complete -c slip -o mono -d 'If on a color display, pretend we\'re on a monochrome display'
complete -c slip -o install -d 'Install a private colormap for the window'
complete -c slip -o visual -d 'Specify which visual to use'
complete -c slip -o ncolors -d 'How many colors should be used (if possible).   Default 200'
complete -c slip -o count -d 'How many whooziwhatsis to generate.   Default 35'
complete -c slip -o cycles -d 'How long to frobnicate.   Default 50'
complete -c slip -o delay -d 'How long we should wait between drawing each step'
complete -c slip -o fps -d 'Display the current frame rate and CPU load'

