# sonar
# Autogenerated from man page /usr/lib/jvm/default/man/man6/sonar.6.gz
complete -c sonar -o ping -d 'The list of things to ping, separated by commas or spaces'
complete -c sonar -o ping-timeout -d 'The amount of time in milliseconds the program will wait for an answer to a p…'
complete -c sonar -o delay -d 'Delay between frames, in microseconds.   Default 20000'
complete -c sonar -o speed -d 'Less than 1 for slower, greater than 1 for faster.   Default 1'
complete -c sonar -o sweep-size -d 'How big the glowing sweep area should be.  Default 0. 3'
complete -c sonar -o font-size -d 'How large the text should be.   Default 10 points'
complete -c sonar -o no-wobble -d 'Keep the display stationary instead of very slowly wobbling back and forth'
complete -c sonar -o no-dns -d 'Do not attempt to resolve IP addresses to hostnames'
complete -c sonar -o no-times -d 'Do not display ping times beneath the host names'
complete -c sonar -o team-a-name -d 'In simulation mode, the name of team A'
complete -c sonar -o team-b-name -d 'In simulation mode, the name of team B'
complete -c sonar -o team-a-count -d 'In simulation mode, the number of bogies on team A'
complete -c sonar -o team-b-count -d 'In simulation mode, the number of bogies on team B'
complete -c sonar -o fps -d 'Display the current frame rate, polygon count, and CPU load'

