# splitflap
# Autogenerated from man page /usr/lib/jvm/default/man/man6/splitflap.6.gz
complete -c splitflap -o visual -d 'Specify which visual to use'
complete -c splitflap -o window -d 'Draw on a newly-created window.   This is the default'
complete -c splitflap -o root -d 'Draw on the root window'
complete -c splitflap -o delay -d 'Per-frame delay, in microseconds.   Default: 20000 (0. 02 seconds)'
complete -c splitflap -o speed -d 'Animation speed.   2. 0 means twice as fast, 0. 5 means half as fast'
complete -c splitflap -o width -d 'Columns of the display.   Default: 22'
complete -c splitflap -o height -d 'Rows of the display.  Default: 8'
complete -c splitflap -o mode -d 'Display a 12-hour clock'
complete -c splitflap -o front -o no-front -d 'When spinning, never spin all the way around or upside down: always face most…'
complete -c splitflap -o wander -o no-wander -d 'Whether the object should wander around the screen'
complete -c splitflap -o spin -d 'Which axes around which the text should spin'
complete -c splitflap -o wireframe -o no-wireframe -d 'Render in wireframe instead of solid'
complete -c splitflap -o fps -o no-fps -d 'Whether to show a frames-per-second display at the bottom of the screen'

