# splodesic
# Autogenerated from man page /usr/lib/jvm/default/man/man6/splodesic.6.gz
complete -c splodesic -o visual -d 'Specify which visual to use'
complete -c splodesic -o window -d 'Draw on a newly-created window.   This is the default'
complete -c splodesic -o root -d 'Draw on the root window'
complete -c splodesic -o wander -o no-wander -d 'Whether the object should wander around the screen'
complete -c splodesic -o spin -o no-spin -d 'Whether the object should spin'
complete -c splodesic -o fps -o no-fps -d 'Whether to show a frames-per-second display at the bottom of the screen'
complete -c splodesic -o delay -d 'Per-frame delay, in microseconds.   Default: 30000 (0. 03 seconds)'
complete -c splodesic -o speed -d 'Frequency of eruptions.   2. 0 means twice as often, 0. 5 means half as often'
complete -c splodesic -o depth -d 'Depth (frequency) of the geodesic.  0 - 5.  Default: 4'

