# squiral
# Autogenerated from man page /usr/lib/jvm/default/man/man6/squiral.6.gz
complete -c squiral -o window -d 'Draw on a newly-created window.   This is the default'
complete -c squiral -o root -d 'Draw on the root window'
complete -c squiral -o mono -d 'If on a color display, pretend we\'re on a monochrome display'
complete -c squiral -o install -d 'Install a private colormap for the window'
complete -c squiral -o visual -d 'Specify which visual to use'
complete -c squiral -o fill -d 'Specify the percent (0-100) of the screen which must be filled before the scr…'
complete -c squiral -o count -d 'The number of squiralies.   By default, the screen width divided by 32'
complete -c squiral -o delay -d 'The wait between steps.   The default is 1000'
complete -c squiral -o disorder -d 'The fraction of the time a squiraly will choose a new direction'
complete -c squiral -o handedness -d 'The fraction of the time a squiraly will choose to enter lefthanded mode.   0'
complete -c squiral -o fps -d 'Display the current frame rate and CPU load'

