# sshdump
# Autogenerated from man page /usr/lib/jvm/default/man/man1/sshdump.1.gz
complete -c sshdump -l help -d 'PD Print program arguments'
complete -c sshdump -l version -d 'Print program version'
complete -c sshdump -l extcap-interfaces -d 'List available interfaces'
complete -c sshdump -l extcap-interface -d 'Use specified interfaces'
complete -c sshdump -l extcap-dlts -d 'List DLTs of specified interface'
complete -c sshdump -l extcap-config -d 'List configuration options of specified interface'
complete -c sshdump -l capture -d 'Start capturing from specified interface and write raw packet data to the loc…'
complete -c sshdump -l fifo -d 'Save captured packet to file or send it through pipe'
complete -c sshdump -l remote-host -d 'The address of the remote host for capture'
complete -c sshdump -l remote-port -d 'The \\s-1SSH\\s0 port of the remote host'
complete -c sshdump -l remote-username -d 'The username for ssh authentication'
complete -c sshdump -l remote-password -d 'The password to use (if not ssh-agent and pubkey are used)'
complete -c sshdump -l sshkey -d 'The path to a private key for authentication'
complete -c sshdump -l remote-interface -d 'The remote network interface to capture from'
complete -c sshdump -l remote-capture-command -d 'A custom remote capture command that produces the remote stream that is shown…'

