# stonerview
# Autogenerated from man page /usr/lib/jvm/default/man/man6/stonerview.6.gz
complete -c stonerview -o visual -d 'Specify which visual to use'
complete -c stonerview -o window -d 'Draw on a newly-created window.   This is the default'
complete -c stonerview -o root -d 'Draw on the root window'
complete -c stonerview -o wireframe -d 'Render in wireframe instead of solid'
complete -c stonerview -o fps -d 'Display the current frame rate, CPU load, and polygon count'

