# tabs
# Autogenerated from man page /usr/lib/jvm/default/man/man1/tabs.1p.gz
complete -c tabs -s 8
complete -c tabs -s 0 -d 'is used, the tab stops shall be cleared and no new ones set'
complete -c tabs -s t -d 'tablist option was added for consistency with expand ; this was later removed…'

