# tail
# Autogenerated from man page /usr/lib/jvm/default/man/man1/tail.1p.gz
complete -c tail -o cnumber -d 'The application shall ensure that the R number option-argument is a decimal i…'
complete -c tail -o @Relative -d 'none@Relative to the end of the file'
complete -c tail -s 1
complete -c tail -s b -d 'option was omitted because of the general non-portability of block-sized unit…'

