# tessellimage
# Autogenerated from man page /usr/lib/jvm/default/man/man6/tessellimage.6.gz
complete -c tessellimage -o visual -d 'Specify which visual to use'
complete -c tessellimage -o window -d 'Draw on a newly-created window.   This is the default'
complete -c tessellimage -o root -d 'Draw on the root window'
complete -c tessellimage -o delay -d 'Per-frame delay, in microseconds.   Default: 30000 (0. 03 seconds)'
complete -c tessellimage -o duration -d 'Length of time until loading a new image.  Default: 2 minutes'
complete -c tessellimage -o duration2 -d 'Length of time until increasing or decreasing the triangulation depth'
complete -c tessellimage -o max-depth -d 'The maximum number of triangles to render.   Default: 40000'
complete -c tessellimage -o max-resolution -d 'The size of the loaded image will be constrained to this width or height, to …'
complete -c tessellimage -o outline -o no-outline -d 'Whether to outline the triangles'
complete -c tessellimage -o fill-screen -o no-fill-screen -d 'Whether to zoom in on the image to completely fill the screen, or to center it'
complete -c tessellimage -o fps -o no-fps -d 'Whether to show a frames-per-second display at the bottom of the screen'

