# test
# Autogenerated from man page /usr/lib/jvm/default/man/man1/test.1p.gz
complete -c test -o primary_operator -d 'are known as unary primaries '
complete -c test -s C -d 'True if file is a contiguous file'
complete -c test -s V -d 'True if file is a version file'
complete -c test -s l -d 'The length of the string string '

