# touch
# Autogenerated from man page /usr/lib/jvm/default/man/man1/touch.1p.gz
complete -c touch -o ddate_time -d 'Use the specified R date_time instead of the current time'
complete -c touch -o rref_file -d 'Use the corresponding time of the file named by the pathname R ref_file inste…'
complete -c touch -o ttime -d 'Use the specified R time instead of the current time'

