# triangle
# Autogenerated from man page /usr/lib/jvm/default/man/man6/triangle.6.gz
complete -c triangle -o visual -d 'Specify which visual to use'
complete -c triangle -o window -d 'Draw on a newly-created window.   This is the default'
complete -c triangle -o root -d 'Draw on the root window'
complete -c triangle -o delay -d 'Per-frame delay, in microseconds.   Default: 10000 (0. 01 seconds. )'
complete -c triangle -o ncolors -d 'Number of Colors.   Default: 128'
complete -c triangle -o fps -d 'Display the current frame rate and CPU load'

