# unknownpleasures
# Autogenerated from man page /usr/lib/jvm/default/man/man6/unknownpleasures.6.gz
complete -c unknownpleasures -o visual -d 'Specify which visual to use'
complete -c unknownpleasures -o window -d 'Draw on a newly-created window.   This is the default'
complete -c unknownpleasures -o root -d 'Draw on the root window'
complete -c unknownpleasures -o delay -d 'Per-frame delay, in microseconds.   Default: 30000 (0. 03 seconds)'
complete -c unknownpleasures -o speed -d 'Animation speed.  2 for twice as fast, 0. 5 for half as fast'
complete -c unknownpleasures -o count -d 'Scanlines (vertical resolution).   Default: 80'
complete -c unknownpleasures -o resolution -d 'Horizontal Resolution, Default: 100'
complete -c unknownpleasures -o amplitude -d 'Height of the waves, 0 - 1. 0.   Default: 0. 13'
complete -c unknownpleasures -o noise -d 'How noisy the signal is.  2 for twice as noisy, 0. 5 for half as noisy'
complete -c unknownpleasures -o mask -d 'Use the given image file as a clipping mask against the data'
complete -c unknownpleasures -o ortho -o no-ortho -d 'Whether to use an orthographic projection'
complete -c unknownpleasures -o buzz -o no-buzz -d 'Whether each line should seethe with noise'
complete -c unknownpleasures -o wireframe -o no-wireframe -d 'Render in wireframe instead of solid'
complete -c unknownpleasures -o fps -o no-fps -d 'Whether to show a frames-per-second display at the bottom of the screen'

