# unset
# Autogenerated from man page /usr/lib/jvm/default/man/man1/unset.1p.gz
complete -c unset -s v -d 'is specified, name refers to a variable name and the shell shall unset it and…'
complete -c unset -s f -d 'is specified, name refers to a function and the shell shall unset the functio…'

