# uux
# Autogenerated from man page /usr/lib/jvm/default/man/man1/uux.1p.gz
complete -c uux -s j -d 'Write the job identification string to standard output'
complete -c uux -s n -d 'Do not notify the user if the command fails'
complete -c uux -s p -d 'Make the standard input to uux the standard input to the command-string '

