# voronoi
# Autogenerated from man page /usr/lib/jvm/default/man/man6/voronoi.6.gz
complete -c voronoi -o visual -d 'Specify which visual to use'
complete -c voronoi -o window -d 'Draw on a newly-created window.   This is the default'
complete -c voronoi -o root -d 'Draw on the root window'
complete -c voronoi -o points -d 'How many points to add each time we zoom in'
complete -c voronoi -o point-size -d 'How big to draw the stars, in pixels.   0 for no stars'
complete -c voronoi -o point-speed -d 'How fast the points should wander'
complete -c voronoi -o point-delay -d 'How quickly to insert new points, when adding'
complete -c voronoi -o zoom-speed -d 'How fast to zoom in.  Less than 1 for slower, greater than 1 for faster'
complete -c voronoi -o zoom-delay -d 'Zoom in every this-many seconds'
complete -c voronoi -o fps -d 'Display the current frame rate, CPU load, and polygon count'

