# wander
# Autogenerated from man page /usr/lib/jvm/default/man/man6/wander.6.gz
complete -c wander -o visual -d 'Specify which visual to use'
complete -c wander -o window -d 'Draw on a newly-created window.   This is the default'
complete -c wander -o root -d 'Draw on the root window'
complete -c wander -o density -d 'Density.   1 - 30.   Default: 2'
complete -c wander -o reset -d 'Number of frames before resetting.   Default: 2500000'
complete -c wander -o length -d 'Number of iterations. 	Default: 25000'
complete -c wander -o delay -d 'Sustain.   0 - 60.   Default: 1'
complete -c wander -o circles -o no-circles -d 'Whether to draw spots'
complete -c wander -o size -d 'Size.   0 - 100.   Default: 1'
complete -c wander -o advance -d 'Color Contrast.   1 - 100.   Default: 1'
complete -c wander -o fps -d 'Display the current frame rate and CPU load'

