# wormhole
# Autogenerated from man page /usr/lib/jvm/default/man/man6/wormhole.6.gz
complete -c wormhole -o window -d 'Draw on a newly-created window.   This is the default'
complete -c wormhole -o root -d 'Draw on the root window'
complete -c wormhole -o mono -d 'Make all the rocks the same color'
complete -c wormhole -o install -d 'Install a private colormap for the window'
complete -c wormhole -o visual -d 'Specify which visual to use'
complete -c wormhole -o stars -d 'Number of stars to create every animation loop'
complete -c wormhole -o zspeed -d 'Speed light streaks fly by'
complete -c wormhole -o delay -d 'Number of microseconds to delay between each frame'
complete -c wormhole -o fps -d 'Display the current frame rate and CPU load'

