# xargs
# Autogenerated from man page /usr/lib/jvm/default/man/man1/xargs.1p.gz
complete -c xargs -o Eeofstr -d 'Use R eofstr as the logical end-of-file string'
complete -c xargs -o Ireplstr -d 'Insert mode: R utility is executed for each logical line from standard input'
complete -c xargs -o Lnumber -d 'The R utility shall be executed for each non-empty R number lines of argument…'
complete -c xargs -o nnumber -d 'Invoke R utility using as many standard input arguments as possible, up to R …'
complete -c xargs -o ssize -d 'Invoke R utility using as many standard input arguments as possible yielding …'
complete -c xargs -o print -d 'or ls into commands to be executed, unexpected results are likely if any file…'
complete -c xargs -o exec -d 'with a \'+\'  terminator instead of \';\' '

