# xmatrix
# Autogenerated from man page /usr/lib/jvm/default/man/man6/xmatrix.6.gz
complete -c xmatrix -o window -d 'Draw on a newly-created window.   This is the default'
complete -c xmatrix -o root -d 'Draw on the root window'
complete -c xmatrix -o install -d 'Install a private colormap for the window'
complete -c xmatrix -o visual -d 'Specify which visual to use'
complete -c xmatrix -o delay -d 'The delay between steps of the animation, in microseconds: default 10000'
complete -c xmatrix -o density -d 'The approximate percentage of the screen that should be filled with  characte…'
complete -c xmatrix -o top -o bottom -o both -d 'If -top is specified, the characters will only drop in from the top of the sc…'
complete -c xmatrix -o small -o large -d 'These options specify the sizes of the characters.   The default is -large'
complete -c xmatrix -o mode -d 'Start off with a representation of a phone number being traced'
complete -c xmatrix -o phone -d 'The phone number to trace, if -trace is specified'
complete -c xmatrix -o program -d 'The command to run to generate the text to display'

