# xrayswarm
# Autogenerated from man page /usr/lib/jvm/default/man/man6/xrayswarm.6.gz
complete -c xrayswarm -o visual -d 'Specify which visual to use'
complete -c xrayswarm -o window -d 'Draw on a newly-created window.   This is the default'
complete -c xrayswarm -o root -d 'Draw on the root window'
complete -c xrayswarm -o delay -d 'Per-frame delay, in microseconds.   Default: 0 (0. 00 seconds. )'

