# xscreensaver-demo
# Autogenerated from man page /usr/lib/jvm/default/man/man1/xscreensaver-demo.1.gz
complete -c xscreensaver-demo -o display -d 'The X display to use'
complete -c xscreensaver-demo -o prefs -d 'Start up with the Advanced tab selected by default instead of the Display Mod…'
complete -c xscreensaver-demo -o debug -d 'Causes lots of diagnostics to be printed on stderr'

