# zoom
# Autogenerated from man page /usr/lib/jvm/default/man/man6/zoom.6.gz
complete -c zoom -o window -d 'Draw on a newly-created window.   This is the default'
complete -c zoom -o root -d 'Draw on the root window'
complete -c zoom -o mono -d 'If on a color display, pretend we\'re on a monochrome display'
complete -c zoom -o install -d 'Install a private colormap for the window'
complete -c zoom -o visual -d 'Specify which visual to use'
complete -c zoom -o delay -d 'Slow it down'
complete -c zoom -o duration -d 'How long to run before loading a new image.   Default 120 seconds'
complete -c zoom -o lenses -d 'Instead of doing magnification we just copy an offset region from the origina…'
complete -c zoom -o pixwidth -d 'Width of the magnified pixels'
complete -c zoom -o pixheight -d 'Height of the magnified pixels'
complete -c zoom -o pixspacex -d 'Amount of black space between magnified pixels (X direction)'
complete -c zoom -o pixspacey -d 'Amount of black space between magnified pixels (Y direction)'
complete -c zoom -o lensoffsetx -d 'Distance in X direction between consecutive copied regions (only effective wh…'
complete -c zoom -o lensoffsety -d 'Distance in Y direction between consecutive copied regions (only effective wh…'

